<?php

namespace App\Http\Controllers;

use App\Models\Asset;
use App\Models\Delivery;
use App\Models\DeliveryProof;
use App\Models\Product;
use App\Models\Rental;
use App\Models\RentalAsset;
use App\Models\RentalItem;
use App\Models\Role;
use App\Models\Sale;
use App\Services\Deliveries\DeliveryProofService;
use App\Services\Deliveries\DeliveryWorkflowService;
use App\Services\Metrics\LogisticsMetricsService;
use App\Models\Staff;
use App\Models\User;
use App\Support\ActivityLogger;
use App\Support\PhoneNumber;
use Illuminate\Http\Request;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Pagination\Paginator;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\Rules\Exists;
use Illuminate\Validation\Rule;
use Illuminate\Validation\ValidationException;

class DeliveryController extends Controller
{
    private ?bool $hasAssignedStaffColumn = null;
    private ?bool $hasAssignmentTypeColumn = null;
    private ?bool $hasAssignedUserColumn = null;
    private ?bool $hasThirdPartyNameColumn = null;
    private ?bool $hasThirdPartyContactColumn = null;
    private ?bool $hasThirdPartyPhoneColumn = null;
    private ?bool $hasSaleColumn = null;
    private ?bool $hasRentalSaleItemsTable = null;
    private ?bool $hasDeliveryProofsTable = null;

    private function hasRentalAssetsTable(): bool
    {
        return \App\Models\RentalAsset::hasTable();
    }

    private function hasRentalItemsTable(): bool
    {
        return \App\Models\Rental::hasRentalItemsTable();
    }

    private function hasRentalSaleItemsTable(): bool
    {
        return $this->hasRentalSaleItemsTable ??= \App\Models\Rental::hasSaleItemsTable();
    }

    private function hasDeliveryProofsTable(): bool
    {
        return $this->hasDeliveryProofsTable ??= Schema::hasTable('delivery_proofs');
    }

    private function hasAssignedStaffColumn(): bool
    {
        return $this->hasAssignedStaffColumn ??= Schema::hasColumn('deliveries', 'assigned_staff_id');
    }

    private function hasAssignmentTypeColumn(): bool
    {
        return $this->hasAssignmentTypeColumn ??= Schema::hasColumn('deliveries', 'assignment_type');
    }

    private function hasAssignedUserColumn(): bool
    {
        return $this->hasAssignedUserColumn ??= Schema::hasColumn('deliveries', 'assigned_user_id');
    }

    private function hasThirdPartyNameColumn(): bool
    {
        return $this->hasThirdPartyNameColumn ??= Schema::hasColumn('deliveries', 'third_party_name');
    }

    private function hasThirdPartyContactColumn(): bool
    {
        return $this->hasThirdPartyContactColumn ??= Schema::hasColumn('deliveries', 'third_party_contact');
    }

    private function hasThirdPartyPhoneColumn(): bool
    {
        return $this->hasThirdPartyPhoneColumn ??= Schema::hasColumn('deliveries', 'third_party_phone');
    }

    private function hasSaleColumn(): bool
    {
        return $this->hasSaleColumn ??= Schema::hasColumn('deliveries', 'sale_id');
    }

    private function hasAutoGeneratedRentalSaleColumn(): bool
    {
        return Schema::hasColumn('sales', 'auto_generated_from_rental');
    }

    private function deliveryWorkflowService(): DeliveryWorkflowService
    {
        return app(DeliveryWorkflowService::class);
    }

    private function deliveryProofService(): DeliveryProofService
    {
        return app(DeliveryProofService::class);
    }

    private function logisticsMetrics(): LogisticsMetricsService
    {
        return app(LogisticsMetricsService::class);
    }

    private function availableSaleAssets(?Sale $selectedSale = null)
    {
        $selectedAssetIds = collect();

        if ($selectedSale?->asset_id) {
            $selectedAssetIds = collect([(int) $selectedSale->asset_id]);
        }

        return Asset::query()
            ->with(['product', 'warehouse'])
            ->where('organization_id', $this->orgId())
            ->where('asset_stage', Asset::STAGE_NEW_STOCK)
            ->where(function ($query) use ($selectedAssetIds) {
                $query->where('asset_status', 'available_for_sale');

                if ($selectedAssetIds->isNotEmpty()) {
                    $query->orWhereIn('id', $selectedAssetIds->all());
                }
            })
            ->orderBy('serial_number')
            ->get();
    }

    private function validateSaleAssetLink(?Sale $sale, mixed $assetId): ?Asset
    {
        $resolvedAssetId = (int) $assetId;

        if (!$sale || $resolvedAssetId <= 0) {
            return null;
        }

        if ($sale->asset_id && (int) $sale->asset_id !== $resolvedAssetId) {
            throw ValidationException::withMessages([
                'sale_asset_id' => 'This sale already has a linked asset. Change it from the Sales screen if needed.',
            ]);
        }

        if ((int) $sale->quantity !== 1) {
            throw ValidationException::withMessages([
                'sale_asset_id' => 'Serialized asset linking from delivery is supported only when sale quantity is 1.',
            ]);
        }

        $asset = Asset::query()
            ->where('organization_id', $this->orgId())
            ->findOrFail($resolvedAssetId);

        if ((int) $asset->product_id !== (int) $sale->product_id) {
            throw ValidationException::withMessages([
                'sale_asset_id' => 'Selected asset does not belong to this sale product.',
            ]);
        }

        if ($asset->asset_stage !== Asset::STAGE_NEW_STOCK) {
            throw ValidationException::withMessages([
                'sale_asset_id' => 'Only new stock assets can be linked here.',
            ]);
        }

        $isCurrentSaleAsset = (int) ($sale->asset_id ?? 0) === (int) $asset->id;

        if ($asset->asset_status !== 'available_for_sale' && !$isCurrentSaleAsset) {
            throw ValidationException::withMessages([
                'sale_asset_id' => 'Selected asset is not available for sale.',
            ]);
        }

        return $asset;
    }

    private function ensureRentalItemsExist(Rental $rental): void
    {
        $this->deliveryWorkflowService()->ensureRentalItemsExist($this->orgId(), $rental);
    }

    private function loadRentalProgressItems(Rental $rental)
    {
        return $this->deliveryWorkflowService()->loadRentalProgressItems($this->orgId(), $rental);
    }

    private function overallPendingDeliveryQuantity(Rental $rental): int
    {
        if (!$this->hasRentalItemsTable()) {
            return $rental->deliveryStatus() === 'completed' ? 0 : max((int) ($rental->quantity ?? 0), 0);
        }

        return (int) $this->loadRentalProgressItems($rental)->sum('pending_delivery_quantity');
    }

    private function overallPendingPickupQuantity(Rental $rental): int
    {
        if (!$this->hasRentalItemsTable()) {
            return $rental->status === 'returned' ? 0 : ($rental->deliveryStatus() === 'completed' ? max((int) ($rental->quantity ?? 0), 0) : 0);
        }

        return (int) $this->loadRentalProgressItems($rental)->sum('pending_pickup_quantity');
    }

    private function deliveredQuantityExists(Rental $rental): bool
    {
        if (!$this->hasRentalItemsTable()) {
            return $rental->deliveryStatus() === 'completed';
        }

        return $this->loadRentalProgressItems($rental)->sum('delivered_quantity_value') > 0;
    }

    private function resolveRentalProgressItem(Rental $rental, int $itemId): RentalItem
    {
        $items = $this->loadRentalProgressItems($rental);

        /** @var RentalItem|null $item */
        $item = $items->firstWhere('id', $itemId);

        if (!$item) {
            throw ValidationException::withMessages([
                'rental_item_id' => 'The selected rental item does not belong to this rental.',
            ]);
        }

        return $item;
    }

    private function nextPendingAssetIdsForDelivery(RentalItem $item, int $quantity): array
    {
        return $this->deliveryWorkflowService()->nextPendingAssetIdsForDelivery($item, $quantity);
    }

    private function nextDeliveredAssetIdsForReturn(RentalItem $item, int $quantity): array
    {
        return $this->deliveryWorkflowService()->nextDeliveredAssetIdsForReturn($item, $quantity);
    }

    private function releaseSpecificRentalAssets(Rental $rental, array $assetIds, ?string $returnedAt = null): void
    {
        $this->deliveryWorkflowService()->releaseSpecificRentalAssets($this->orgId(), $rental, $assetIds, $returnedAt);
    }

    private function restoreLegacyRentalItemStock(RentalItem $item, int $quantity): void
    {
        $this->deliveryWorkflowService()->restoreLegacyRentalItemStock($this->orgId(), $item, $quantity);
    }

    private function syncRentalProgressAssetStatuses(Rental $rental): void
    {
        $this->deliveryWorkflowService()->syncRentalProgressAssetStatuses($this->orgId(), $rental);
    }

    private function orgId(): int
    {
        return (int) auth()->user()->organization_id;
    }

    private function deliveryProofAcknowledgement(string $workflowStage): string
    {
        return DeliveryProof::acknowledgementFor($workflowStage);
    }

    private function deliveryProofConfig(): array
    {
        return [
            'max_kb' => $this->deliveryProofService()->maxKilobytes(),
            'target_kb' => $this->deliveryProofService()->targetKilobytes(),
            'max_dimension' => (int) config('proof.image_max_dimension', 1024),
        ];
    }

    private function redirectToWorkflowChecklist(Delivery $delivery, string $message)
    {
        return redirect()
            ->route('deliveries.show', $delivery)
            ->with('error', $message);
    }

    private function ensureProofWorkflowRequest(Request $request, Delivery $delivery, string $action)
    {
        if ($request->boolean('workflow_capture_form')) {
            return null;
        }

        $verb = $action === 'start' ? 'capture start location' : 'capture required proof and location';

        return $this->redirectToWorkflowChecklist(
            $delivery,
            'Open the delivery task detail page to ' . $verb . ' before continuing.'
        );
    }

    private function startWorkflowValidationRules(): array
    {
        return [
            'workflow_capture_form' => ['required', 'accepted'],
            'location_latitude' => ['nullable', 'numeric', 'between:-90,90'],
            'location_longitude' => ['nullable', 'numeric', 'between:-180,180'],
            'location_accuracy' => ['nullable', 'numeric', 'min:0'],
            'location_captured_at' => ['nullable', 'date'],
            'location_missing_reason' => ['nullable', 'string', 'max:500'],
        ];
    }

    private function completionWorkflowValidationRules(Delivery $delivery): array
    {
        $maxKb = $this->deliveryProofService()->maxKilobytes();
        $commonImageRule = ['file', 'image', 'mimes:jpg,jpeg,png,webp', 'max:' . $maxKb];

        $rules = [
            'workflow_capture_form' => ['required', 'accepted'],
            'location_latitude' => ['nullable', 'numeric', 'between:-90,90'],
            'location_longitude' => ['nullable', 'numeric', 'between:-180,180'],
            'location_accuracy' => ['nullable', 'numeric', 'min:0'],
            'location_captured_at' => ['nullable', 'date'],
            'location_missing_reason' => ['nullable', 'string', 'max:500'],
            'signature_data' => ['required', 'string'],
            'proof_notes' => ['nullable', 'string', 'max:1000'],
        ];

        if ($delivery->type === 'delivery') {
            $rules['delivery_device_photos'] = ['required', 'array', 'min:1'];
            $rules['delivery_device_photos.*'] = $commonImageRule;
            $rules['premises_photo'] = array_merge(['required'], $commonImageRule);
            $rules['pickup_device_photos'] = ['prohibited'];
            $rules['damage_reported'] = ['prohibited'];
            $rules['damage_notes'] = ['prohibited'];
            $rules['missing_accessories_notes'] = ['prohibited'];
            $rules['damage_photos'] = ['prohibited'];
            $rules['damage_photos.*'] = ['prohibited'];
        } else {
            $rules['pickup_device_photos'] = ['required', 'array', 'min:1'];
            $rules['pickup_device_photos.*'] = $commonImageRule;
            $rules['damage_reported'] = ['nullable', 'boolean'];
            $rules['damage_notes'] = ['nullable', 'string', 'max:1000'];
            $rules['missing_accessories_notes'] = ['nullable', 'string', 'max:1000'];
            $rules['damage_photos'] = ['nullable', 'array'];
            $rules['damage_photos.*'] = $commonImageRule;
            $rules['delivery_device_photos'] = ['prohibited'];
            $rules['delivery_device_photos.*'] = ['prohibited'];
            $rules['premises_photo'] = ['prohibited'];
        }

        return $rules;
    }

    private function validateStartWorkflowRequest(Request $request): array
    {
        $validator = Validator::make($request->all(), $this->startWorkflowValidationRules());
        $validator->after(function ($validator) {
            $this->appendLocationCaptureErrors($validator, $validator->getData());
        });

        return $validator->validate();
    }

    private function validateCompletionWorkflowRequest(Request $request, Delivery $delivery): array
    {
        $validator = Validator::make($request->all(), $this->completionWorkflowValidationRules($delivery));
        $validator->after(function ($validator) use ($delivery) {
            $data = $validator->getData();
            $this->appendLocationCaptureErrors($validator, $data);

            if ($delivery->type === 'pickup') {
                $this->appendPickupDamageProofErrors($validator, $data);
            }
        });

        return $validator->validate();
    }

    private function appendLocationCaptureErrors($validator, array $validated): void
    {
        $latitude = $validated['location_latitude'] ?? null;
        $longitude = $validated['location_longitude'] ?? null;
        $missingReason = trim((string) ($validated['location_missing_reason'] ?? ''));

        $hasCoordinates = $latitude !== null && $longitude !== null && $latitude !== '' && $longitude !== '';

        if ($hasCoordinates && $missingReason !== '') {
            return;
        }

        if ($hasCoordinates) {
            return;
        }

        if ($missingReason !== '') {
            return;
        }

        $validator->errors()->add('location_missing_reason', 'Capture the current location or enter a reason why location could not be captured.');
    }

    private function appendPickupDamageProofErrors($validator, array $validated): void
    {
        $damageReported = filter_var($validated['damage_reported'] ?? false, FILTER_VALIDATE_BOOLEAN);

        if (! $damageReported) {
            return;
        }

        $damageNotes = trim((string) ($validated['damage_notes'] ?? ''));
        $damagePhotos = collect($validated['damage_photos'] ?? [])->filter()->values();

        $messages = [];

        if ($damageNotes === '') {
            $messages['damage_notes'] = 'Damage notes are required when damage is reported at pickup.';
        }

        if ($damagePhotos->isEmpty()) {
            $messages['damage_photos'] = 'At least one damage photo is required when damage is reported at pickup.';
        }

        foreach ($messages as $key => $message) {
            $validator->errors()->add($key, $message);
        }
    }

    private function storeDeliveryWorkflowLocation(Delivery $delivery, User $user, string $captureMoment, array $validated): void
    {
        $this->deliveryProofService()->storeLocationCapture(
            $delivery,
            $user,
            $delivery->type,
            $captureMoment,
            isset($validated['location_latitude']) ? (float) $validated['location_latitude'] : null,
            isset($validated['location_longitude']) ? (float) $validated['location_longitude'] : null,
            isset($validated['location_accuracy']) ? (float) $validated['location_accuracy'] : null,
            $validated['location_captured_at'] ?? null,
            trim((string) ($validated['location_missing_reason'] ?? '')) ?: null
        );
    }

    private function storeWorkflowCompletionProofs(Delivery $delivery, User $user, array $validated): void
    {
        $acknowledgementText = $this->deliveryProofAcknowledgement($delivery->type);
        $proofNotes = trim((string) ($validated['proof_notes'] ?? '')) ?: null;

        $this->storeDeliveryWorkflowLocation($delivery, $user, DeliveryProof::MOMENT_COMPLETE, $validated);

        if ($delivery->type === 'delivery') {
            $this->deliveryProofService()->storeUploadedFiles(
                $delivery,
                $user,
                DeliveryProof::STAGE_DELIVERY,
                DeliveryProof::MOMENT_COMPLETE,
                DeliveryProof::TYPE_DELIVERED_DEVICE,
                $validated['delivery_device_photos'] ?? [],
                $proofNotes
            );

            $premisesPhoto = $validated['premises_photo'] ?? null;

            if ($premisesPhoto) {
                $this->deliveryProofService()->storeUploadedFiles(
                    $delivery,
                    $user,
                    DeliveryProof::STAGE_DELIVERY,
                    DeliveryProof::MOMENT_COMPLETE,
                    DeliveryProof::TYPE_PREMISES,
                    [$premisesPhoto],
                    $proofNotes
                );
            }

            $signatureMeta = [
                'proof_notes' => $proofNotes,
            ];
        } else {
            $damageReported = filter_var($validated['damage_reported'] ?? false, FILTER_VALIDATE_BOOLEAN);
            $damageNotes = trim((string) ($validated['damage_notes'] ?? '')) ?: null;
            $missingAccessoriesNotes = trim((string) ($validated['missing_accessories_notes'] ?? '')) ?: null;

            $this->deliveryProofService()->storeUploadedFiles(
                $delivery,
                $user,
                DeliveryProof::STAGE_PICKUP,
                DeliveryProof::MOMENT_COMPLETE,
                DeliveryProof::TYPE_PICKED_UP_DEVICE,
                $validated['pickup_device_photos'] ?? [],
                $proofNotes
            );

            if ($damageReported) {
                $this->deliveryProofService()->storeUploadedFiles(
                    $delivery,
                    $user,
                    DeliveryProof::STAGE_PICKUP,
                    DeliveryProof::MOMENT_COMPLETE,
                    DeliveryProof::TYPE_DAMAGE,
                    $validated['damage_photos'] ?? [],
                    $damageNotes,
                    [
                        'missing_accessories_notes' => $missingAccessoriesNotes,
                    ]
                );
            }

            $signatureMeta = [
                'proof_notes' => $proofNotes,
                'damage_reported' => $damageReported,
                'damage_notes' => $damageNotes,
                'missing_accessories_notes' => $missingAccessoriesNotes,
            ];
        }

        $this->deliveryProofService()->storeSignature(
            $delivery,
            $user,
            $delivery->type,
            DeliveryProof::MOMENT_COMPLETE,
            (string) $validated['signature_data'],
            $acknowledgementText,
            $proofNotes,
            $signatureMeta
        );
    }

    private function applyDeliveryScope($query)
    {
        $user = auth()->user();

        if ($user && $user->hasScope('assigned', 'deliveries') && $this->hasAssignedUserColumn()) {
            $query->where('assigned_user_id', $user->id);
        }

        return $query;
    }

    private function scopedDelivery(Delivery $delivery, bool $enforceAssignedScope = true): Delivery
    {
        abort_if($delivery->organization_id !== $this->orgId(), 403);

        $user = auth()->user();

        if ($enforceAssignedScope && $user && $user->hasScope('assigned', 'deliveries') && $this->hasAssignedUserColumn()) {
            abort_if((int) $delivery->assigned_user_id !== (int) $user->id, 403);
        }

        return $delivery;
    }

    private function redirectAfterDeliveryMutation(Delivery $delivery, string $message)
    {
        if ($this->hasSaleColumn() && $delivery->sale_id) {
            return redirect()
                ->route('sales.show', $delivery->sale_id)
                ->with('success', $message);
        }

        if ($delivery->rental_id) {
            return redirect()
                ->route('rentals.show', $delivery->rental_id)
                ->with('success', $message);
        }

        return redirect('/deliveries')->with('success', $message);
    }

    private function existingOpenTaskForRental(Rental $rental, string $type, ?int $ignoreDeliveryId = null): ?Delivery
    {
        return Delivery::query()
            ->where('organization_id', $this->orgId())
            ->where('rental_id', $rental->id)
            ->where('type', $type)
            ->whereIn('status', ['pending', 'in_progress'])
            ->when($ignoreDeliveryId, fn ($query) => $query->where('id', '!=', $ignoreDeliveryId))
            ->latest('id')
            ->first();
    }

    private function deliveryDedupKey(Delivery $delivery): string
    {
        if ($delivery->sale_id) {
            return 'sale:' . $delivery->sale_id . ':' . $delivery->type;
        }

        return 'rental:' . ($delivery->rental_id ?? 'none') . ':' . $delivery->type;
    }

    private function dedupeDeliveryCollection($deliveries)
    {
        return $deliveries
            ->sortByDesc('id')
            ->unique(fn (Delivery $delivery) => $this->deliveryDedupKey($delivery))
            ->sort(function (Delivery $a, Delivery $b) {
                $statusRank = ['pending' => 0, 'in_progress' => 1, 'completed' => 2, 'cancelled' => 3];
                $aRank = $statusRank[$a->status] ?? 9;
                $bRank = $statusRank[$b->status] ?? 9;

                if ($aRank !== $bRank) {
                    return $aRank <=> $bRank;
                }

                if (($a->scheduled_at?->timestamp ?? PHP_INT_MAX) !== ($b->scheduled_at?->timestamp ?? PHP_INT_MAX)) {
                    return ($a->scheduled_at?->timestamp ?? PHP_INT_MAX) <=> ($b->scheduled_at?->timestamp ?? PHP_INT_MAX);
                }

                return $b->id <=> $a->id;
            })
            ->values();
    }

    private function pickupTaskNeedsAction(Delivery $delivery): bool
    {
        if ($delivery->type !== 'pickup') {
            return false;
        }

        if ($delivery->sale_id || !$delivery->rental) {
            return in_array($delivery->status, ['pending', 'in_progress'], true);
        }

        return $this->overallPendingPickupQuantity($delivery->rental) > 0;
    }

    private function cancelOlderDuplicateTasks(Delivery $delivery): void
    {
        $this->deliveryWorkflowService()->cancelOlderDuplicateTasks($this->orgId(), $delivery);
    }

    private function assignableStaffMembers()
    {
        return Staff::forOrganization($this->orgId())
            ->eligibleForAssignments()
            ->orderBy('name')
            ->get();
    }

    private function assignableStaffRule(): Exists
    {
        return Rule::exists('staff', 'id')->where(function ($query) {
            $query->where('organization_id', $this->orgId())
                ->where('status', 'active');

            if (Staff::hasAssignmentEnabledColumn()) {
                $query->where('is_assignment_enabled', true);
            }

            if (Staff::hasAssignmentRoleColumn()) {
                $query->whereIn('assignment_role', Staff::deliveryPickupAssignmentRoles());
            } else {
                $query->whereIn('role', Staff::deliveryPickupAssignmentRoles());
            }
        });
    }

    private function assignableUsers()
    {
        $allowedRoles = ['delivery', 'pickup'];
        $allowedRoleIds = collect();

        if (Schema::hasColumn('users', 'role_id')) {
            $allowedRoleIds = Role::query()
                ->whereIn('slug', $allowedRoles)
                ->pluck('id');
        }

        return User::query()
            ->with('assignedRole')
            ->where('organization_id', $this->orgId())
            ->when(Schema::hasColumn('users', 'is_active'), fn ($query) => $query->where('is_active', true))
            ->where(function ($query) use ($allowedRoles, $allowedRoleIds) {
                $query->whereIn('role', $allowedRoles);

                if ($allowedRoleIds->isNotEmpty()) {
                    $query->orWhereIn('role_id', $allowedRoleIds);
                }
            })
            ->orderBy('name')
            ->get();
    }

    private function assignableUserRule(): Exists
    {
        $allowedRoles = ['delivery', 'pickup'];
        $allowedRoleIds = collect();

        if (Schema::hasColumn('users', 'role_id')) {
            $allowedRoleIds = Role::query()
                ->whereIn('slug', $allowedRoles)
                ->pluck('id');
        }

        return Rule::exists('users', 'id')->where(function ($query) {
            $allowedRoles = ['delivery', 'pickup'];
            $allowedRoleIds = collect();

            if (Schema::hasColumn('users', 'role_id')) {
                $allowedRoleIds = Role::query()
                    ->whereIn('slug', $allowedRoles)
                    ->pluck('id');
            }

            $query->where('organization_id', $this->orgId())
                ->when(Schema::hasColumn('users', 'is_active'), fn ($innerQuery) => $innerQuery->where('is_active', true))
                ->where(function ($innerQuery) use ($allowedRoles, $allowedRoleIds) {
                    $innerQuery->whereIn('role', $allowedRoles);

                    if ($allowedRoleIds->isNotEmpty()) {
                        $innerQuery->orWhereIn('role_id', $allowedRoleIds);
                    }
                });
        });
    }

    private function syncAssignedAssetStatuses(Delivery $delivery): void
    {
        $this->deliveryWorkflowService()->syncAssignedAssetStatuses($this->orgId(), $delivery, $this->hasSaleColumn());
    }

    private function releaseRentalAssetsForReturn(Rental $rental, ?string $returnedAt = null): void
    {
        $this->deliveryWorkflowService()->releaseRentalAssetsForReturn($this->orgId(), $rental, $returnedAt);
    }

    private function finalizePickupCompletionForRental(Delivery $delivery, Rental $rental, ?string $returnedAt = null): void
    {
        $this->deliveryWorkflowService()->finalizePickupCompletionForRental($this->orgId(), $rental, $returnedAt);
    }

    public function index(Request $request)
    {
        $this->authorize('viewAny', Delivery::class);

        $legacyBoard = strtolower((string) $request->query('board', ''));
        $legacyBoardDefaults = [
            'pending_delivery' => ['tab' => 'deliveries', 'task_type' => 'delivery', 'workflow' => 'pending_delivery'],
            'scheduled_delivery' => ['tab' => 'deliveries', 'task_type' => 'delivery', 'workflow' => 'scheduled_delivery'],
            'out_delivery' => ['tab' => 'in_progress', 'task_type' => 'delivery', 'workflow' => 'out_delivery'],
            'overdue_delivery' => ['tab' => 'overdue', 'task_type' => 'delivery', 'workflow' => 'overdue_delivery'],
            'completed_delivery' => ['tab' => 'completed', 'task_type' => 'delivery', 'workflow' => 'completed_delivery'],
            'pending_pickup' => ['tab' => 'pickups', 'task_type' => 'pickup', 'workflow' => 'pending_pickup'],
            'scheduled_pickup' => ['tab' => 'pickups', 'task_type' => 'pickup', 'workflow' => 'scheduled_pickup'],
            'out_pickup' => ['tab' => 'in_progress', 'task_type' => 'pickup', 'workflow' => 'out_pickup'],
            'overdue_pickup' => ['tab' => 'overdue', 'task_type' => 'pickup', 'workflow' => 'overdue_pickup'],
            'completed_pickup' => ['tab' => 'completed', 'task_type' => 'pickup', 'workflow' => 'completed_pickup'],
            'delivery_workload' => ['tab' => 'deliveries', 'task_type' => 'delivery', 'workflow' => 'delivery_workload'],
            'pickup_workload' => ['tab' => 'pickups', 'task_type' => 'pickup', 'workflow' => 'pickup_workload'],
            'live_tasks' => ['tab' => 'all', 'workflow' => 'live'],
            'completed_today' => ['tab' => 'completed', 'status' => 'completed', 'workflow' => 'completed_today'],
        ];

        $legacyDefault = $legacyBoardDefaults[$legacyBoard] ?? [];

        $tab = strtolower((string) $request->query('tab', $legacyDefault['tab'] ?? 'all'));
        $search = trim((string) $request->query('search', ''));
        $selectedDate = trim((string) $request->query('date', ''));
        $taskType = strtolower((string) $request->query('task_type', $legacyDefault['task_type'] ?? ''));
        $staffFilter = trim((string) $request->query('staff', ''));
        $areaFilter = trim((string) $request->query('area', ''));
        $statusFilter = strtolower((string) $request->query('status', $legacyDefault['status'] ?? ''));
        $workflowFilter = strtolower((string) $request->query('workflow', $legacyDefault['workflow'] ?? ''));
        $ownershipFilter = strtolower((string) $request->query('ownership', 'all'));

        if (!in_array($ownershipFilter, ['all', 'my'], true)) {
            $ownershipFilter = 'all';
        }

        $baseLoad = [
            'rental.product',
            'rental.customer',
            'rental.dispatchWarehouse',
            'sale.product',
            'sale.customer',
            'sale.asset.warehouse',
            'assignedUser',
            'assignedStaff',
        ];

        if ($this->hasRentalItemsTable()) {
            $baseLoad[] = 'rental.rentalItems.product';
        }

        if ($this->hasRentalAssetsTable()) {
            $baseLoad[] = 'rental.activeRentalAssets.asset.warehouse';
        }

        if ($this->hasRentalSaleItemsTable()) {
            $baseLoad[] = 'rental.saleItems.product';
            $baseLoad[] = 'rental.saleItems.asset.warehouse';
        }

        $summaryBaseQuery = Delivery::query()->where('organization_id', $this->orgId());
        $baseQuery = clone $summaryBaseQuery;

        if ($ownershipFilter === 'my') {
            $baseQuery = $this->applyDeliveryScope($baseQuery);
        }

        $applySearchFilter = function ($query) use ($search) {
            return $query->where(function ($taskQuery) use ($search) {
                $taskQuery->whereHas('rental', function ($rentalQuery) use ($search) {
                    $rentalQuery->where(function ($rentalInnerQuery) use ($search) {
                        $rentalInnerQuery
                            ->where('customer_name', 'like', "%{$search}%")
                            ->orWhere('phone', 'like', "%{$search}%")
                            ->orWhereHas('customer', function ($customerQuery) use ($search) {
                                $customerQuery
                                    ->where('name', 'like', "%{$search}%")
                                    ->orWhere('phone', 'like', "%{$search}%")
                                    ->orWhere('email', 'like', "%{$search}%");

                                if (Schema::hasColumn('customers', 'whatsapp_number')) {
                                    $customerQuery->orWhere('whatsapp_number', 'like', "%{$search}%");
                                }

                                if (Schema::hasColumn('customers', 'contact_name')) {
                                    $customerQuery->orWhere('contact_name', 'like', "%{$search}%");
                                }
                            });
                    });
                })->orWhereHas('sale', function ($saleQuery) use ($search) {
                    $saleQuery->where(function ($saleInnerQuery) use ($search) {
                        $saleInnerQuery
                            ->where('id', 'like', "%{$search}%")
                            ->orWhereHas('customer', function ($customerQuery) use ($search) {
                                $customerQuery
                                    ->where('name', 'like', "%{$search}%")
                                    ->orWhere('phone', 'like', "%{$search}%")
                                    ->orWhere('email', 'like', "%{$search}%");

                                if (Schema::hasColumn('customers', 'whatsapp_number')) {
                                    $customerQuery->orWhere('whatsapp_number', 'like', "%{$search}%");
                                }

                                if (Schema::hasColumn('customers', 'contact_name')) {
                                    $customerQuery->orWhere('contact_name', 'like', "%{$search}%");
                                }
                            })
                            ->orWhereHas('product', function ($productQuery) use ($search) {
                                $productQuery->where('name', 'like', "%{$search}%");
                            });
                    });
                });
            });
        };

        $applyUnassignedFilter = function ($query) {
            return $query->where(function ($innerQuery) {
                if ($this->hasAssignedUserColumn()) {
                    $innerQuery->whereNull('assigned_user_id');
                }

                if ($this->hasAssignedStaffColumn()) {
                    $innerQuery->whereNull('assigned_staff_id');
                }

                if ($this->hasAssignmentTypeColumn()) {
                    $innerQuery->where(function ($assignmentQuery) {
                        $assignmentQuery->whereNull('assignment_type')
                            ->orWhere('assignment_type', 'delivery_team');
                    });
                }
            });
        };

        $applyWarehouseAreaFilter = function ($query, int $warehouseId) {
            return $query->where(function ($innerQuery) use ($warehouseId) {
                $innerQuery->whereHas('rental', function ($rentalQuery) use ($warehouseId) {
                    $rentalQuery->where('dispatch_warehouse_id', $warehouseId);
                })->orWhereHas('sale.asset', function ($assetQuery) use ($warehouseId) {
                    $assetQuery->where('warehouse_id', $warehouseId);
                });
            });
        };

        $applyCityAreaFilter = function ($query, string $city) {
            return $query->where(function ($innerQuery) use ($city) {
                $innerQuery->whereHas('rental.customer', fn ($customerQuery) => $customerQuery->where('city', $city))
                    ->orWhereHas('sale.customer', fn ($customerQuery) => $customerQuery->where('city', $city));
            });
        };

        if ($search !== '') {
            $applySearchFilter($baseQuery);
            $applySearchFilter($summaryBaseQuery);
        }

        if ($selectedDate !== '') {
            $baseQuery->whereDate('scheduled_at', $selectedDate);
            $summaryBaseQuery->whereDate('scheduled_at', $selectedDate);
        }

        if ($staffFilter !== '') {
            if (str_starts_with($staffFilter, 'user:') && $this->hasAssignedUserColumn()) {
                $baseQuery->where('assigned_user_id', (int) substr($staffFilter, 5));
                $summaryBaseQuery->where('assigned_user_id', (int) substr($staffFilter, 5));
            } elseif (str_starts_with($staffFilter, 'staff:') && $this->hasAssignedStaffColumn()) {
                $baseQuery->where('assigned_staff_id', (int) substr($staffFilter, 6));
                $summaryBaseQuery->where('assigned_staff_id', (int) substr($staffFilter, 6));
            } elseif ($staffFilter === 'third_party' && $this->hasAssignmentTypeColumn()) {
                $baseQuery->where('assignment_type', 'third_party');
                $summaryBaseQuery->where('assignment_type', 'third_party');
            } elseif ($staffFilter === 'unassigned') {
                $applyUnassignedFilter($baseQuery);
                $applyUnassignedFilter($summaryBaseQuery);
            }
        }

        if ($areaFilter !== '') {
            if (str_starts_with($areaFilter, 'warehouse:')) {
                $warehouseId = (int) substr($areaFilter, 10);
                $applyWarehouseAreaFilter($baseQuery, $warehouseId);
                $applyWarehouseAreaFilter($summaryBaseQuery, $warehouseId);
            } elseif (str_starts_with($areaFilter, 'city:')) {
                $city = substr($areaFilter, 5);
                $applyCityAreaFilter($baseQuery, $city);
                $applyCityAreaFilter($summaryBaseQuery, $city);
            }
        }

        $orderedMinimalDeliveryQuery = function ($query) {
            return $query
                ->select([
                    'id',
                    'rental_id',
                    'sale_id',
                    'type',
                    'status',
                    'scheduled_at',
                    'completed_at',
                    'updated_at',
                    'assigned_user_id',
                    'assigned_staff_id',
                    'third_party_name',
                    'assignment_type',
                    'created_at',
                ])
                ->orderByRaw("CASE WHEN status = 'pending' THEN 0 WHEN status = 'in_progress' THEN 1 ELSE 2 END")
                ->orderByRaw("CASE WHEN scheduled_at IS NULL THEN 1 ELSE 0 END")
                ->orderBy('scheduled_at')
                ->orderByDesc('created_at');
        };

        $hydrateDeliveries = function (Collection $deliveryIds) use ($baseLoad): Collection {
            if ($deliveryIds->isEmpty()) {
                return collect();
            }

            $deliveriesQuery = Delivery::with($baseLoad)
                ->where('organization_id', $this->orgId())
                ->whereIn('id', $deliveryIds->all());

            if ($this->hasDeliveryProofsTable()) {
                $deliveriesQuery->withCount('proofs');
            }

            $deliveries = $deliveriesQuery
                ->get()
                ->keyBy('id');

            return $deliveryIds
                ->map(fn ($deliveryId) => $deliveries->get((int) $deliveryId))
                ->filter()
                ->values();
        };

        $deliveriesQuery = clone $baseQuery;
        $summaryQuery = clone $summaryBaseQuery;

        if (in_array($taskType, ['delivery', 'pickup'], true)) {
            $deliveriesQuery->where('type', $taskType);
            $summaryQuery->where('type', $taskType);
        }

        if (in_array($statusFilter, ['pending', 'in_progress', 'completed', 'cancelled'], true)) {
            $deliveriesQuery->where('status', $statusFilter);
            $summaryQuery->where('status', $statusFilter);
        } else {
            $deliveriesQuery->where('status', '!=', 'cancelled');
            $summaryQuery->where('status', '!=', 'cancelled');
        }

        $today = now()->toDateString();

        switch ($tab) {
            case 'deliveries':
                $deliveriesQuery->where('type', 'delivery');
                $summaryQuery->where('type', 'delivery');
                break;
            case 'pickups':
                $deliveriesQuery->where('type', 'pickup');
                $summaryQuery->where('type', 'pickup');
                break;
            case 'in_progress':
                $deliveriesQuery->where('status', 'in_progress');
                $summaryQuery->where('status', 'in_progress');
                break;
            case 'completed':
                $deliveriesQuery->where('status', 'completed');
                $summaryQuery->where('status', 'completed');
                break;
            case 'today':
                $deliveriesQuery->whereDate('scheduled_at', $today);
                $summaryQuery->whereDate('scheduled_at', $today);
                break;
            case 'overdue':
                $deliveriesQuery
                    ->whereIn('status', ['pending', 'in_progress'])
                    ->whereDate('scheduled_at', '<', $today);
                $summaryQuery
                    ->whereIn('status', ['pending', 'in_progress'])
                    ->whereDate('scheduled_at', '<', $today);
                break;
            default:
                $tab = 'all';
                break;
        }

        $dedupedTaskIds = $this->dedupeDeliveryCollection(
            $orderedMinimalDeliveryQuery(clone $deliveriesQuery)->get()
        )
            ->pluck('id')
            ->map(fn ($id) => (int) $id)
            ->values();

        if ($this->logisticsMetrics()->isSupportedWorkflow($workflowFilter)) {
            $dedupedTaskIds = $this->logisticsMetrics()
                ->applyWorkflowFilter($hydrateDeliveries($dedupedTaskIds), $workflowFilter, now()->startOfDay())
                ->pluck('id')
                ->map(fn ($id) => (int) $id)
                ->values();
        }

        $perPage = 20;
        $currentPage = Paginator::resolveCurrentPage('page');
        $pageDeliveryIds = $dedupedTaskIds->forPage($currentPage, $perPage)->values();
        $taskCollection = $hydrateDeliveries($pageDeliveryIds);
        $taskResultsCount = $dedupedTaskIds->count();

        $tasks = new LengthAwarePaginator(
            $taskCollection,
            $taskResultsCount,
            $perPage,
            $currentPage,
            [
                'path' => $request->url(),
                'query' => $request->query(),
                'pageName' => 'page',
            ]
        );

        $summaryTaskIds = $this->dedupeDeliveryCollection(
            $orderedMinimalDeliveryQuery(clone $summaryQuery)->get()
        )
            ->pluck('id')
            ->map(fn ($id) => (int) $id)
            ->values();

        if ($this->logisticsMetrics()->isSupportedWorkflow($workflowFilter)) {
            $summaryTaskIds = $this->logisticsMetrics()
                ->applyWorkflowFilter($hydrateDeliveries($summaryTaskIds), $workflowFilter, now()->startOfDay())
                ->pluck('id')
                ->map(fn ($id) => (int) $id)
                ->values();
        }

        $summaryDeliveries = $hydrateDeliveries($summaryTaskIds);
        $logisticsSummary = $this->logisticsMetrics()->summary($summaryDeliveries, now()->startOfDay());
        $totalTasksCount = (int) ($logisticsSummary['totalTasksCount'] ?? 0);
        $deliveryTasksCount = (int) ($logisticsSummary['deliveryTasksCount'] ?? 0);
        $pickupTasksCount = (int) ($logisticsSummary['pickupTasksCount'] ?? 0);
        $overdueTasksCount = (int) ($logisticsSummary['overdueTasksCount'] ?? 0);
        $completedTodayCount = (int) ($logisticsSummary['completedTodayCount'] ?? 0);
        $pendingDeliveryCount = (int) ($logisticsSummary['pendingDeliveryCount'] ?? 0);
        $scheduledDeliveryCount = (int) ($logisticsSummary['scheduledDeliveryCount'] ?? 0);
        $outForDeliveryCount = (int) ($logisticsSummary['outForDeliveryCount'] ?? 0);
        $overdueDeliveryCount = (int) ($logisticsSummary['overdueDeliveryCount'] ?? 0);
        $completedDeliveryCount = (int) ($logisticsSummary['completedDeliveryCount'] ?? 0);
        $deliveredTodayCount = (int) ($logisticsSummary['deliveredTodayCount'] ?? 0);
        $pendingPickupCount = (int) ($logisticsSummary['pendingPickupCount'] ?? 0);
        $scheduledPickupCount = (int) ($logisticsSummary['scheduledPickupCount'] ?? 0);
        $outForPickupCount = (int) ($logisticsSummary['outForPickupCount'] ?? 0);
        $overduePickupCount = (int) ($logisticsSummary['overduePickupCount'] ?? 0);
        $completedPickupCount = (int) ($logisticsSummary['completedPickupCount'] ?? 0);
        $todayTaskCount = (int) ($logisticsSummary['todayTaskCount'] ?? 0);
        $todayDeliveryCount = (int) ($logisticsSummary['todayDeliveryCount'] ?? 0);
        $todayPickupCount = (int) ($logisticsSummary['todayPickupCount'] ?? 0);
        $pendingCollectionsCount = (int) ($logisticsSummary['pendingCollectionsCount'] ?? 0);

        $todayOverviewTaskIds = collect($logisticsSummary['todayTasks'] ?? collect())
            ->sortBy(fn (Delivery $delivery) => $delivery->scheduled_at?->timestamp ?? PHP_INT_MAX)
            ->take(5)
            ->pluck('id')
            ->map(fn ($id) => (int) $id)
            ->values();
        $todayOverviewTasks = $hydrateDeliveries($todayOverviewTaskIds);

        $overdueTaskIds = collect($logisticsSummary['overdueTasks'] ?? collect())
            ->sortBy(fn (Delivery $delivery) => $delivery->scheduled_at?->timestamp ?? PHP_INT_MAX)
            ->take(5)
            ->pluck('id')
            ->map(fn ($id) => (int) $id)
            ->values();
        $overdueTasks = $hydrateDeliveries($overdueTaskIds);

        $pendingCollectionIds = collect($logisticsSummary['pendingPickupTasks'] ?? collect())
            ->sortBy(fn (Delivery $delivery) => $delivery->scheduled_at?->timestamp ?? PHP_INT_MAX)
            ->take(5)
            ->pluck('id')
            ->map(fn ($id) => (int) $id)
            ->values();
        $pendingCollections = $hydrateDeliveries($pendingCollectionIds);

        $assignableUsers = $this->assignableUsers();
        $assignableStaffMembers = $this->assignableStaffMembers();
        $warehouseOptions = \App\Models\Warehouse::query()
            ->where('organization_id', $this->orgId())
            ->orderBy('name')
            ->get(['id', 'name']);
        $areaOptions = DB::table('customers')
            ->where('organization_id', $this->orgId())
            ->whereNotNull('city')
            ->where('city', '!=', '')
            ->distinct()
            ->orderBy('city')
            ->pluck('city');

        return view('deliveries.index', compact(
            'tab',
            'search',
            'selectedDate',
            'taskType',
            'staffFilter',
            'areaFilter',
            'statusFilter',
            'workflowFilter',
            'ownershipFilter',
            'tasks',
            'taskResultsCount',
            'totalTasksCount',
            'deliveryTasksCount',
            'pickupTasksCount',
            'overdueTasksCount',
            'completedTodayCount',
            'pendingDeliveryCount',
            'scheduledDeliveryCount',
            'outForDeliveryCount',
            'overdueDeliveryCount',
            'completedDeliveryCount',
            'deliveredTodayCount',
            'pendingPickupCount',
            'scheduledPickupCount',
            'outForPickupCount',
            'overduePickupCount',
            'completedPickupCount',
            'todayTaskCount',
            'todayDeliveryCount',
            'todayPickupCount',
            'pendingCollectionsCount',
            'todayOverviewTasks',
            'overdueTasks',
            'pendingCollections',
            'assignableUsers',
            'assignableStaffMembers',
            'warehouseOptions',
            'areaOptions'
        ));
    }

    public function create(Request $request)
    {
        $this->authorize('create', Delivery::class);

        $rentals = Rental::with(['product', 'dispatchWarehouse'])
            ->where('organization_id', $this->orgId())
            ->latest()
            ->get();
        $hasSaleSupport = $this->hasSaleColumn();
        $sales = $hasSaleSupport
            ? Sale::with(['customer', 'product', 'asset.warehouse'])
                ->where('organization_id', $this->orgId())
                ->when($this->hasAutoGeneratedRentalSaleColumn(), function ($query) {
                    $query->where(function ($saleQuery) {
                        $saleQuery->where('auto_generated_from_rental', false)
                            ->orWhereNull('auto_generated_from_rental');
                    });
                })
                ->latest('id')
                ->get()
            : collect();

        $selectedRentalId = $request->get('rental_id');
        $selectedSaleId = $request->get('sale_id');
        $selectedType = in_array($request->get('type'), ['delivery', 'pickup'], true)
            ? $request->get('type')
            : 'delivery';
        $selectedSale = $selectedSaleId
            ? $sales->firstWhere('id', (int) $selectedSaleId)
            : null;

        $assignableUsers = $this->assignableUsers();
        $assignableStaffMembers = $this->assignableStaffMembers();
        $saleAssets = $this->availableSaleAssets($selectedSale);

        return view('deliveries.create', compact('rentals', 'sales', 'selectedRentalId', 'selectedSaleId', 'selectedType', 'assignableUsers', 'assignableStaffMembers', 'hasSaleSupport', 'saleAssets'));
    }

    public function store(Request $request)
    {
        $this->authorize('create', Delivery::class);

        $validationRules = [
            'rental_id' => array_filter([
                $this->hasSaleColumn() ? 'nullable' : 'required',
                $this->hasSaleColumn() ? 'required_without:sale_id' : null,
                Rule::exists('rentals', 'id')->where(fn ($query) => $query->where('organization_id', $this->orgId())),
            ]),
            'sale_id' => $this->hasSaleColumn()
                ? [
                    'nullable',
                    'required_without:rental_id',
                    Rule::exists('sales', 'id')->where(fn ($query) => $query->where('organization_id', $this->orgId())),
                ]
                : ['prohibited'],
            'type' => 'required|in:delivery,pickup',
            'scheduled_at' => 'nullable|date',
            'status' => 'required|in:pending,in_progress,completed,cancelled',
            'notes' => 'nullable|string',
        ];

        if ($this->hasAssignmentTypeColumn()) {
            $validationRules['assignment_type'] = 'required|in:delivery_team,vendor,third_party';
        }

        if ($this->hasAssignedUserColumn()) {
            $validationRules['assigned_user_id'] = ['nullable', $this->assignableUserRule()];
        }

        if ($this->hasThirdPartyNameColumn()) {
            $validationRules['third_party_name'] = 'nullable|string|max:255';
        }

        if ($this->hasThirdPartyContactColumn()) {
            $validationRules['third_party_contact'] = 'nullable|string|max:255';
        }

        if ($this->hasThirdPartyPhoneColumn()) {
            $validationRules['third_party_phone'] = PhoneNumber::validationRules();
            $validationRules['third_party_phone_country_code'] = 'nullable|string|max:8';
        }

        if ($this->hasAssignedStaffColumn()) {
            $validationRules['assigned_staff_id'] = ['nullable', $this->assignableStaffRule()];
        }

        if ($this->hasSaleColumn()) {
            $validationRules['sale_asset_id'] = [
                'nullable',
                Rule::exists('assets', 'id')->where(fn ($query) => $query->where('organization_id', $this->orgId())),
            ];
        }

        $request->validate($validationRules);

        if ($this->hasSaleColumn() && $request->filled('rental_id') && $request->filled('sale_id')) {
            return back()
                ->withErrors(['sale_id' => 'Choose either a rental or a sale order, not both.'])
                ->withInput();
        }

        $rental = $request->filled('rental_id')
            ? Rental::where('organization_id', $this->orgId())->findOrFail($request->rental_id)
            : null;
        $sale = $request->filled('sale_id')
            ? Sale::where('organization_id', $this->orgId())->findOrFail($request->sale_id)
            : null;

        if ($sale && $this->hasAutoGeneratedRentalSaleColumn() && (bool) ($sale->auto_generated_from_rental ?? false)) {
            return back()->withErrors([
                'sale_id' => 'This sale is managed from the linked rental. Assign delivery from the rental workflow instead.',
            ])->withInput();
        }

        if ($sale && $request->type !== 'delivery') {
            return back()->withErrors(['type' => 'Sales orders can only be assigned for delivery.'])->withInput();
        }

        if ($rental && $request->type === 'pickup' && !$this->deliveredQuantityExists($rental)) {
            return back()->withErrors([
                'type' => 'Pickup can only be assigned after at least one rental item has been delivered.',
            ])->withInput();
        }

        if ($rental && $request->type === 'pickup' && $this->overallPendingPickupQuantity($rental) <= 0) {
            return back()->withErrors([
                'type' => 'All delivered items are already picked up for this rental.',
            ])->withInput();
        }

        if ($rental) {
            $existingTask = $this->existingOpenTaskForRental($rental, $request->type);

            if ($existingTask) {
                return back()->withErrors([
                    'type' => ucfirst($request->type) . ' is already assigned for this rental. Open the existing task instead of creating another one.',
                ])->withInput();
            }
        }

        $linkedSaleAsset = $this->validateSaleAssetLink($sale, $request->input('sale_asset_id'));

        $data = [
            'organization_id' => $this->orgId(),
            'rental_id' => $rental?->id,
            'type' => $request->type,
            'scheduled_at' => $request->scheduled_at,
            'status' => $request->status,
            'notes' => $request->notes,
        ];

        if ($this->hasSaleColumn()) {
            $data['sale_id'] = $sale?->id;
        }

        $assignmentType = $request->input('assignment_type', 'delivery_team');

        if ($this->hasAssignmentTypeColumn()) {
            $data['assignment_type'] = $assignmentType;
        }

        if ($this->hasAssignedUserColumn()) {
            $data['assigned_user_id'] = $assignmentType === 'delivery_team' ? $request->assigned_user_id : null;
        }

        if ($this->hasThirdPartyNameColumn()) {
            $data['third_party_name'] = $assignmentType === 'third_party' ? $request->third_party_name : null;
        }

        if ($this->hasThirdPartyContactColumn()) {
            $data['third_party_contact'] = $assignmentType === 'third_party' ? $request->third_party_contact : null;
        }

        if ($this->hasThirdPartyPhoneColumn()) {
            $data['third_party_phone'] = $assignmentType === 'third_party'
                ? PhoneNumber::normalize($request->third_party_phone, $request->input('third_party_phone_country_code'))
                : null;
        }

        if ($this->hasAssignedStaffColumn()) {
            $data['assigned_staff_id'] = $assignmentType === 'vendor' ? $request->assigned_staff_id : null;
        }

        if ($request->status === 'completed') {
            $data['completed_at'] = now();
        }

        if ($sale && $linkedSaleAsset && !$sale->asset_id) {
            $saleUpdates = ['asset_id' => $linkedSaleAsset->id];

            if (Schema::hasColumn('sales', 'warehouse_id')) {
                $saleUpdates['warehouse_id'] = $linkedSaleAsset->warehouse_id;
            }

            $sale->update($saleUpdates);
        }

        $delivery = Delivery::create($data);

        if ($delivery->type === 'pickup' && $delivery->status === 'completed' && $rental) {
            $this->finalizePickupCompletionForRental($delivery, $rental, optional($delivery->completed_at)->toDateTimeString());
        }

        $this->syncAssignedAssetStatuses($delivery);

        ActivityLogger::log('delivery.assigned', $delivery, [
            'type' => $delivery->type,
            'status' => $delivery->status,
            'assignment_type' => $delivery->assignment_type ?? null,
            'assigned_user_id' => $delivery->assigned_user_id ?? null,
            'assigned_staff_id' => $delivery->assigned_staff_id ?? null,
            'scheduled_at' => optional($delivery->scheduled_at)->toDateTimeString(),
        ], 'Delivery or pickup assignment created.');

        return $this->redirectAfterDeliveryMutation($delivery, 'Delivery/Pickup created successfully.');
    }

    public function show(Delivery $delivery)
    {
        $delivery = $this->scopedDelivery($delivery, false);
        $this->authorize('view', $delivery);

        if ($delivery->type === 'pickup' && $delivery->status === 'completed' && $delivery->rental_id) {
            $rental = Rental::query()
                ->where('organization_id', $this->orgId())
                ->find($delivery->rental_id);

            if ($rental && $this->overallPendingPickupQuantity($rental) > 0) {
                $this->finalizePickupCompletionForRental($delivery, $rental, optional($delivery->completed_at)->toDateTimeString());
            }
        }

        $load = [
            'rental.product',
            'rental.deliveryRecord',
            'rental.dispatchWarehouse',
            'rental.pickupRecord',
            'sale.product',
            'sale.customer',
            'sale.asset.warehouse',
            'assignedUser',
            'assignedStaff',
        ];

        if ($this->hasRentalAssetsTable()) {
            $load[] = 'rental.activeRentalAssets.asset';
        }

        if ($this->hasRentalSaleItemsTable()) {
            $load[] = 'rental.saleItems.product';
            $load[] = 'rental.saleItems.asset.warehouse';
        }

        if ($this->hasRentalItemsTable()) {
            $load[] = 'rental.rentalItems.product';
        }

        if ($this->hasRentalItemsTable()) {
            $load[] = 'rental.rentalItems.product';
        }

        $delivery->load($load);

        if (!$this->hasRentalAssetsTable() && $delivery->relationLoaded('rental') && $delivery->rental) {
            $delivery->rental->setRelation('activeRentalAssets', collect());
        }

        if (!$this->hasRentalSaleItemsTable() && $delivery->relationLoaded('rental') && $delivery->rental) {
            $delivery->rental->setRelation('saleItems', collect());
        }

        if (!$this->hasRentalItemsTable() && $delivery->relationLoaded('rental') && $delivery->rental) {
            $delivery->rental->setRelation('rentalItems', collect());
        }

        $activityLogs = ActivityLogger::recentFor($delivery);
        $deliveryProofs = $this->hasDeliveryProofsTable()
            ? $delivery->proofs()->with('creator')->latest('captured_at')->latest('id')->get()
            : collect();
        $proofConfig = $this->deliveryProofConfig();

        return view('deliveries.show', compact('delivery', 'activityLogs', 'deliveryProofs', 'proofConfig'));
    }

    public function viewProof(Delivery $delivery, DeliveryProof $proof)
    {
        $delivery = $this->scopedDelivery($delivery, false);
        $this->authorize('view', $delivery);

        abort_if($proof->organization_id !== $this->orgId(), 403);
        abort_if((int) $proof->delivery_id !== (int) $delivery->id, 404);

        return $this->deliveryProofService()->streamInline($proof);
    }

    public function edit(Delivery $delivery)
    {
        $delivery = $this->scopedDelivery($delivery);
        $this->authorize('update', $delivery);

        $rentals = Rental::with(['product', 'dispatchWarehouse'])
            ->where('organization_id', $this->orgId())
            ->latest()
            ->get();
        $hasSaleSupport = $this->hasSaleColumn();
        $sales = $hasSaleSupport
            ? Sale::with(['customer', 'product', 'asset.warehouse'])
                ->where('organization_id', $this->orgId())
                ->when($this->hasAutoGeneratedRentalSaleColumn(), function ($query) {
                    $query->where(function ($saleQuery) {
                        $saleQuery->where('auto_generated_from_rental', false)
                            ->orWhereNull('auto_generated_from_rental');
                    });
                })
                ->latest('id')
                ->get()
            : collect();

        $assignableUsers = $this->assignableUsers();
        $assignableStaffMembers = $this->assignableStaffMembers();
        $selectedSale = $delivery->sale;
        $saleAssets = $this->availableSaleAssets($selectedSale);

        return view('deliveries.edit', compact('delivery', 'rentals', 'sales', 'assignableUsers', 'assignableStaffMembers', 'hasSaleSupport', 'saleAssets'));
    }

    public function update(Request $request, Delivery $delivery)
    {
        $delivery = $this->scopedDelivery($delivery);
        $this->authorize('update', $delivery);
        $wasCompleted = $delivery->status === 'completed';

        $validationRules = [
            'rental_id' => array_filter([
                $this->hasSaleColumn() ? 'nullable' : 'required',
                $this->hasSaleColumn() ? 'required_without:sale_id' : null,
                Rule::exists('rentals', 'id')->where(fn ($query) => $query->where('organization_id', $this->orgId())),
            ]),
            'sale_id' => $this->hasSaleColumn()
                ? [
                    'nullable',
                    'required_without:rental_id',
                    Rule::exists('sales', 'id')->where(fn ($query) => $query->where('organization_id', $this->orgId())),
                ]
                : ['prohibited'],
            'type' => 'required|in:delivery,pickup',
            'scheduled_at' => 'nullable|date',
            'status' => 'required|in:pending,in_progress,completed,cancelled',
            'notes' => 'nullable|string',
        ];

        if ($this->hasAssignmentTypeColumn()) {
            $validationRules['assignment_type'] = 'required|in:delivery_team,vendor,third_party';
        }

        if ($this->hasAssignedUserColumn()) {
            $validationRules['assigned_user_id'] = ['nullable', $this->assignableUserRule()];
        }

        if ($this->hasThirdPartyNameColumn()) {
            $validationRules['third_party_name'] = 'nullable|string|max:255';
        }

        if ($this->hasThirdPartyContactColumn()) {
            $validationRules['third_party_contact'] = 'nullable|string|max:255';
        }

        if ($this->hasThirdPartyPhoneColumn()) {
            $validationRules['third_party_phone'] = PhoneNumber::validationRules();
            $validationRules['third_party_phone_country_code'] = 'nullable|string|max:8';
        }

        if ($this->hasAssignedStaffColumn()) {
            $validationRules['assigned_staff_id'] = ['nullable', $this->assignableStaffRule()];
        }

        if ($this->hasSaleColumn()) {
            $validationRules['sale_asset_id'] = [
                'nullable',
                Rule::exists('assets', 'id')->where(fn ($query) => $query->where('organization_id', $this->orgId())),
            ];
        }

        $request->validate($validationRules);

        if ($this->hasSaleColumn() && $request->filled('rental_id') && $request->filled('sale_id')) {
            return back()
                ->withErrors(['sale_id' => 'Choose either a rental or a sale order, not both.'])
                ->withInput();
        }

        $rental = $request->filled('rental_id')
            ? Rental::where('organization_id', $this->orgId())->findOrFail($request->rental_id)
            : null;
        $sale = $request->filled('sale_id')
            ? Sale::where('organization_id', $this->orgId())->findOrFail($request->sale_id)
            : null;

        if ($sale && $this->hasAutoGeneratedRentalSaleColumn() && (bool) ($sale->auto_generated_from_rental ?? false)) {
            return back()->withErrors([
                'sale_id' => 'This sale is managed from the linked rental. Assign delivery from the rental workflow instead.',
            ])->withInput();
        }

        if ($sale && $request->type !== 'delivery') {
            return back()->withErrors(['type' => 'Sales orders can only be assigned for delivery.'])->withInput();
        }

        if ($rental && $request->type === 'pickup' && $rental->deliveryStatus() !== 'completed') {
            return back()->withErrors([
                'type' => 'Pickup can only be assigned after delivery is completed.',
            ])->withInput();
        }

        if ($rental) {
            $existingTask = $this->existingOpenTaskForRental($rental, $request->type, $delivery->id);

            if ($existingTask) {
                return back()->withErrors([
                    'type' => ucfirst($request->type) . ' is already assigned for this rental. Keep one open task per rental and workflow step.',
                ])->withInput();
            }
        }

        $linkedSaleAsset = $this->validateSaleAssetLink($sale, $request->input('sale_asset_id'));

        $data = [
            'rental_id' => $rental?->id,
            'type' => $request->type,
            'scheduled_at' => $request->scheduled_at,
            'status' => $request->status,
            'notes' => $request->notes,
        ];

        if ($this->hasSaleColumn()) {
            $data['sale_id'] = $sale?->id;
        }

        $assignmentType = $request->input('assignment_type', 'delivery_team');

        if ($this->hasAssignmentTypeColumn()) {
            $data['assignment_type'] = $assignmentType;
        }

        if ($this->hasAssignedUserColumn()) {
            $data['assigned_user_id'] = $assignmentType === 'delivery_team' ? $request->assigned_user_id : null;
        }

        if ($this->hasThirdPartyNameColumn()) {
            $data['third_party_name'] = $assignmentType === 'third_party' ? $request->third_party_name : null;
        }

        if ($this->hasThirdPartyContactColumn()) {
            $data['third_party_contact'] = $assignmentType === 'third_party' ? $request->third_party_contact : null;
        }

        if ($this->hasThirdPartyPhoneColumn()) {
            $data['third_party_phone'] = $assignmentType === 'third_party'
                ? PhoneNumber::normalize($request->third_party_phone, $request->input('third_party_phone_country_code'))
                : null;
        }

        if ($this->hasAssignedStaffColumn()) {
            $data['assigned_staff_id'] = $assignmentType === 'vendor' ? $request->assigned_staff_id : null;
        }

        if ($request->status === 'completed' && !$delivery->completed_at) {
            $data['completed_at'] = now();
        }

        if ($request->status !== 'completed') {
            $data['completed_at'] = null;
        }

        if ($sale && $linkedSaleAsset && !$sale->asset_id) {
            $saleUpdates = ['asset_id' => $linkedSaleAsset->id];

            if (Schema::hasColumn('sales', 'warehouse_id')) {
                $saleUpdates['warehouse_id'] = $linkedSaleAsset->warehouse_id;
            }

            $sale->update($saleUpdates);
        }

        $delivery->update($data);

        if ($delivery->type === 'pickup' && !$wasCompleted && $delivery->status === 'completed' && $rental) {
            $this->finalizePickupCompletionForRental($delivery, $rental, optional($delivery->completed_at)->toDateTimeString());
        }

        $this->syncAssignedAssetStatuses($delivery);

        ActivityLogger::log('delivery.updated', $delivery->refresh(), [
            'type' => $delivery->type,
            'status' => $delivery->status,
            'assignment_type' => $delivery->assignment_type ?? null,
            'assigned_user_id' => $delivery->assigned_user_id ?? null,
            'assigned_staff_id' => $delivery->assigned_staff_id ?? null,
            'scheduled_at' => optional($delivery->scheduled_at)->toDateTimeString(),
        ], 'Delivery or pickup assignment updated.');

        return $this->redirectAfterDeliveryMutation($delivery, 'Delivery/Pickup updated successfully.');
    }

    public function destroy(Delivery $delivery)
    {
        $delivery = $this->scopedDelivery($delivery);
        $this->authorize('delete', $delivery);

        $delivery->delete();

        return redirect()
            ->route('deliveries.index')
            ->with('success', 'Delivery/Pickup deleted successfully.');
    }

    public function recordPartialDelivery(Request $request, Delivery $delivery)
    {
        $delivery = $this->scopedDelivery($delivery);
        $this->authorize('update', $delivery);

        if ($delivery->type !== 'delivery' || !$delivery->rental_id) {
            return redirect()->back()->with('error', 'Partial delivery is available only for rental delivery tasks.');
        }

        if (in_array($delivery->status, ['completed', 'cancelled'], true)) {
            return redirect()->back()->with('error', 'This delivery task is already closed.');
        }

        $validated = $request->validate([
            'rental_item_id' => 'required|integer',
            'quantity' => 'required|integer|min:1',
            'notes' => 'nullable|string|max:500',
        ]);

        $rental = Rental::query()
            ->where('organization_id', $this->orgId())
            ->findOrFail($delivery->rental_id);

        $item = $this->resolveRentalProgressItem($rental, (int) $validated['rental_item_id']);
        $quantity = (int) $validated['quantity'];

        if ($quantity > $item->pending_delivery_quantity) {
            throw ValidationException::withMessages([
                'quantity' => 'Delivery quantity cannot exceed the pending delivery quantity.',
            ]);
        }

        $assetIds = $this->nextPendingAssetIdsForDelivery($item, $quantity);

        $this->deliveryWorkflowService()->recordPartialDelivery(
            $this->orgId(),
            $delivery,
            $rental,
            $item,
            $quantity,
            $assetIds,
            $validated['notes'] ?? null,
            fn (Delivery $freshDelivery) => $this->syncAssignedAssetStatuses($freshDelivery),
            function (Delivery $loggedDelivery, array $context): void {
                ActivityLogger::log('delivery.partial_recorded', $loggedDelivery, $context, 'Partial delivery recorded.');
            }
        );

        return redirect()->back()->with('success', 'Partial delivery recorded successfully.');
    }

    public function recordPartialPickup(Request $request, Delivery $delivery)
    {
        $delivery = $this->scopedDelivery($delivery);
        $this->authorize('update', $delivery);

        if ($delivery->type !== 'pickup' || !$delivery->rental_id) {
            return redirect()->back()->with('error', 'Partial pickup is available only for rental pickup tasks.');
        }

        if (in_array($delivery->status, ['completed', 'cancelled'], true)) {
            return redirect()->back()->with('error', 'This pickup task is already closed.');
        }

        $validated = $request->validate([
            'rental_item_id' => 'required|integer',
            'quantity' => 'required|integer|min:1',
            'notes' => 'nullable|string|max:500',
        ]);

        $rental = Rental::query()
            ->where('organization_id', $this->orgId())
            ->findOrFail($delivery->rental_id);

        $item = $this->resolveRentalProgressItem($rental, (int) $validated['rental_item_id']);
        $quantity = (int) $validated['quantity'];

        if ($quantity > $item->pending_pickup_quantity) {
            throw ValidationException::withMessages([
                'quantity' => 'Pickup quantity cannot exceed the pending pickup quantity.',
            ]);
        }

        $assetIds = $this->nextDeliveredAssetIdsForReturn($item, $quantity);

        $this->deliveryWorkflowService()->recordPartialPickup(
            $this->orgId(),
            $delivery,
            $rental,
            $item,
            $quantity,
            $assetIds,
            $validated['notes'] ?? null,
            fn (Delivery $freshDelivery) => $this->syncAssignedAssetStatuses($freshDelivery)
        );

        ActivityLogger::log('pickup.partial_recorded', $delivery, [
            'rental_item_id' => $item->id,
            'product_id' => $item->product_id,
            'quantity' => $quantity,
            'notes' => $validated['notes'] ?? null,
        ], 'Partial pickup recorded.');

        return redirect()->back()->with('success', 'Partial pickup recorded successfully.');
    }

    public function markInProgress(Request $request, Delivery $delivery)
    {
        $delivery = $this->scopedDelivery($delivery);
        $this->authorize('update', $delivery);

        if ($redirect = $this->ensureProofWorkflowRequest($request, $delivery, 'start')) {
            return $redirect;
        }

        if ($delivery->status === 'completed') {
            return redirect()->back()->with('error', ucfirst($delivery->type) . ' is already completed.');
        }

        if ($delivery->status !== 'pending') {
            return redirect()->back()->with('error', 'Only pending ' . $delivery->type . ' tasks can be started.');
        }

        $validated = $this->validateStartWorkflowRequest($request);

        $this->deliveryWorkflowService()->markInProgress(
            $delivery,
            fn (Delivery $activeDelivery) => $this->syncAssignedAssetStatuses($activeDelivery)
        );

        $this->storeDeliveryWorkflowLocation($delivery, auth()->user(), DeliveryProof::MOMENT_START, $validated);

        ActivityLogger::log('delivery.started', $delivery, [
            'type' => $delivery->type,
            'status' => $delivery->status,
            'location_captured' => filled($validated['location_latitude'] ?? null) && filled($validated['location_longitude'] ?? null),
        ], ucfirst($delivery->type) . ' marked as in progress.');

        return redirect()->back()->with('success', ucfirst($delivery->type) . ' marked as in progress.');
    }

    public function markCompleted(Request $request, Delivery $delivery)
    {
        $delivery = $this->scopedDelivery($delivery);
        $this->authorize('update', $delivery);
        $confirmPartial = $request->boolean('confirm_partial');

        if ($redirect = $this->ensureProofWorkflowRequest($request, $delivery, 'complete')) {
            return $redirect;
        }

        if ($delivery->status === 'completed') {
            return redirect()->back()->with('error', ucfirst($delivery->type) . ' is already completed.');
        }

        if ($delivery->status !== 'in_progress') {
            return redirect()->back()->with('error', 'Only in-progress ' . $delivery->type . ' tasks can be completed.');
        }

        if ($delivery->rental_id) {
            $rental = Rental::query()
                ->where('organization_id', $this->orgId())
                ->find($delivery->rental_id);

            if ($rental) {
                $pendingQuantity = $delivery->type === 'delivery'
                    ? $this->overallPendingDeliveryQuantity($rental)
                    : $this->overallPendingPickupQuantity($rental);

                if ($pendingQuantity > 0 && !$confirmPartial) {
                    return redirect()->back()->with('error', 'Pending item quantities remain. Record the delivered/picked-up quantities first, or complete this task as partial.');
                }
            }
        }

        $validated = $this->validateCompletionWorkflowRequest($request, $delivery);

        $pickupRental = null;
        if ($delivery->type === 'pickup' && $delivery->rental_id) {
            $pickupRental = Rental::query()
                ->where('organization_id', $this->orgId())
                ->find($delivery->rental_id);
        }

        $this->deliveryWorkflowService()->markCompleted(
            $this->orgId(),
            $delivery,
            $pickupRental,
            fn (Delivery $completedDelivery) => $this->syncAssignedAssetStatuses($completedDelivery)
        );

        $this->storeWorkflowCompletionProofs($delivery, auth()->user(), $validated);

        ActivityLogger::log('delivery.completed', $delivery, [
            'type' => $delivery->type,
            'status' => $delivery->status,
            'completed_at' => optional($delivery->completed_at)->toDateTimeString(),
            'proof_stage' => $delivery->type,
        ], ucfirst($delivery->type) . ' marked as completed.');

        return redirect()->back()->with('success', ucfirst($delivery->type) . ' marked as completed.');
    }

    public function cancel(Delivery $delivery)
    {
        $delivery = $this->scopedDelivery($delivery);
        $this->authorize('update', $delivery);

        if ($delivery->status === 'completed') {
            return redirect()->back()->with('error', ucfirst($delivery->type) . ' is already completed and cannot be cancelled.');
        }

        if ($delivery->status === 'cancelled') {
            return redirect()->back()->with('error', ucfirst($delivery->type) . ' is already cancelled.');
        }

        $delivery->update([
            'status' => 'cancelled',
            'completed_at' => null,
        ]);

        $this->syncAssignedAssetStatuses($delivery);

        ActivityLogger::log('delivery.cancelled', $delivery->refresh(), [
            'type' => $delivery->type,
            'status' => $delivery->status,
        ], ucfirst($delivery->type) . ' cancelled.');

        return $this->redirectAfterDeliveryMutation($delivery, ucfirst($delivery->type) . ' cancelled successfully.');
    }

    public function assigned()
    {
        $this->authorize('viewAny', Delivery::class);

        $user = auth()->user();

        $load = [
            'rental.product',
            'rental.rentalItems.product',
            'rental.dispatchWarehouse',
            'rental.customer',
            'sale.product',
            'sale.customer',
            'sale.asset.warehouse',
            'assignedUser',
            'assignedStaff',
        ];

        if ($this->hasRentalAssetsTable()) {
            $load[] = 'rental.activeRentalAssets.asset.warehouse';
        }

        if ($this->hasRentalItemsTable()) {
            $load[] = 'rental.rentalItems.product';
        }

        if ($this->hasRentalSaleItemsTable()) {
            $load[] = 'rental.saleItems.product';
            $load[] = 'rental.saleItems.asset.warehouse';
        }

        $query = $this->applyDeliveryScope(Delivery::with($load))
            ->where('organization_id', $this->orgId())
            ->where('type', 'delivery');

        if ($this->hasDeliveryProofsTable()) {
            $query->withCount('proofs');
        }

        if ($user && $user->hasScope('assigned', 'deliveries')) {
            $query->where('assigned_user_id', $user->id);
        }

        $deliveries = $this->dedupeDeliveryCollection($query->latest()->get());

        return view('deliveries.assigned', compact('deliveries'));
    }

    public function assignedPickups()
    {
        $this->authorize('viewAny', Delivery::class);

        $user = auth()->user();

        $load = [
            'rental.product',
            'rental.dispatchWarehouse',
            'rental.customer',
            'sale.product',
            'sale.customer',
            'sale.asset.warehouse',
            'assignedUser',
            'assignedStaff',
        ];

        if ($this->hasRentalAssetsTable()) {
            $load[] = 'rental.activeRentalAssets.asset';
        }

        $query = $this->applyDeliveryScope(Delivery::with($load))
            ->where('organization_id', $this->orgId())
            ->where('type', 'pickup');

        if ($this->hasDeliveryProofsTable()) {
            $query->withCount('proofs');
        }

        if ($user && $user->hasScope('assigned', 'deliveries')) {
            $query->where('assigned_user_id', $user->id);
        }

        $deliveries = $this->dedupeDeliveryCollection($query->latest()->get());

        return view('deliveries.pickups', compact('deliveries'));
    }
}
