<?php

namespace App\Http\Controllers;

use App\Models\Asset;
use App\Models\Sale;
use App\Models\Customer;
use App\Models\Delivery;
use App\Models\Invoice;
use App\Models\Organization;
use App\Models\Payment;
use App\Models\Product;
use App\Models\Rental;
use App\Models\SaleInventory;
use App\Models\SaleItem;
use App\Services\Finance\InvoiceLinkResolver;
use App\Services\Finance\InvoiceSyncService;
use App\Services\Finance\AmountReductionGuardService;
use App\Services\Finance\PaymentSyncService;
use App\Services\Imports\ImportMatchSignatureService;
use App\Services\Imports\SaleImportExecutor;
use App\Services\Metrics\SalesMetricsService;
use App\Support\ActivityLogger;
use Illuminate\Http\Request;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Illuminate\Validation\ValidationException;
use Illuminate\Validation\Rule;

class SaleController extends Controller
{
    private ?bool $hasWarehouseColumn = null;
    private ?bool $hasStockAppliedColumn = null;
    private ?bool $hasAutoGeneratedFromRentalColumn = null;
    private ?bool $hasInvoiceSaleColumn = null;
    private ?bool $hasSaleItemsTable = null;

    private function salesMetrics(): SalesMetricsService
    {
        return app(SalesMetricsService::class);
    }

    private function orgId()
    {
        return auth()->user()->organization_id;
    }

    private function saleImportExecutor(): SaleImportExecutor
    {
        return app(SaleImportExecutor::class);
    }

    private function importMatchSignatureService(): ImportMatchSignatureService
    {
        return app(ImportMatchSignatureService::class);
    }

    private function hasWarehouseColumn(): bool
    {
        return $this->hasWarehouseColumn ??= Schema::hasColumn('sales', 'warehouse_id');
    }

    private function hasStockAppliedColumn(): bool
    {
        return $this->hasStockAppliedColumn ??= Schema::hasColumn('sales', 'stock_applied');
    }

    private function hasAutoGeneratedFromRentalColumn(): bool
    {
        return $this->hasAutoGeneratedFromRentalColumn ??= Schema::hasColumn('sales', 'auto_generated_from_rental');
    }

    private function hasInvoiceSaleColumn(): bool
    {
        return $this->hasInvoiceSaleColumn ??= Schema::hasColumn('invoices', 'sale_id');
    }

    private function hasSaleItemsTable(): bool
    {
        return $this->hasSaleItemsTable ??= Sale::hasSaleItemsTable();
    }

    private function isAutoGeneratedRentalSale(Sale $sale): bool
    {
        return $this->hasAutoGeneratedFromRentalColumn()
            && (bool) ($sale->auto_generated_from_rental ?? false)
            && !empty($sale->rental_id);
    }

    private function managedRentalSaleRedirect(Sale $sale)
    {
        $message = 'This sale is managed from rental #' . $sale->rental_id . '. Update the linked rental new-product lines instead.';

        if ($sale->rental_id) {
            return redirect()->route('rentals.show', $sale->rental_id)->with('error', $message);
        }

        return redirect()->route('sales.show', $sale)->with('error', $message);
    }

    private function baseSalesQuery(bool $includeRelations = true)
    {
        $query = Sale::query()
            ->where('organization_id', $this->orgId());

        if ($includeRelations) {
            $relations = ['customer', 'product', 'asset.warehouse', 'rental'];

            if ($this->hasDeliverySaleColumn()) {
                $relations[] = 'deliveryRecord.assignedStaff';
                $relations[] = 'deliveryRecord.assignedUser';
            }

            $query->with($relations);
        }

        return $this->applySalesScope($query);
    }

    private function hasDeliverySaleColumn(): bool
    {
        return Schema::hasColumn('deliveries', 'sale_id');
    }

    private function hasCreatedByColumn(): bool
    {
        return Schema::hasColumn('sales', 'created_by');
    }

    private function hasCreatedByUserColumn(): bool
    {
        return Schema::hasColumn('sales', 'created_by_user_id');
    }

    private function paymentsRentalIdIsNullable(): bool
    {
        static $isNullable = null;

        if ($isNullable !== null) {
            return $isNullable;
        }

        if (DB::connection()->getDriverName() === 'sqlite') {
            $columns = DB::select("PRAGMA table_info('payments')");

            foreach ($columns as $column) {
                if (($column->name ?? null) === 'rental_id') {
                    return $isNullable = ((int) ($column->notnull ?? 1)) === 0;
                }
            }

            return $isNullable = true;
        }

        $column = DB::table('information_schema.columns')
            ->select('is_nullable')
            ->where('table_schema', DB::raw('schema()'))
            ->where('table_name', 'payments')
            ->where('column_name', 'rental_id')
            ->first();

        return $isNullable = strtoupper((string) ($column->is_nullable ?? 'NO')) === 'YES';
    }

    private function applySalesScope($query)
    {
        $user = auth()->user();

        if (!$user || !$user->hasScope('self_created', 'sales')) {
            return $query;
        }

        if ($this->hasCreatedByUserColumn()) {
            return $query->where('created_by_user_id', $user->id);
        }

        if ($this->hasCreatedByColumn()) {
            return $query->where('created_by', $user->id);
        }

        return $query;
    }

    private function scopedSale(Sale $sale): Sale
    {
        abort_if($sale->organization_id !== $this->orgId(), 403);

        $user = auth()->user();

        if ($user && $user->hasScope('self_created', 'sales')) {
            $owned = true;

            if ($this->hasCreatedByUserColumn()) {
                $owned = (int) $sale->created_by_user_id === (int) $user->id;
            } elseif ($this->hasCreatedByColumn()) {
                $owned = (int) $sale->created_by === (int) $user->id;
            }

            abort_if(!$owned, 403);
        }

        return $sale;
    }

    private function applyDateRangeFilter($query, string $fromDate, string $toDate)
    {
        if ($fromDate !== '') {
            $query->whereDate('sale_date', '>=', $fromDate);
        }

        if ($toDate !== '') {
            $query->whereDate('sale_date', '<=', $toDate);
        }

        return $query;
    }

    private function applySorting($query, string $sortBy)
    {
        return match ($sortBy) {
            'oldest' => $query->orderBy('sale_date')->orderBy('id'),
            'priority' => $query->orderByRaw("CASE WHEN payment_status IN ('pending', 'partial') THEN 0 ELSE 1 END")
                ->orderByDesc('sale_amount')
                ->orderByDesc('sale_date'),
            'amount_desc' => $query->orderByDesc('sale_amount')->orderByDesc('sale_date'),
            'amount_asc' => $query->orderBy('sale_amount')->orderByDesc('sale_date'),
            'customer_asc' => $query->leftJoin('customers', 'sales.customer_id', '=', 'customers.id')
                ->select('sales.*')
                ->orderBy('customers.name')
                ->orderByDesc('sales.sale_date'),
            'customer_desc' => $query->leftJoin('customers', 'sales.customer_id', '=', 'customers.id')
                ->select('sales.*')
                ->orderByDesc('customers.name')
                ->orderByDesc('sales.sale_date'),
            default => $query->orderByDesc('sale_date')->orderByDesc('id'),
        };
    }

    private function latestInvoiceIdForSale(int $saleId): ?int
    {
        return $this->saleInvoiceLookupQuery([$saleId])
            ->latest('id')
            ->value('id');
    }

    private function saleInvoice(Sale $sale): ?Invoice
    {
        return app(InvoiceLinkResolver::class)->saleInvoice(
            $sale,
            $this->orgId(),
            $this->hasInvoiceSaleColumn()
        );
    }

    private function saleInvoiceLookupQuery(array $saleIds)
    {
        return app(InvoiceLinkResolver::class)->saleInvoiceLookupQuery(
            $this->orgId(),
            $saleIds,
            $this->hasInvoiceSaleColumn()
        );
    }

    private function nextInvoiceNumber(): string
    {
        return 'INV-' . str_pad((Invoice::max('id') ?? 0) + 1, 6, '0', STR_PAD_LEFT);
    }

    private function normalizeStateName(?string $value): ?string
    {
        $normalized = strtolower(trim((string) $value));

        return $normalized !== '' ? $normalized : null;
    }

    private function productTaxPercentage(Product $product): float
    {
        return match ($product->gst_tax_type) {
            Product::GST_TAX_TYPE_CGST_SGST => round((float) ($product->cgst_rate ?? 0) + (float) ($product->sgst_rate ?? 0), 2),
            Product::GST_TAX_TYPE_IGST => round((float) ($product->igst_rate ?? 0), 2),
            default => 0.0,
        };
    }

    private function calculateSaleCommercials(
        float $quantity,
        float $unitPrice,
        float $discountAmount,
        float $shippingCharges,
        float $taxPercentage,
        string $taxCalculationMode
    ): array {
        $quantity = max($quantity, 1);
        $unitPrice = max($unitPrice, 0);
        $discountAmount = max($discountAmount, 0);
        $shippingCharges = max($shippingCharges, 0);
        $taxPercentage = max($taxPercentage, 0);
        $taxCalculationMode = $taxCalculationMode === 'inclusive' ? 'inclusive' : 'exclusive';

        $subtotal = round($quantity * $unitPrice, 2);
        $taxableBase = max($subtotal - $discountAmount, 0);

        if ($taxCalculationMode === 'inclusive' && $taxPercentage > 0) {
            $taxableAmount = round($taxableBase / (1 + ($taxPercentage / 100)), 2);
            $totalTaxAmount = round($taxableBase - $taxableAmount, 2);
        } else {
            $taxableAmount = $taxableBase;
            $totalTaxAmount = round(($taxableAmount * $taxPercentage) / 100, 2);
        }

        $saleAmount = round($taxableBase + ($taxCalculationMode === 'exclusive' ? $totalTaxAmount : 0) + $shippingCharges, 2);

        return [
            'subtotal' => $subtotal,
            'discount_amount' => $discountAmount,
            'shipping_charges' => $shippingCharges,
            'taxable_amount' => $taxableAmount,
            'total_tax_amount' => $totalTaxAmount,
            'sale_amount' => $saleAmount,
        ];
    }

    private function normalizedSaleItems(Request $request, ?Sale $sale = null): array
    {
        $requestedItems = collect($request->input('sale_items', []))
            ->map(fn ($row) => is_array($row) ? $row : [])
            ->values();

        $rows = $requestedItems
            ->filter(function (array $row): bool {
                return collect([
                    $row['product_id'] ?? null,
                    $row['asset_id'] ?? null,
                    $row['warehouse_id'] ?? null,
                    $row['quantity'] ?? null,
                    $row['unit_price'] ?? null,
                    $row['discount_amount'] ?? null,
                    $row['shipping_charges'] ?? null,
                    $row['tax_percentage'] ?? null,
                    $row['notes'] ?? null,
                ])->contains(fn ($value) => filled($value) && $value !== '0' && $value !== 0 && $value !== '0.00');
            })
            ->values();

        if ($rows->isEmpty() && $request->filled('product_id')) {
            $rows = collect([[
                'product_id' => $request->input('product_id'),
                'asset_id' => $request->input('asset_id'),
                'warehouse_id' => $request->input('warehouse_id'),
                'quantity' => $request->input('quantity'),
                'unit_price' => $request->input('unit_price'),
                'discount_amount' => $request->input('discount_amount'),
                'shipping_charges' => $request->input('shipping_charges'),
                'tax_percentage' => $request->input('tax_percentage'),
                'tax_calculation_mode' => $request->input('tax_calculation_mode'),
                'notes' => $request->input('notes'),
            ]]);
        }

        if ($rows->isEmpty()) {
            throw ValidationException::withMessages([
                'sale_items' => ['Add at least one product line before saving the sale.'],
            ]);
        }

        $productIds = $rows->pluck('product_id')
            ->filter(fn ($id) => filled($id))
            ->map(fn ($id) => (int) $id)
            ->unique()
            ->values();

        $products = Product::query()
            ->where('organization_id', $this->orgId())
            ->whereIn('id', $productIds)
            ->get()
            ->keyBy('id');

        return $rows->map(function (array $row, int $index) use ($products) {
            $productId = (int) ($row['product_id'] ?? 0);
            $product = $products->get($productId);

            if (!$product) {
                throw ValidationException::withMessages([
                    "sale_items.$index.product_id" => ['Select a valid product for this line.'],
                ]);
            }

            if (!$product->canSell()) {
                throw ValidationException::withMessages([
                    "sale_items.$index.product_id" => [$product->name . ' is not available for sale.'],
                ]);
            }

            $quantity = max((int) ($row['quantity'] ?? 0), 0);
            $unitPrice = round((float) ($row['unit_price'] ?? 0), 2);
            $discountAmount = round((float) ($row['discount_amount'] ?? 0), 2);
            $shippingCharges = round((float) ($row['shipping_charges'] ?? 0), 2);
            $taxCalculationMode = (($row['tax_calculation_mode'] ?? '') === 'inclusive')
                ? 'inclusive'
                : (($product->gst_calculation_mode ?? 'exclusive') === 'inclusive' ? 'inclusive' : 'exclusive');
            $taxPercentage = filled($row['tax_percentage'] ?? null)
                ? round((float) ($row['tax_percentage'] ?? 0), 2)
                : $this->productTaxPercentage($product);

            if ($quantity < 1) {
                throw ValidationException::withMessages([
                    "sale_items.$index.quantity" => ['Quantity must be greater than 0.'],
                ]);
            }

            foreach ([
                'unit_price' => $unitPrice,
                'discount_amount' => $discountAmount,
                'shipping_charges' => $shippingCharges,
                'tax_percentage' => $taxPercentage,
            ] as $field => $value) {
                if ($value < 0) {
                    throw ValidationException::withMessages([
                        "sale_items.$index.$field" => [ucfirst(str_replace('_', ' ', $field)) . ' cannot be negative.'],
                    ]);
                }
            }

            $commercials = $this->calculateSaleCommercials(
                (float) $quantity,
                $unitPrice,
                $discountAmount,
                $shippingCharges,
                $taxPercentage,
                $taxCalculationMode
            );

            return [
                'product_id' => $product->id,
                'asset_id' => filled($row['asset_id'] ?? null) ? (int) $row['asset_id'] : null,
                'warehouse_id' => filled($row['warehouse_id'] ?? null) ? (int) $row['warehouse_id'] : null,
                'quantity' => $quantity,
                'unit_price' => $unitPrice,
                'discount_amount' => $discountAmount,
                'shipping_charges' => $shippingCharges,
                'tax_percentage' => $taxPercentage,
                'tax_calculation_mode' => $taxCalculationMode,
                'notes' => filled($row['notes'] ?? null) ? trim((string) $row['notes']) : null,
                'commercials' => $commercials,
                'product' => $product,
            ];
        })->all();
    }

    private function aggregateSaleCommercials(array $saleItems): array
    {
        return [
            'subtotal' => round((float) collect($saleItems)->sum(fn (array $line) => (float) ($line['commercials']['subtotal'] ?? 0)), 2),
            'discount_amount' => round((float) collect($saleItems)->sum(fn (array $line) => (float) ($line['discount_amount'] ?? 0)), 2),
            'shipping_charges' => round((float) collect($saleItems)->sum(fn (array $line) => (float) ($line['shipping_charges'] ?? 0)), 2),
            'taxable_amount' => round((float) collect($saleItems)->sum(fn (array $line) => (float) ($line['commercials']['taxable_amount'] ?? 0)), 2),
            'total_tax_amount' => round((float) collect($saleItems)->sum(fn (array $line) => (float) ($line['commercials']['total_tax_amount'] ?? 0)), 2),
            'sale_amount' => round((float) collect($saleItems)->sum(fn (array $line) => (float) ($line['commercials']['sale_amount'] ?? 0)), 2),
            'quantity' => (int) collect($saleItems)->sum(fn (array $line) => (int) ($line['quantity'] ?? 0)),
        ];
    }

    private function saleSummaryPayload(Request $request, Customer $customer, array $saleItems, array $commercials): array
    {
        $primaryLine = $saleItems[0];

        $payload = [
            'customer_id' => $customer->id,
            'product_id' => $primaryLine['product_id'],
            'asset_id' => $primaryLine['asset_id'],
            'rental_id' => $request->filled('rental_id') ? $request->integer('rental_id') : null,
            'quantity' => max((int) ($primaryLine['quantity'] ?? 1), 1),
            'unit_price' => $primaryLine['unit_price'],
            'discount_amount' => $commercials['discount_amount'],
            'shipping_charges' => $commercials['shipping_charges'],
            'tax_percentage' => $primaryLine['tax_percentage'],
            'tax_calculation_mode' => $primaryLine['tax_calculation_mode'],
            'sale_date' => $request->input('sale_date'),
            'sale_amount' => $commercials['sale_amount'],
            'payment_status' => $request->input('payment_status'),
            'notes' => $request->input('notes'),
            'organization_id' => $this->orgId(),
        ];

        if ($this->hasWarehouseColumn()) {
            $payload['warehouse_id'] = $primaryLine['warehouse_id'];
        }

        return $payload;
    }

    private function syncSaleItems(Sale $sale, array $saleItems): void
    {
        if (!$this->hasSaleItemsTable()) {
            return;
        }

        $sale->saleItems()->delete();

        foreach ($saleItems as $index => $line) {
            $sale->saleItems()->create([
                'organization_id' => $this->orgId(),
                'product_id' => $line['product_id'],
                'asset_id' => $line['asset_id'],
                'warehouse_id' => $line['warehouse_id'],
                'quantity' => $line['quantity'],
                'unit_price' => $line['unit_price'],
                'discount_amount' => $line['discount_amount'],
                'shipping_charges' => $line['shipping_charges'],
                'tax_percentage' => $line['tax_percentage'],
                'tax_calculation_mode' => $line['tax_calculation_mode'],
                'taxable_amount' => $line['commercials']['taxable_amount'],
                'total_tax_amount' => $line['commercials']['total_tax_amount'],
                'line_total' => $line['commercials']['sale_amount'],
                'sort_order' => $index,
                'asset_ids' => $line['asset_id'] ? [(int) $line['asset_id']] : null,
                'notes' => $line['notes'],
            ]);
        }

        $sale->unsetRelation('saleItems');
    }

    private function saleInvoiceLines(Sale $sale): array
    {
        return $sale->displaySaleItems()
            ->map(function ($item) {
                $product = $item->product ?: Product::query()
                    ->where('organization_id', $this->orgId())
                    ->find($item->product_id);

                return [
                    'product_id' => (int) $item->product_id,
                    'asset_id' => $item->asset_id ? (int) $item->asset_id : null,
                    'warehouse_id' => $item->warehouse_id ? (int) $item->warehouse_id : null,
                    'quantity' => max((int) ($item->quantity ?? 1), 1),
                    'unit_price' => round((float) ($item->unit_price ?? 0), 2),
                    'discount_amount' => round((float) ($item->discount_amount ?? 0), 2),
                    'shipping_charges' => round((float) ($item->shipping_charges ?? 0), 2),
                    'tax_percentage' => round((float) ($item->tax_percentage ?? 0), 2),
                    'tax_calculation_mode' => ($item->tax_calculation_mode ?? 'exclusive') === 'inclusive' ? 'inclusive' : 'exclusive',
                    'notes' => $item->notes,
                    'commercials' => [
                        'subtotal' => round(max((int) ($item->quantity ?? 1), 1) * (float) ($item->unit_price ?? 0), 2),
                        'discount_amount' => round((float) ($item->discount_amount ?? 0), 2),
                        'shipping_charges' => round((float) ($item->shipping_charges ?? 0), 2),
                        'taxable_amount' => round((float) ($item->taxable_amount ?? 0), 2),
                        'total_tax_amount' => round((float) ($item->total_tax_amount ?? 0), 2),
                        'sale_amount' => round((float) ($item->line_total ?? 0), 2),
                    ],
                    'product' => $product,
                ];
            })
            ->values()
            ->all();
    }

    private function createSaleInvoice(Sale $sale): Invoice
    {
        $sale->loadMissing(['customer', 'product', 'asset.warehouse', 'rental']);

        if ($this->hasSaleItemsTable()) {
            $sale->loadMissing(['saleItems.product', 'saleItems.asset', 'saleItems.warehouse']);
        }

        if ($existingInvoice = $this->saleInvoice($sale)) {
            $this->syncSaleInvoiceFromSale($sale, $existingInvoice);
            $this->syncExistingSaleInvoicePayment($sale, $existingInvoice);

            return $existingInvoice;
        }

        $organization = Organization::findOrFail($this->orgId());
        $taxType = $this->saleTaxType($sale, $organization);
        $saleItems = $this->saleInvoiceLines($sale);
        $commercials = $this->aggregateSaleCommercials($saleItems);

        return DB::transaction(function () use ($sale, $organization, $taxType, $commercials, $saleItems) {
            $invoice = app(InvoiceSyncService::class)->createSaleInvoiceFromPayload(
                $this->orgId(),
                $sale,
                $this->hasInvoiceSaleColumn(),
                $this->nextInvoiceNumber(),
                $this->saleInvoicePayload($sale, $organization, $taxType, $commercials),
                $this->saleInvoiceItemPayloads($sale, $taxType, $saleItems),
                $sale->payment_status === 'paid',
                auth()->id()
            );

            if ($sale->payment_status === 'paid') {
                app(PaymentSyncService::class)->recordPaidSaleInvoice(
                    $this->orgId(),
                    $sale,
                    $invoice,
                    (float) $commercials['sale_amount'],
                    $this->paymentsRentalIdIsNullable()
                );
                $invoice->refresh()->syncFinancialStatus();
            }

            return $invoice;
        });
    }

    private function saleTaxType(Sale $sale, Organization $organization): string
    {
        $customerState = $this->normalizeStateName($sale->customer?->state);
        $organizationState = $this->normalizeStateName($organization->state);

        return ($customerState && $organizationState && $customerState !== $organizationState)
            ? 'igst'
            : 'cgst_sgst';
    }

    private function saleInvoicePayload(Sale $sale, Organization $organization, string $taxType, array $commercials): array
    {
        return [
            'organization_id' => $this->orgId(),
            'invoice_date' => $sale->sale_date ?: now()->toDateString(),
            'due_date' => $sale->sale_date ?: now()->toDateString(),
            'customer_id' => $sale->customer_id,
            'bill_to_name' => $sale->customer?->name,
            'bill_to_phone' => $sale->customer?->phone,
            'bill_to_email' => $sale->customer?->email,
            'bill_to_address' => $sale->customer?->address,
            'bill_to_city' => $sale->customer?->city,
            'bill_to_state' => $sale->customer?->state,
            'bill_to_pincode' => $sale->customer?->pincode,
            'ship_to_name' => $sale->customer?->name,
            'ship_to_phone' => $sale->customer?->phone,
            'ship_to_address' => $sale->customer?->address,
            'ship_to_city' => $sale->customer?->city,
            'ship_to_state' => $sale->customer?->state,
            'ship_to_pincode' => $sale->customer?->pincode,
            'place_of_supply_state' => $sale->customer?->state,
            'tax_type' => $taxType,
            'tax_calculation_mode' => $sale->tax_calculation_mode ?: 'exclusive',
            'subtotal' => $commercials['subtotal'],
            'discount_amount' => $commercials['discount_amount'],
            'deposit_amount' => 0,
            'shipping_charges' => $commercials['shipping_charges'],
            'taxable_amount' => $commercials['taxable_amount'],
            'cgst_amount' => $taxType === 'cgst_sgst' ? round($commercials['total_tax_amount'] / 2, 2) : 0,
            'sgst_amount' => $taxType === 'cgst_sgst' ? round($commercials['total_tax_amount'] / 2, 2) : 0,
            'igst_amount' => $taxType === 'igst' ? $commercials['total_tax_amount'] : 0,
            'total_tax_amount' => $commercials['total_tax_amount'],
            'total_amount' => $commercials['sale_amount'],
            'notes' => 'Auto-generated for sale #' . $sale->id,
            'terms_conditions' => $organization->default_terms,
        ];
    }

    private function saleInvoiceItemPayloads(Sale $sale, string $taxType, array $saleItems): array
    {
        return collect($saleItems)->map(function (array $line) use ($sale, $taxType) {
            $taxAmount = (float) ($line['commercials']['total_tax_amount'] ?? 0);
            $lineTotalExShipping = round((float) ($line['commercials']['sale_amount'] ?? 0) - (float) ($line['shipping_charges'] ?? 0), 2);
            $product = $line['product'] ?? null;
            $description = $product?->name ?? 'Sale product';

            $assetNote = !empty($line['asset_id']) ? ' | Asset linked' : '';

            return [
                'product_id' => $line['product_id'],
                'source_type' => 'sale',
                'source_id' => $sale->id,
                'description' => $description . ' | Unit: sale | Qty: ' . (float) $line['quantity'] . $assetNote,
                'hsn_sac_code' => null,
                'quantity' => (float) $line['quantity'],
                'unit' => 'sale',
                'days' => null,
                'rate' => (float) $line['unit_price'],
                'discount_amount' => (float) $line['discount_amount'],
                'taxable_amount' => (float) ($line['commercials']['taxable_amount'] ?? 0),
                'tax_percentage' => (float) $line['tax_percentage'],
                'tax_type' => $taxType,
                'cgst_rate' => $taxType === 'cgst_sgst' ? round(((float) $line['tax_percentage']) / 2, 2) : 0,
                'sgst_rate' => $taxType === 'cgst_sgst' ? round(((float) $line['tax_percentage']) / 2, 2) : 0,
                'igst_rate' => $taxType === 'igst' ? (float) $line['tax_percentage'] : 0,
                'cgst_amount' => $taxType === 'cgst_sgst' ? round($taxAmount / 2, 2) : 0,
                'sgst_amount' => $taxType === 'cgst_sgst' ? round($taxAmount / 2, 2) : 0,
                'igst_amount' => $taxType === 'igst' ? $taxAmount : 0,
                'line_total' => $lineTotalExShipping,
            ];
        })->values()->all();
    }

    private function syncSaleInvoiceFromSale(Sale $sale, Invoice $invoice): void
    {
        $sale->loadMissing(['customer', 'product']);

        if ($this->hasSaleItemsTable()) {
            $sale->loadMissing(['saleItems.product', 'saleItems.asset', 'saleItems.warehouse']);
        }

        $organization = Organization::findOrFail($this->orgId());
        $taxType = $this->saleTaxType($sale, $organization);
        $saleItems = $this->saleInvoiceLines($sale);
        $commercials = $this->aggregateSaleCommercials($saleItems);

        app(InvoiceSyncService::class)->syncSaleInvoiceFromPayload(
            $invoice,
            $this->saleInvoicePayload($sale, $organization, $taxType, $commercials),
            $this->saleInvoiceItemPayloads($sale, $taxType, $saleItems),
            $sale->id
        );
    }

    private function recordPaidSaleInvoice(Sale $sale, Invoice $invoice, float $amount): void
    {
        app(PaymentSyncService::class)->recordPaidSaleInvoice(
            $this->orgId(),
            $sale,
            $invoice,
            $amount,
            $this->paymentsRentalIdIsNullable()
        );
    }

    private function autoPaidSalePaymentQuery(Sale $sale, Invoice $invoice)
    {
        return Payment::query()
            ->where('organization_id', $this->orgId())
            ->where('invoice_id', $invoice->id)
            ->where('notes', 'Auto-recorded from paid sale #' . $sale->id . '.');
    }

    private function syncExistingSaleInvoicePayment(Sale $sale, Invoice $invoice): void
    {
        app(PaymentSyncService::class)->syncExistingSaleInvoicePayment(
            $this->orgId(),
            $sale,
            $invoice,
            $this->paymentsRentalIdIsNullable()
        );
    }

    private function syncSalePaymentStatusFromInvoice(Sale $sale, Invoice $invoice): void
    {
        app(PaymentSyncService::class)->syncSalePaymentStatusFromInvoice($sale, $invoice);
    }

    private function validateQuickPayment(Request $request): array
    {
        return $request->validate([
            'payment_date' => 'required|date',
            'amount' => 'required|numeric|min:0.01',
            'payment_method' => 'nullable|string|max:255',
            'notes' => 'nullable|string',
        ]);
    }

    private function createInvoicePaymentForSale(Sale $sale, Invoice $invoice, array $validated): Payment
    {
        return app(PaymentSyncService::class)->createInvoicePayment(
            $this->orgId(),
            $invoice,
            $validated,
            $sale->rental_id ? (int) $sale->rental_id : null,
            $sale->rental_id || $this->paymentsRentalIdIsNullable(),
            'Payment amount cannot exceed the invoice balance due.',
            'Payment could not be recorded because the payments table still requires rental_id.'
        );
    }

    private function saleValidationRules(?Sale $sale = null): array
    {
        return [
            'customer_id' => [
                'required',
                Rule::exists('customers', 'id')->where(fn ($query) => $query->where('organization_id', $this->orgId())),
            ],
            'product_id' => [
                'nullable',
                Rule::exists('products', 'id')->where(fn ($query) => $query->where('organization_id', $this->orgId())),
            ],
            'asset_id' => [
                'nullable',
                Rule::exists('assets', 'id')->where(fn ($query) => $query->where('organization_id', $this->orgId())),
            ],
            'rental_id' => [
                'nullable',
                Rule::exists('rentals', 'id')->where(fn ($query) => $query->where('organization_id', $this->orgId())),
            ],
            'quantity' => 'nullable|integer|min:1',
            'unit_price' => 'nullable|numeric|min:0',
            'discount_amount' => 'nullable|numeric|min:0',
            'shipping_charges' => 'nullable|numeric|min:0',
            'tax_percentage' => 'nullable|numeric|min:0|max:100',
            'tax_calculation_mode' => 'nullable|in:exclusive,inclusive',
            'sale_date' => 'required|date',
            'sale_amount' => 'nullable|numeric|min:0',
            'payment_status' => 'required|in:pending,paid,partial,void',
            'notes' => 'nullable|string',
            'sale_items' => 'nullable|array',
            'sale_items.*.product_id' => [
                'nullable',
                Rule::exists('products', 'id')->where(fn ($query) => $query->where('organization_id', $this->orgId())),
            ],
            'sale_items.*.asset_id' => [
                'nullable',
                Rule::exists('assets', 'id')->where(fn ($query) => $query->where('organization_id', $this->orgId())),
            ],
            'sale_items.*.warehouse_id' => [
                'nullable',
                Rule::exists('warehouses', 'id')->where(fn ($query) => $query->where('organization_id', $this->orgId())),
            ],
            'sale_items.*.quantity' => 'nullable|integer|min:1',
            'sale_items.*.unit_price' => 'nullable|numeric|min:0',
            'sale_items.*.discount_amount' => 'nullable|numeric|min:0',
            'sale_items.*.shipping_charges' => 'nullable|numeric|min:0',
            'sale_items.*.tax_percentage' => 'nullable|numeric|min:0|max:100',
            'sale_items.*.tax_calculation_mode' => 'nullable|in:exclusive,inclusive',
            'sale_items.*.notes' => 'nullable|string',
        ];
    }

    private function saleUsesAppliedStock(Sale $sale): bool
    {
        if ($this->hasStockAppliedColumn()) {
            return (bool) ($sale->stock_applied ?? false);
        }

        return ($sale->payment_status ?? 'pending') !== 'void';
    }

    private function resolveSaleInventory(Product $product, int $quantity, ?int $warehouseId = null, bool $restore = false): ?SaleInventory
    {
        $inventoryQuery = SaleInventory::query()
            ->where('organization_id', $this->orgId())
            ->where('product_id', $product->id);

        if ($warehouseId) {
            return (clone $inventoryQuery)
                ->where('warehouse_id', $warehouseId)
                ->lockForUpdate()
                ->first();
        }

        $inventories = (clone $inventoryQuery)
            ->orderBy('id')
            ->lockForUpdate()
            ->get();

        if ($inventories->isEmpty()) {
            return null;
        }

        if ($restore) {
            return $inventories->first();
        }

        return $inventories->first(fn ($inventory) => $inventory->availableToSell() >= $quantity);
    }

    private function updateSaleStockState(Sale $sale, bool $applied, ?int $warehouseId = null): void
    {
        $attributes = [];

        if ($this->hasWarehouseColumn()) {
            $attributes['warehouse_id'] = $warehouseId;
        }

        if ($this->hasStockAppliedColumn()) {
            $attributes['stock_applied'] = $applied;
        }

        if (!empty($attributes)) {
            $sale->forceFill($attributes)->saveQuietly();
        }
    }

    private function syncTrackedSaleSummary(Product $product): void
    {
        SaleInventory::syncFromSaleUnits($this->orgId(), $product->id);
        $product->refresh();
        $product->syncLegacyStockFields();
    }

    private function trackedSaleAllocationError(Product $product): ValidationException
    {
        return ValidationException::withMessages([
            'quantity' => ['Tracked sale product requires available sale asset units. Add stock or convert rental asset to sale stock first.'],
        ]);
    }

    private function trackedSaleAllocatedAssetsForLine(SaleItem $saleItem)
    {
        $assetIds = collect($saleItem->asset_ids ?? [])
            ->map(fn ($assetId) => (int) $assetId)
            ->filter(fn ($assetId) => $assetId > 0)
            ->values()
            ->all();

        if (empty($assetIds) && $saleItem->asset_id) {
            $assetIds = [(int) $saleItem->asset_id];
        }

        if (empty($assetIds)) {
            return collect();
        }

        return Asset::query()
            ->where('organization_id', $this->orgId())
            ->whereIn('id', $assetIds)
            ->lockForUpdate()
            ->get()
            ->sortBy(fn ($asset) => $asset->serial_number ?: (string) $asset->id)
            ->values();
    }

    private function trackedSaleAllocatedAssets(Sale $sale)
    {
        $sale->loadMissing('saleUnits');

        $assetIds = $sale->saleUnits
            ->pluck('id')
            ->map(fn ($assetId) => (int) $assetId)
            ->filter(fn ($assetId) => $assetId > 0)
            ->values()
            ->all();

        if (empty($assetIds) && $sale->asset_id) {
            $assetIds = [(int) $sale->asset_id];
        }

        if (empty($assetIds)) {
            return collect();
        }

        return Asset::query()
            ->where('organization_id', $this->orgId())
            ->whereIn('id', $assetIds)
            ->lockForUpdate()
            ->get()
            ->sortBy(fn ($asset) => $asset->serial_number ?: (string) $asset->id)
            ->values();
    }

    private function autoAllocateTrackedSaleAssets(Product $product, int $quantity, ?int $warehouseId = null, ?int $explicitAssetId = null)
    {
        if ($quantity <= 0) {
            return collect();
        }

        $baseQuery = Asset::query()
            ->where('organization_id', $this->orgId())
            ->where('product_id', $product->id)
            ->where('asset_stage', Asset::STAGE_NEW_STOCK);

        if ($explicitAssetId) {
            $asset = (clone $baseQuery)
                ->lockForUpdate()
                ->findOrFail($explicitAssetId);

            if ($asset->asset_status !== 'available_for_sale') {
                throw $this->trackedSaleAllocationError($product);
            }

            if ($quantity !== 1) {
                throw ValidationException::withMessages([
                    'quantity' => ['Quantity must be 1 when a serialized asset is selected for a tracked sale product.'],
                ]);
            }

            return collect([$asset]);
        }

        if ($warehouseId) {
            $assets = (clone $baseQuery)
                ->where('warehouse_id', $warehouseId)
                ->where('asset_status', 'available_for_sale')
                ->orderBy('serial_number')
                ->orderBy('id')
                ->lockForUpdate()
                ->limit($quantity)
                ->get();

            if ($assets->count() < $quantity) {
                throw $this->trackedSaleAllocationError($product);
            }

            return $assets->values();
        }

        $assets = (clone $baseQuery)
            ->where('asset_status', 'available_for_sale')
            ->orderByRaw('CASE WHEN warehouse_id IS NULL THEN 1 ELSE 0 END')
            ->orderBy('warehouse_id')
            ->orderBy('serial_number')
            ->orderBy('id')
            ->lockForUpdate()
            ->limit($quantity)
            ->get();

        if ($assets->count() < $quantity) {
            throw $this->trackedSaleAllocationError($product);
        }

        return $assets->values();
    }

    private function syncTrackedSaleUnitAssignments(Sale $sale, $assets): void
    {
        $syncPayload = $assets
            ->mapWithKeys(fn ($asset) => [
                (int) $asset->id => ['organization_id' => $this->orgId()],
            ])
            ->all();

        $sale->saleUnits()->sync($syncPayload);

        $resolvedAssetId = $assets->count() === 1 ? (int) $assets->first()->id : null;

        if ((int) ($sale->asset_id ?? 0) !== (int) ($resolvedAssetId ?? 0)) {
            $sale->forceFill([
                'asset_id' => $resolvedAssetId,
            ])->saveQuietly();
        }
    }

    private function adjustSaleStock(Sale $sale, bool $restore = false): void
    {
        if ($this->hasSaleItemsTable()) {
            $sale->loadMissing(['saleItems.product', 'saleItems.asset']);

            if ($sale->saleItems->isNotEmpty()) {
                $this->adjustSaleItemsStock($sale, $restore);

                return;
            }
        }

        $sale->loadMissing(['product', 'asset']);

        $product = Product::query()
            ->where('organization_id', $this->orgId())
            ->findOrFail($sale->product_id);

        $quantity = max((int) $sale->quantity, 1);
        $warehouseId = $this->hasWarehouseColumn() ? (int) ($sale->warehouse_id ?? 0) : 0;
        $asset = null;

        if ($product->tracksSaleStock()) {
            if ($restore) {
                $allocatedAssets = $this->trackedSaleAllocatedAssets($sale);

                foreach ($allocatedAssets as $allocatedAsset) {
                    if ($allocatedAsset->asset_stage !== Asset::STAGE_NEW_STOCK) {
                        continue;
                    }

                    $allocatedAsset->update(['asset_status' => 'available_for_sale']);
                }

                $this->syncTrackedSaleSummary($product);
                $this->updateSaleStockState(
                    $sale,
                    false,
                    $warehouseId ?: ($allocatedAssets->count() === 1 ? (int) ($allocatedAssets->first()->warehouse_id ?: 0) : null)
                );

                return;
            }

            $allocatedAssets = $this->autoAllocateTrackedSaleAssets(
                $product,
                $quantity,
                $warehouseId ?: null,
                $sale->asset_id ? (int) $sale->asset_id : null
            );

            foreach ($allocatedAssets as $allocatedAsset) {
                $allocatedAsset->update(['asset_status' => 'sold']);
            }

            $this->syncTrackedSaleUnitAssignments($sale, $allocatedAssets);
            $this->syncTrackedSaleSummary($product);

            $resolvedWarehouseId = null;

            if ($allocatedAssets->pluck('warehouse_id')->filter(fn ($warehouse) => filled($warehouse))->unique()->count() === 1) {
                $resolvedWarehouseId = (int) $allocatedAssets->pluck('warehouse_id')->first();
            } elseif ($warehouseId > 0) {
                $resolvedWarehouseId = $warehouseId;
            }

            $this->updateSaleStockState($sale, true, $resolvedWarehouseId);

            return;
        }

        if ($sale->asset_id) {
            $asset = Asset::query()
                ->where('organization_id', $this->orgId())
                ->lockForUpdate()
                ->findOrFail($sale->asset_id);

            if ((int) $asset->product_id !== (int) $product->id) {
                throw ValidationException::withMessages([
                    'asset_id' => 'Selected asset does not belong to the chosen product.',
                ]);
            }

            if ($asset->asset_stage !== Asset::STAGE_NEW_STOCK) {
                throw ValidationException::withMessages([
                    'asset_id' => 'Only new stock assets can be linked to a sale.',
                ]);
            }

            $warehouseId = (int) ($asset->warehouse_id ?: $warehouseId);

            if ($restore) {
                $asset->update(['asset_status' => 'available_for_sale']);
            } else {
                if ($asset->asset_status !== 'available_for_sale') {
                    throw ValidationException::withMessages([
                        'asset_id' => 'Selected asset is no longer available for sale.',
                    ]);
                }

                $asset->update(['asset_status' => 'sold']);
            }
        }

        $inventory = $this->resolveSaleInventory($product, $quantity, $warehouseId ?: null, $restore);

        if ($inventory) {
            if (!$restore && $inventory->availableToSell() < $quantity) {
                throw ValidationException::withMessages([
                    'quantity' => 'Sale quantity exceeds available stock for ' . $product->name . '.',
                ]);
            }

            if ($restore) {
                $inventory->increment('quantity_in_stock', $quantity);
            } else {
                $inventory->decrement('quantity_in_stock', $quantity);
            }

            $product->syncLegacyStockFields();
            $warehouseId = (int) $inventory->warehouse_id;
        } else {
            if ($restore) {
                $product->increment('available_quantity', $quantity);
            } else {
                if ((int) $product->available_quantity < $quantity) {
                    throw ValidationException::withMessages([
                        'quantity' => 'Sale quantity exceeds available stock for ' . $product->name . '.',
                    ]);
                }

                $product->decrement('available_quantity', $quantity);
            }
        }

        $this->updateSaleStockState($sale, !$restore, $warehouseId ?: null);
    }

    private function adjustSaleItemsStock(Sale $sale, bool $restore = false): void
    {
        $sale->loadMissing(['saleItems.product', 'saleItems.asset']);
        $trackedSaleUnitIds = [];
        $resolvedWarehouseId = null;

        foreach ($sale->saleItems as $saleItem) {
            $product = Product::query()
                ->where('organization_id', $this->orgId())
                ->findOrFail($saleItem->product_id);

            $quantity = max((int) ($saleItem->quantity ?? 0), 1);
            $warehouseId = $this->hasWarehouseColumn() ? (int) ($saleItem->warehouse_id ?? $sale->warehouse_id ?? 0) : 0;

            if ($product->tracksSaleStock()) {
                if ($restore) {
                    $allocatedAssets = $this->trackedSaleAllocatedAssetsForLine($saleItem);

                    foreach ($allocatedAssets as $allocatedAsset) {
                        if ($allocatedAsset->asset_stage === Asset::STAGE_NEW_STOCK) {
                            $allocatedAsset->update(['asset_status' => 'available_for_sale']);
                        }
                    }

                    $this->syncTrackedSaleSummary($product);
                    continue;
                }

                $allocatedAssets = $this->autoAllocateTrackedSaleAssets(
                    $product,
                    $quantity,
                    $warehouseId ?: null,
                    $saleItem->asset_id ? (int) $saleItem->asset_id : null
                );

                foreach ($allocatedAssets as $allocatedAsset) {
                    $allocatedAsset->update(['asset_status' => 'sold']);
                }

                $saleItem->forceFill([
                    'asset_id' => $allocatedAssets->count() === 1 ? (int) $allocatedAssets->first()->id : null,
                    'warehouse_id' => $allocatedAssets->pluck('warehouse_id')->filter()->unique()->count() === 1
                        ? (int) $allocatedAssets->pluck('warehouse_id')->first()
                        : ($warehouseId ?: null),
                    'asset_ids' => $allocatedAssets->pluck('id')->map(fn ($id) => (int) $id)->values()->all(),
                ])->saveQuietly();

                $trackedSaleUnitIds = array_merge($trackedSaleUnitIds, $allocatedAssets->pluck('id')->map(fn ($id) => (int) $id)->all());
                $resolvedWarehouseId = $saleItem->warehouse_id ?: $resolvedWarehouseId;

                $this->syncTrackedSaleSummary($product);
                continue;
            }

            $asset = null;

            if ($saleItem->asset_id) {
                $asset = Asset::query()
                    ->where('organization_id', $this->orgId())
                    ->lockForUpdate()
                    ->findOrFail($saleItem->asset_id);

                if ((int) $asset->product_id !== (int) $product->id) {
                    throw ValidationException::withMessages([
                        'sale_items' => ['Selected asset does not belong to ' . $product->name . '.'],
                    ]);
                }

                if ($asset->asset_stage !== Asset::STAGE_NEW_STOCK) {
                    throw ValidationException::withMessages([
                        'sale_items' => ['Only new stock assets can be linked to a sale.'],
                    ]);
                }

                if ($restore) {
                    $asset->update(['asset_status' => 'available_for_sale']);
                } else {
                    if ($asset->asset_status !== 'available_for_sale') {
                        throw ValidationException::withMessages([
                            'sale_items' => ['Selected asset is no longer available for sale.'],
                        ]);
                    }

                    $asset->update(['asset_status' => 'sold']);
                }

                $resolvedWarehouseId = (int) ($asset->warehouse_id ?: $warehouseId ?: $resolvedWarehouseId);
            }

            $inventory = $this->resolveSaleInventory($product, $quantity, $warehouseId ?: null, $restore);

            if ($inventory) {
                if (!$restore && $inventory->availableToSell() < $quantity) {
                    throw ValidationException::withMessages([
                        'sale_items' => ['Sale quantity exceeds available stock for ' . $product->name . '.'],
                    ]);
                }

                if ($restore) {
                    $inventory->increment('quantity_in_stock', $quantity);
                } else {
                    $inventory->decrement('quantity_in_stock', $quantity);
                }

                $product->syncLegacyStockFields();
                $resolvedWarehouseId = (int) ($inventory->warehouse_id ?: $resolvedWarehouseId);
            } else {
                if ($restore) {
                    $product->increment('available_quantity', $quantity);
                } else {
                    if ((int) $product->available_quantity < $quantity) {
                        throw ValidationException::withMessages([
                            'sale_items' => ['Sale quantity exceeds available stock for ' . $product->name . '.'],
                        ]);
                    }

                    $product->decrement('available_quantity', $quantity);
                }
            }
        }

        if ($restore) {
            $sale->saleUnits()->sync([]);
            $this->updateSaleStockState($sale, false, $resolvedWarehouseId);

            return;
        }

        $sale->saleUnits()->sync(collect($trackedSaleUnitIds)->unique()->mapWithKeys(fn ($assetId) => [
            $assetId => ['organization_id' => $this->orgId()],
        ])->all());

        $this->updateSaleStockState($sale, true, $resolvedWarehouseId);
    }

    private function applySaleStock(Sale $sale): void
    {
        $this->adjustSaleStock($sale, false);
    }

    private function restoreSaleStock(Sale $sale): void
    {
        $this->adjustSaleStock($sale, true);
    }

    private function validateLinkedSaleReferences(Request $request, Customer $customer, array $saleItems, ?Sale $currentSale = null): void
    {
        foreach ($saleItems as $index => $line) {
            if (empty($line['asset_id'])) {
                continue;
            }

            $asset = Asset::query()
                ->where('organization_id', $this->orgId())
                ->findOrFail((int) $line['asset_id']);

            if ((int) $asset->product_id !== (int) $line['product_id']) {
                throw ValidationException::withMessages([
                    "sale_items.$index.asset_id" => ['Selected asset does not belong to the chosen product.'],
                ]);
            }

            if ($asset->asset_stage !== Asset::STAGE_NEW_STOCK) {
                throw ValidationException::withMessages([
                    "sale_items.$index.asset_id" => ['Only new stock assets can be linked to a sale.'],
                ]);
            }

            $isCurrentSaleAsset = $currentSale
                && ((int) $currentSale->asset_id === (int) $asset->id
                    || $currentSale->displaySaleItems()->pluck('asset_id')->contains((int) $asset->id)
                    || $currentSale->displaySaleItems()->pluck('asset_ids')->flatten()->contains((int) $asset->id));

            if ($asset->asset_status !== 'available_for_sale' && !$isCurrentSaleAsset) {
                throw ValidationException::withMessages([
                    "sale_items.$index.asset_id" => ['Selected asset is not available for sale.'],
                ]);
            }

            if ((int) $line['quantity'] !== 1) {
                throw ValidationException::withMessages([
                    "sale_items.$index.quantity" => ['Quantity must be 1 when a serialized asset is linked.'],
                ]);
            }
        }

        if ($request->filled('rental_id')) {
            $rental = Rental::query()
                ->where('organization_id', $this->orgId())
                ->findOrFail($request->integer('rental_id'));

            if ((int) $rental->customer_id !== (int) $customer->id) {
                throw ValidationException::withMessages([
                    'rental_id' => 'Linked rental must belong to the selected customer.',
                ]);
            }
        }
    }

    private function synchronizeLinkedRentalContext(Request $request): void
    {
        if (! $request->filled('rental_id')) {
            return;
        }

        $rental = Rental::query()
            ->where('organization_id', $this->orgId())
            ->find($request->integer('rental_id'));

        if (! $rental || ! $rental->customer_id) {
            return;
        }

        $request->merge([
            'customer_id' => $rental->customer_id,
        ]);
    }

    private function attachLinkedInvoiceIds($sales)
    {
        $saleIds = $sales->pluck('id')->filter()->map(fn ($id) => (int) $id)->values();

        if ($saleIds->isEmpty()) {
            return $sales;
        }

        $invoiceMap = Invoice::query()
            ->whereIn('id', (clone $this->saleInvoiceLookupQuery($saleIds->all()))->select('id'))
            ->with(['items' => function ($itemQuery) use ($saleIds) {
                $itemQuery
                    ->where('source_type', 'sale')
                    ->whereIn('source_id', $saleIds->all());
            }])
            ->orderByDesc('id')
            ->get()
            ->reduce(function ($carry, $invoice) {
                $directSaleId = $this->hasInvoiceSaleColumn()
                    ? (int) ($invoice->sale_id ?? 0)
                    : 0;

                if ($directSaleId > 0 && !isset($carry[$directSaleId])) {
                    $carry[$directSaleId] = (int) $invoice->id;
                }

                foreach ($invoice->items as $item) {
                    $saleId = (int) ($item->source_id ?? 0);

                    if ($saleId > 0 && !isset($carry[$saleId])) {
                        $carry[$saleId] = (int) $invoice->id;
                    }
                }

                return $carry;
            }, []);

        $sales->each(function ($sale) use ($invoiceMap) {
            $sale->setAttribute('linked_invoice_id', $invoiceMap[(int) $sale->id] ?? null);
        });

        return $sales;
    }

    private function salesReceivablesSnapshot($salesQuery): array
    {
        return $this->salesMetrics()->receivablesSnapshot(
            $salesQuery,
            $this->orgId(),
            $this->hasInvoiceSaleColumn()
        );
    }

    public function index(Request $request)
    {
        $this->authorize('viewAny', Sale::class);

        $search = trim((string) $request->get('search', ''));
        $customerId = $request->get('customer_id', '');
        $paymentStatus = (string) $request->get('payment_status', '');
        $fromDate = trim((string) $request->get('from_date', $request->get('date', '')));
        $toDate = trim((string) $request->get('to_date', $request->get('date', '')));
        $sortBy = (string) $request->get('sort_by', 'latest');

        $applyIndexFilters = function ($query) use ($customerId, $paymentStatus, $search, $fromDate, $toDate) {
            $query
                ->when($customerId !== '', fn ($innerQuery) => $innerQuery->where('customer_id', $customerId))
                ->when($paymentStatus !== '', fn ($innerQuery) => $innerQuery->where('payment_status', $paymentStatus))
                ->when($search !== '', function ($innerQuery) use ($search) {
                    $innerQuery->where(function ($nestedQuery) use ($search) {
                        $nestedQuery->whereHas('customer', function ($customerQuery) use ($search) {
                            $customerQuery->where('name', 'like', '%' . $search . '%')
                                ->orWhere('phone', 'like', '%' . $search . '%')
                                ->orWhere('email', 'like', '%' . $search . '%');

                            if (Customer::hasWhatsappNumberColumn()) {
                                $customerQuery->orWhere('whatsapp_number', 'like', '%' . $search . '%');
                            }
                        })->orWhereHas('product', function ($productQuery) use ($search) {
                            $productQuery->where('name', 'like', '%' . $search . '%');
                        })->orWhere('notes', 'like', '%' . $search . '%');
                    });
                });

            $this->applyDateRangeFilter($query, $fromDate, $toDate);

            return $query;
        };

        $salesQuery = $applyIndexFilters($this->baseSalesQuery(true));
        $summaryQuery = $applyIndexFilters($this->baseSalesQuery(false));

        $sales = $this->applySorting(clone $salesQuery, $sortBy)
            ->paginate(20)
            ->withQueryString();

        $this->attachLinkedInvoiceIds($sales->getCollection());

        $salesSummary = $this->salesMetrics()->summary(
            $summaryQuery,
            $this->orgId(),
            $this->hasInvoiceSaleColumn()
        );
        $totalSales = (int) ($salesSummary['totalSales'] ?? 0);
        $paidSales = (int) ($salesSummary['paidSalesCount'] ?? 0);
        $pendingSales = (int) ($salesSummary['pendingSalesCount'] ?? 0);
        $totalSalesAmount = (float) ($salesSummary['totalSalesAmount'] ?? 0);
        $totalTransportationAmount = (float) ($salesSummary['totalTransportationAmount'] ?? 0);
        $totalSaleValue = (float) ($salesSummary['totalSaleValue'] ?? 0);
        $paidSalesAmount = (float) ($salesSummary['paidSalesAmount'] ?? 0);
        $pendingSalesAmount = (float) ($salesSummary['pendingSalesAmount'] ?? 0);
        $outstandingInvoiceAmount = (float) ($salesSummary['outstandingInvoiceAmount'] ?? 0);
        $outstandingInvoiceCount = (int) ($salesSummary['outstandingInvoiceCount'] ?? 0);
        $unbilledSalesAmount = (float) ($salesSummary['unbilledSalesAmount'] ?? 0);
        $unbilledSalesCount = (int) ($salesSummary['unbilledSalesCount'] ?? 0);
        $totalPendingSalesAmount = (float) ($salesSummary['totalPendingSalesAmount'] ?? 0);

        $customers = Customer::where('organization_id', $this->orgId())
            ->orderBy('name')
            ->get(['id', 'name']);

        return view('sales.index', compact(
            'sales',
            'customers',
            'search',
            'customerId',
            'paymentStatus',
            'fromDate',
            'toDate',
            'sortBy',
            'totalSales',
            'paidSales',
            'pendingSales',
            'totalSalesAmount',
            'paidSalesAmount',
            'pendingSalesAmount',
            'totalTransportationAmount',
            'totalSaleValue',
            'outstandingInvoiceAmount',
            'outstandingInvoiceCount',
            'unbilledSalesAmount',
            'unbilledSalesCount',
            'totalPendingSalesAmount'
        ));
    }

    public function show(Sale $sale)
    {
        $sale = $this->scopedSale($sale);
        $this->authorize('view', $sale);
        $relations = ['customer', 'product', 'asset.warehouse', 'rental.customer', 'rental.product'];

        if ($this->hasSaleItemsTable()) {
            $relations[] = 'saleItems.product';
            $relations[] = 'saleItems.asset.warehouse';
            $relations[] = 'saleItems.warehouse';
        }

        if ($this->hasDeliverySaleColumn()) {
            $relations[] = 'deliveryRecord.assignedStaff';
            $relations[] = 'deliveryRecord.assignedUser';
        }

        $sale->load($relations);
        $saleInvoice = $this->saleInvoice($sale);
        $saleInvoice?->load(['payments.customer', 'payments.rental.product']);
        $sale->setAttribute('linked_invoice_id', $saleInvoice?->id);
        $activityLogs = ActivityLogger::recentFor($sale);

        return view('sales.show', compact('sale', 'saleInvoice', 'activityLogs'));
    }

    public function create()
    {
        $this->authorize('create', Sale::class);

        $customers = Customer::where('organization_id', $this->orgId())->orderBy('name')->get();
        $products = Product::where('organization_id', $this->orgId())
            ->orderBy('name')
            ->get()
            ->filter(fn (Product $product) => $product->canSell())
            ->values();
        $assets = Asset::query()
            ->with(['product', 'warehouse'])
            ->where('organization_id', $this->orgId())
            ->where('asset_stage', Asset::STAGE_NEW_STOCK)
            ->where('asset_status', 'available_for_sale')
            ->orderBy('serial_number')
            ->get();
        $rentals = Rental::query()
            ->with(['customer', 'product'])
            ->where('organization_id', $this->orgId())
            ->latest('id')
            ->get();

        return view('sales.create', compact('customers', 'products', 'assets', 'rentals'));
    }

    public function store(Request $request)
    {
        $this->authorize('create', Sale::class);

        $this->synchronizeLinkedRentalContext($request);
        $request->validate($this->saleValidationRules());
        $saleItems = $this->normalizedSaleItems($request);

        $customer = Customer::where('organization_id', $this->orgId())->findOrFail($request->customer_id);
        $this->validateLinkedSaleReferences($request, $customer, $saleItems);
        $commercials = $this->aggregateSaleCommercials($saleItems);
        $salePayload = $this->saleSummaryPayload($request, $customer, $saleItems, $commercials);

        if ($this->hasCreatedByColumn()) {
            $salePayload['created_by'] = auth()->id();
        }

        if ($this->hasCreatedByUserColumn()) {
            $salePayload['created_by_user_id'] = auth()->id();
        }

        [$sale, $invoice] = DB::transaction(function () use ($salePayload, $saleItems) {
            $sale = Sale::create($salePayload);
            $this->syncSaleItems($sale, $saleItems);
            $this->applySaleStock($sale);
            $invoice = $this->createSaleInvoice($sale);

            return [$sale, $invoice];
        });

        ActivityLogger::log('sale.created', $sale, [
            'invoice_id' => $invoice->id,
            'invoice_number' => $invoice->invoice_number,
            'sale_amount' => $sale->sale_amount,
            'payment_status' => $sale->payment_status,
            'tax_calculation_mode' => $sale->tax_calculation_mode ?? null,
        ], 'Sale created and invoice generated.');

        return redirect()
            ->route('sales.index')
            ->with('success', 'Sale created successfully. Invoice ' . $invoice->invoice_number . ' was created automatically.');
    }

    public function importSaleFromPayload(array $attributes): array
    {
        $customer = Customer::where('organization_id', $this->orgId())->findOrFail((int) $attributes['customer_id']);
        $product = Product::where('organization_id', $this->orgId())->findOrFail((int) $attributes['product_id']);
        $match = $this->describeImportedSaleMatch(
            $this->importMatchSignatureService()->sale(
                $attributes,
                $customer->id,
                $product->id,
                max((int) ($attributes['quantity'] ?? 0), 1),
                $this->hasWarehouseColumn() && !empty($attributes['warehouse_id'])
                    ? (int) $attributes['warehouse_id']
                    : null
            )
        );

        if (($match['action'] ?? null) === 'review') {
            throw ValidationException::withMessages([
                'import' => [$match['message'] ?? 'This sales import row requires manual review.'],
            ]);
        }

        $commercials = $this->calculateSaleCommercials(
            (float) $attributes['quantity'],
            (float) $attributes['unit_price'],
            (float) ($attributes['discount_amount'] ?? 0),
            (float) ($attributes['shipping_charges'] ?? 0),
            (float) ($attributes['tax_percentage'] ?? 0),
            (string) ($attributes['tax_calculation_mode'] ?? 'exclusive')
        );

        $salePayload = [
            'customer_id' => $customer->id,
            'product_id' => $product->id,
            'asset_id' => $attributes['asset_id'] ?? null,
            'rental_id' => $attributes['rental_id'] ?? null,
            'quantity' => $attributes['quantity'],
            'unit_price' => $attributes['unit_price'],
            'discount_amount' => $attributes['discount_amount'] ?? 0,
            'shipping_charges' => $attributes['shipping_charges'] ?? 0,
            'tax_percentage' => $attributes['tax_percentage'] ?? 0,
            'tax_calculation_mode' => $attributes['tax_calculation_mode'] ?? 'exclusive',
            'sale_date' => $attributes['sale_date'],
            'sale_amount' => $commercials['sale_amount'],
            'payment_status' => in_array(($attributes['payment_status'] ?? 'pending'), ['paid', 'partial'], true)
                ? 'pending'
                : ($attributes['payment_status'] ?? 'pending'),
            'notes' => $attributes['notes'] ?? null,
            'organization_id' => $this->orgId(),
        ];

        if ($this->hasWarehouseColumn() && !empty($attributes['warehouse_id'])) {
            $salePayload['warehouse_id'] = (int) $attributes['warehouse_id'];
        }

        if ($this->hasCreatedByColumn()) {
            $salePayload['created_by'] = auth()->id();
        }

        if ($this->hasCreatedByUserColumn()) {
            $salePayload['created_by_user_id'] = auth()->id();
        }

        if ($existingSale = ($match['sale'] ?? null)) {
            [$sale, $invoice, $delivery] = $this->updateImportedSaleFromPayload($existingSale, $salePayload, $attributes);
            $action = 'updated';
        } else {
            [$sale, $invoice, $delivery] = $this->createImportedSaleFromPayload($salePayload, $attributes);
            $action = 'created';
        }

        try {
            ActivityLogger::log('sale.imported', $sale, [
                'invoice_id' => $invoice?->id,
                'invoice_number' => $invoice?->invoice_number,
                'delivery_id' => $delivery?->id,
                'sale_amount' => $sale->sale_amount,
                'payment_status' => $sale->payment_status,
                'import_action' => $action,
            ], 'Sale imported via sales import preview.');
        } catch (\Throwable) {
            // Keep import success independent from optional activity logging.
        }

        return [
            'sale' => $sale,
            'invoice' => $invoice,
            'delivery' => $delivery,
            'action' => $action,
        ];
    }

    public function describeImportedSaleMatch(array $attributes): array
    {
        $customerId = (int) ($attributes['customer_id'] ?? 0);
        $productId = (int) ($attributes['product_id'] ?? 0);
        $quantity = max((int) ($attributes['quantity'] ?? 0), 1);
        $saleDate = $attributes['sale_date'] ?? null;
        $warehouseId = !empty($attributes['warehouse_id']) ? (int) $attributes['warehouse_id'] : null;

        if ($customerId <= 0 || $productId <= 0 || blank($saleDate)) {
            return ['action' => 'create', 'sale' => null, 'message' => null];
        }

        $candidates = Sale::query()
            ->where('organization_id', $this->orgId())
            ->where('customer_id', $customerId)
            ->where('product_id', $productId)
            ->whereDate('sale_date', $saleDate)
            ->where('quantity', $quantity)
            ->when($this->hasWarehouseColumn() && $warehouseId, fn ($query) => $query->where('warehouse_id', $warehouseId))
            ->with(['invoice.payments'])
            ->get();

        if ($candidates->isEmpty()) {
            return ['action' => 'create', 'sale' => null, 'message' => null];
        }

        if ($candidates->count() > 1) {
            return [
                'action' => 'review',
                'sale' => null,
                'message' => 'Multiple sales match this import row. Add a unique external reference or review manually.',
            ];
        }

        $sale = $candidates->first();
        $invoice = $sale?->invoice ?? $this->saleInvoice($sale);
        $paymentReview = $invoice ? $this->importedSalePaymentReviewMessage($sale, $invoice, $attributes) : null;

        if ($paymentReview) {
            return [
                'action' => 'review',
                'sale' => $sale,
                'message' => $paymentReview,
            ];
        }

        return ['action' => 'update', 'sale' => $sale, 'message' => null];
    }

    private function createImportedSaleFromPayload(array $salePayload, array $attributes): array
    {
        return $this->saleImportExecutor()->createImportedSale($salePayload, $attributes, [
            'organization_id' => $this->orgId(),
            'has_delivery_sale_column' => $this->hasDeliverySaleColumn(),
            'has_delivery_assignment_type_column' => Schema::hasColumn('deliveries', 'assignment_type'),
            'apply_sale_stock' => fn (Sale $sale) => $this->applySaleStock($sale),
            'create_sale_invoice' => fn (Sale $sale) => $this->createSaleInvoice($sale),
            'import_field_was_provided' => fn (array $row, string $field) => $this->importFieldWasProvided($row, $field),
            'managed_imported_payment_query' => fn (Invoice $invoice, int $saleId) => $this->managedImportedSalePaymentQuery($invoice, $saleId),
            'imported_payment_note' => fn (int $saleId) => $this->importedSalePaymentNote($saleId),
            'create_invoice_payment' => fn (Sale $sale, Invoice $invoice, array $payload) => $this->createInvoicePaymentForSale($sale, $invoice, $payload),
            'sync_sale_payment_status_from_invoice' => fn (Sale $sale, Invoice $invoice) => $this->syncSalePaymentStatusFromInvoice($sale, $invoice),
            'has_warehouse_column' => $this->hasWarehouseColumn(),
            'sale_invoice' => fn (Sale $sale) => $this->saleInvoice($sale),
            'sync_sale_invoice_from_sale' => fn (Sale $sale, Invoice $invoice) => $this->syncSaleInvoiceFromSale($sale, $invoice),
        ]);
    }

    private function updateImportedSaleFromPayload(Sale $sale, array $salePayload, array $attributes): array
    {
        return $this->saleImportExecutor()->updateImportedSale($sale, $salePayload, $attributes, [
            'organization_id' => $this->orgId(),
            'has_delivery_sale_column' => $this->hasDeliverySaleColumn(),
            'has_delivery_assignment_type_column' => Schema::hasColumn('deliveries', 'assignment_type'),
            'import_field_was_provided' => fn (array $row, string $field) => $this->importFieldWasProvided($row, $field),
            'managed_imported_payment_query' => fn (Invoice $invoice, int $saleId) => $this->managedImportedSalePaymentQuery($invoice, $saleId),
            'imported_payment_note' => fn (int $saleId) => $this->importedSalePaymentNote($saleId),
            'create_invoice_payment' => fn (Sale $saleRecord, Invoice $invoice, array $payload) => $this->createInvoicePaymentForSale($saleRecord, $invoice, $payload),
            'sync_sale_payment_status_from_invoice' => fn (Sale $saleRecord, Invoice $invoice) => $this->syncSalePaymentStatusFromInvoice($saleRecord, $invoice),
            'has_warehouse_column' => $this->hasWarehouseColumn(),
            'sale_invoice' => fn (Sale $saleRecord) => $this->saleInvoice($saleRecord),
            'create_sale_invoice' => fn (Sale $saleRecord) => $this->createSaleInvoice($saleRecord),
            'sync_sale_invoice_from_sale' => fn (Sale $saleRecord, Invoice $invoice) => $this->syncSaleInvoiceFromSale($saleRecord, $invoice),
        ]);
    }

    private function shouldCreateImportedSaleInvoice(array $attributes): bool
    {
        return $this->saleImportExecutor()->shouldCreateImportedSaleInvoice($attributes);
    }

    private function applyImportedSalePaymentState(Sale $sale, Invoice $invoice, array $attributes): void
    {
        $this->saleImportExecutor()->applyImportedSalePaymentState($sale, $invoice, $attributes, [
            'import_field_was_provided' => fn (array $row, string $field) => $this->importFieldWasProvided($row, $field),
            'managed_imported_payment_query' => fn (Invoice $linkedInvoice, int $saleId) => $this->managedImportedSalePaymentQuery($linkedInvoice, $saleId),
            'imported_payment_note' => fn (int $saleId) => $this->importedSalePaymentNote($saleId),
            'create_invoice_payment' => fn (Sale $saleRecord, Invoice $linkedInvoice, array $payload) => $this->createInvoicePaymentForSale($saleRecord, $linkedInvoice, $payload),
            'sync_sale_payment_status_from_invoice' => fn (Sale $saleRecord, Invoice $linkedInvoice) => $this->syncSalePaymentStatusFromInvoice($saleRecord, $linkedInvoice),
        ]);
    }

    private function applyImportedSaleDeliveryState(Sale $sale, array $attributes, bool $isUpdate = false): ?Delivery
    {
        return $this->saleImportExecutor()->applyImportedSaleDeliveryState(
            $sale,
            $attributes,
            $isUpdate,
            $this->orgId(),
            $this->hasDeliverySaleColumn(),
            Schema::hasColumn('deliveries', 'assignment_type')
        );
    }

    private function managedImportedSalePaymentQuery(Invoice $invoice, int $saleId)
    {
        return Payment::query()
            ->where('organization_id', $this->orgId())
            ->where('invoice_id', $invoice->id)
            ->where('notes', $this->importedSalePaymentNote($saleId));
    }

    private function importedSalePaymentNote(int $saleId): string
    {
        return 'Imported payment sync for sale #'.$saleId.'.';
    }

    private function importedSalePaymentReviewMessage(Sale $sale, Invoice $invoice, array $attributes): ?string
    {
        $statusProvided = $this->importFieldWasProvided($attributes, 'payment_status');
        $paidAmountProvided = $this->importFieldWasProvided($attributes, 'paid_amount');

        if (!$statusProvided && !$paidAmountProvided) {
            return null;
        }

        $paymentStatus = strtolower(trim((string) ($attributes['payment_status'] ?? 'pending')));
        $requestedPaidAmount = match ($paymentStatus) {
            'paid' => round((float) ($attributes['sale_amount'] ?? $sale->sale_amount), 2),
            'partial' => round((float) ($attributes['paid_amount'] ?? 0), 2),
            default => 0.0,
        };

        $managedPayment = $this->managedImportedSalePaymentQuery($invoice, $sale->id)->first();
        $historicalPaymentsTotal = (float) $invoice->payments()
            ->when($managedPayment, fn ($query) => $query->whereKeyNot($managedPayment->id))
            ->sum('amount');

        if ($requestedPaidAmount + 0.01 < $historicalPaymentsTotal) {
            return 'Existing recorded payments exceed the imported payment state for this sale. Review this row manually.';
        }

        return null;
    }

    private function importFieldWasProvided(array $attributes, string $field): bool
    {
        return (bool) ($attributes[$field.'_provided'] ?? false);
    }

    public function edit(Sale $sale)
    {
        $sale = $this->scopedSale($sale);
        $this->authorize('update', $sale);

        if ($this->isAutoGeneratedRentalSale($sale)) {
            return $this->managedRentalSaleRedirect($sale);
        }

        $currentSaleAssetIds = $this->hasSaleItemsTable()
            ? $sale->displaySaleItems()
                ->pluck('asset_ids')
                ->flatten()
                ->merge($sale->displaySaleItems()->pluck('asset_id'))
                ->filter()
                ->map(fn ($assetId) => (int) $assetId)
                ->unique()
                ->values()
                ->all()
            : [];
        $currentSaleProductIds = $this->hasSaleItemsTable()
            ? $sale->displaySaleItems()
                ->pluck('product_id')
                ->filter()
                ->map(fn ($productId) => (int) $productId)
                ->unique()
                ->values()
                ->all()
            : [(int) $sale->product_id];

        $customers = Customer::where('organization_id', $this->orgId())->orderBy('name')->get();
        $products = Product::where('organization_id', $this->orgId())
            ->orderBy('name')
            ->get()
            ->filter(function (Product $product) use ($currentSaleProductIds) {
                return $product->canSell() || in_array((int) $product->id, $currentSaleProductIds, true);
            })
            ->values();
        $assets = Asset::query()
            ->with(['product', 'warehouse'])
            ->where('organization_id', $this->orgId())
            ->where('asset_stage', Asset::STAGE_NEW_STOCK)
            ->where(function ($query) use ($sale, $currentSaleAssetIds) {
                $query->where('asset_status', 'available_for_sale');

                if ($sale->asset_id) {
                    $query->orWhere('id', $sale->asset_id);
                }

                if (!empty($currentSaleAssetIds)) {
                    $query->orWhereIn('id', $currentSaleAssetIds);
                }
            })
            ->orderBy('serial_number')
            ->get();
        $rentals = Rental::query()
            ->with(['customer', 'product'])
            ->where('organization_id', $this->orgId())
            ->latest('id')
            ->get();

        if ($this->hasSaleItemsTable()) {
            $sale->loadMissing(['saleItems.product', 'saleItems.asset.warehouse', 'saleItems.warehouse']);
        }

        return view('sales.edit', compact('sale', 'customers', 'products', 'assets', 'rentals'));
    }

    public function update(Request $request, Sale $sale)
    {
        $sale = $this->scopedSale($sale);
        $this->authorize('update', $sale);

        if ($this->isAutoGeneratedRentalSale($sale)) {
            return $this->managedRentalSaleRedirect($sale);
        }

        $this->synchronizeLinkedRentalContext($request);
        $request->validate($this->saleValidationRules($sale));
        $saleItems = $this->normalizedSaleItems($request, $sale);

        $customer = Customer::where('organization_id', $this->orgId())->findOrFail($request->customer_id);
        $this->validateLinkedSaleReferences($request, $customer, $saleItems, $sale);
        $commercials = $this->aggregateSaleCommercials($saleItems);

        $linkedInvoice = $this->saleInvoice($sale->loadMissing(['customer', 'product']));
        if ($linkedInvoice) {
            app(AmountReductionGuardService::class)->assertTotalNotBelowReceivedPayments(
                $linkedInvoice,
                (float) ($commercials['sale_amount'] ?? 0),
                'This sale update'
            );
        }

        DB::transaction(function () use ($sale, $customer, $request, $commercials, $saleItems) {
            $originalSale = Sale::query()
                ->with(['product', 'asset', 'saleItems.product', 'saleItems.asset'])
                ->where('organization_id', $this->orgId())
                ->findOrFail($sale->id);

            if ($this->saleUsesAppliedStock($originalSale)) {
                $this->restoreSaleStock($originalSale);
            }

            $sale->update($this->saleSummaryPayload($request, $customer, $saleItems, $commercials));
            $this->syncSaleItems($sale, $saleItems);

            if ($sale->payment_status !== 'void') {
                $this->applySaleStock($sale->fresh(['product', 'asset', 'saleItems.product', 'saleItems.asset']));
            } elseif ($this->hasStockAppliedColumn()) {
                $sale->forceFill(['stock_applied' => false])->saveQuietly();
            }

            if ($invoice = $this->saleInvoice($sale->refresh())) {
                $this->syncSaleInvoiceFromSale($sale, $invoice);
                $this->syncExistingSaleInvoicePayment($sale, $invoice);
            }
        });

        ActivityLogger::log('sale.updated', $sale->refresh(), [
            'sale_amount' => $sale->sale_amount,
            'payment_status' => $sale->payment_status,
            'tax_calculation_mode' => $sale->tax_calculation_mode ?? null,
        ], 'Sale updated.');

        return redirect()->route('sales.index')->with('success', 'Sale updated successfully.');
    }

    public function generateInvoice(Sale $sale)
    {
        $sale = $this->scopedSale($sale);

        $invoice = $this->createSaleInvoice($sale);

        ActivityLogger::log('sale.invoice.generated', $invoice, [
            'sale_id' => $sale->id,
            'invoice_number' => $invoice->invoice_number,
            'total_amount' => $invoice->total_amount,
            'payment_status' => $invoice->payment_status,
        ], 'Sale invoice generated.');

        return redirect()->route('invoices.show', $invoice)->with('success', 'Sale invoice is ready.');
    }

    public function markPaid(Sale $sale)
    {
        $sale = $this->scopedSale($sale);
        $invoice = $this->createSaleInvoice($sale);
        $invoice->syncFinancialStatus();

        if ((float) $invoice->balance_amount <= 0) {
            $this->syncSalePaymentStatusFromInvoice($sale, $invoice);

            return redirect()->route('sales.show', $sale)->with('success', 'Sale invoice is already settled.');
        }

        DB::transaction(function () use ($sale, $invoice) {
            $payment = $this->createInvoicePaymentForSale($sale, $invoice, [
                'payment_date' => now()->toDateString(),
                'amount' => (float) $invoice->balance_amount,
                'payment_method' => 'other',
                'notes' => 'Auto-recorded from Mark Paid action.',
            ]);

            $this->syncSalePaymentStatusFromInvoice($sale->refresh(), $invoice->refresh());

            ActivityLogger::log('sale.marked_paid', $sale, [
                'invoice_id' => $invoice->id,
                'payment_id' => $payment->id,
                'payment_amount' => $payment->amount,
            ], 'Sale marked as paid from the sale page.');
        });

        return redirect()->route('sales.show', $sale)->with('success', 'Sale marked as paid.');
    }

    public function recordPayment(Request $request, Sale $sale)
    {
        $sale = $this->scopedSale($sale);
        $validated = $this->validateQuickPayment($request);
        $invoice = $this->createSaleInvoice($sale);

        DB::transaction(function () use ($sale, $invoice, $validated) {
            $payment = $this->createInvoicePaymentForSale($sale, $invoice, $validated);
            $this->syncSalePaymentStatusFromInvoice($sale->refresh(), $invoice->refresh());

            ActivityLogger::log('sale.partial_payment_recorded', $sale, [
                'invoice_id' => $invoice->id,
                'payment_id' => $payment->id,
                'payment_amount' => $payment->amount,
                'payment_method' => $payment->payment_method,
            ], 'Sale payment recorded from the sale page.');
        });

        return redirect()->route('sales.show', $sale)->with('success', 'Sale payment recorded successfully.');
    }

    public function destroy(Sale $sale)
    {
        $sale = $this->scopedSale($sale);
        $this->authorize('delete', $sale);

        if ($this->isAutoGeneratedRentalSale($sale)) {
            return $this->managedRentalSaleRedirect($sale);
        }

        DB::transaction(function () use ($sale) {
            $sale->loadMissing(['product', 'asset']);

            if ($this->saleUsesAppliedStock($sale)) {
                $this->restoreSaleStock($sale);
            }

            $sale->delete();
        });

        return redirect()->route('sales.index')->with('success', 'Sale deleted successfully.');
    }

    public function voidSale(Sale $sale)
    {
        $sale = $this->scopedSale($sale);

        if ($this->isAutoGeneratedRentalSale($sale)) {
            return $this->managedRentalSaleRedirect($sale);
        }

        if ($sale->payment_status === 'void') {
            return redirect()->route('sales.show', $sale)->with('error', 'This sale is already voided.');
        }

        DB::transaction(function () use ($sale) {
            if ($this->saleUsesAppliedStock($sale->loadMissing(['product', 'asset']))) {
                $this->restoreSaleStock($sale);
            }

            $invoice = $this->saleInvoice($sale);

            if ($invoice) {
                $this->autoPaidSalePaymentQuery($sale, $invoice)->delete();
                $invoice->forceFill([
                    'status' => 'cancelled',
                    'payment_status' => 'cancelled',
                    'paid_amount' => (float) $invoice->payments()->sum('amount'),
                    'balance_amount' => 0,
                ])->save();
            }

            $sale->update([
                'payment_status' => 'void',
                'notes' => trim(($sale->notes ? $sale->notes . ' | ' : '') . 'Sale voided.'),
            ]);

            if ($this->hasStockAppliedColumn()) {
                $sale->forceFill(['stock_applied' => false])->saveQuietly();
            }
        });

        ActivityLogger::log('sale.voided', $sale->refresh(), [
            'payment_status' => $sale->payment_status,
        ], 'Sale voided.');

        return redirect()->route('sales.show', $sale)->with('success', 'Sale voided successfully.');
    }
}
