<?php

namespace App\Http\Controllers;

use App\Models\Asset;
use App\Models\Sale;
use App\Models\Customer;
use App\Models\Delivery;
use App\Models\Invoice;
use App\Models\Organization;
use App\Models\Payment;
use App\Models\Product;
use App\Models\Rental;
use App\Models\SaleInventory;
use App\Services\Finance\InvoiceLinkResolver;
use App\Services\Finance\InvoiceSyncService;
use App\Services\Finance\AmountReductionGuardService;
use App\Services\Finance\PaymentSyncService;
use App\Services\Imports\ImportMatchSignatureService;
use App\Services\Imports\SaleImportExecutor;
use App\Support\ActivityLogger;
use Illuminate\Http\Request;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Illuminate\Validation\ValidationException;
use Illuminate\Validation\Rule;

class SaleController extends Controller
{
    private ?bool $hasWarehouseColumn = null;
    private ?bool $hasStockAppliedColumn = null;
    private ?bool $hasAutoGeneratedFromRentalColumn = null;
    private ?bool $hasInvoiceSaleColumn = null;

    private function orgId()
    {
        return auth()->user()->organization_id;
    }

    private function saleImportExecutor(): SaleImportExecutor
    {
        return app(SaleImportExecutor::class);
    }

    private function importMatchSignatureService(): ImportMatchSignatureService
    {
        return app(ImportMatchSignatureService::class);
    }

    private function hasWarehouseColumn(): bool
    {
        return $this->hasWarehouseColumn ??= Schema::hasColumn('sales', 'warehouse_id');
    }

    private function hasStockAppliedColumn(): bool
    {
        return $this->hasStockAppliedColumn ??= Schema::hasColumn('sales', 'stock_applied');
    }

    private function hasAutoGeneratedFromRentalColumn(): bool
    {
        return $this->hasAutoGeneratedFromRentalColumn ??= Schema::hasColumn('sales', 'auto_generated_from_rental');
    }

    private function hasInvoiceSaleColumn(): bool
    {
        return $this->hasInvoiceSaleColumn ??= Schema::hasColumn('invoices', 'sale_id');
    }

    private function isAutoGeneratedRentalSale(Sale $sale): bool
    {
        return $this->hasAutoGeneratedFromRentalColumn()
            && (bool) ($sale->auto_generated_from_rental ?? false)
            && !empty($sale->rental_id);
    }

    private function managedRentalSaleRedirect(Sale $sale)
    {
        $message = 'This sale is managed from rental #' . $sale->rental_id . '. Update the linked rental new-product lines instead.';

        if ($sale->rental_id) {
            return redirect()->route('rentals.show', $sale->rental_id)->with('error', $message);
        }

        return redirect()->route('sales.show', $sale)->with('error', $message);
    }

    private function baseSalesQuery(bool $includeRelations = true)
    {
        $query = Sale::query()
            ->where('organization_id', $this->orgId());

        if ($includeRelations) {
            $relations = ['customer', 'product', 'asset.warehouse', 'rental'];

            if ($this->hasDeliverySaleColumn()) {
                $relations[] = 'deliveryRecord.assignedStaff';
                $relations[] = 'deliveryRecord.assignedUser';
            }

            $query->with($relations);
        }

        return $this->applySalesScope($query);
    }

    private function hasDeliverySaleColumn(): bool
    {
        return Schema::hasColumn('deliveries', 'sale_id');
    }

    private function hasCreatedByColumn(): bool
    {
        return Schema::hasColumn('sales', 'created_by');
    }

    private function hasCreatedByUserColumn(): bool
    {
        return Schema::hasColumn('sales', 'created_by_user_id');
    }

    private function paymentsRentalIdIsNullable(): bool
    {
        static $isNullable = null;

        if ($isNullable !== null) {
            return $isNullable;
        }

        if (DB::connection()->getDriverName() === 'sqlite') {
            $columns = DB::select("PRAGMA table_info('payments')");

            foreach ($columns as $column) {
                if (($column->name ?? null) === 'rental_id') {
                    return $isNullable = ((int) ($column->notnull ?? 1)) === 0;
                }
            }

            return $isNullable = true;
        }

        $column = DB::table('information_schema.columns')
            ->select('is_nullable')
            ->where('table_schema', DB::raw('schema()'))
            ->where('table_name', 'payments')
            ->where('column_name', 'rental_id')
            ->first();

        return $isNullable = strtoupper((string) ($column->is_nullable ?? 'NO')) === 'YES';
    }

    private function applySalesScope($query)
    {
        $user = auth()->user();

        if (!$user || !$user->hasScope('self_created', 'sales')) {
            return $query;
        }

        if ($this->hasCreatedByUserColumn()) {
            return $query->where('created_by_user_id', $user->id);
        }

        if ($this->hasCreatedByColumn()) {
            return $query->where('created_by', $user->id);
        }

        return $query;
    }

    private function scopedSale(Sale $sale): Sale
    {
        abort_if($sale->organization_id !== $this->orgId(), 403);

        $user = auth()->user();

        if ($user && $user->hasScope('self_created', 'sales')) {
            $owned = true;

            if ($this->hasCreatedByUserColumn()) {
                $owned = (int) $sale->created_by_user_id === (int) $user->id;
            } elseif ($this->hasCreatedByColumn()) {
                $owned = (int) $sale->created_by === (int) $user->id;
            }

            abort_if(!$owned, 403);
        }

        return $sale;
    }

    private function applyDateRangeFilter($query, string $fromDate, string $toDate)
    {
        if ($fromDate !== '') {
            $query->whereDate('sale_date', '>=', $fromDate);
        }

        if ($toDate !== '') {
            $query->whereDate('sale_date', '<=', $toDate);
        }

        return $query;
    }

    private function applySorting($query, string $sortBy)
    {
        return match ($sortBy) {
            'oldest' => $query->orderBy('sale_date')->orderBy('id'),
            'priority' => $query->orderByRaw("CASE WHEN payment_status IN ('pending', 'partial') THEN 0 ELSE 1 END")
                ->orderByDesc('sale_amount')
                ->orderByDesc('sale_date'),
            'amount_desc' => $query->orderByDesc('sale_amount')->orderByDesc('sale_date'),
            'amount_asc' => $query->orderBy('sale_amount')->orderByDesc('sale_date'),
            'customer_asc' => $query->leftJoin('customers', 'sales.customer_id', '=', 'customers.id')
                ->select('sales.*')
                ->orderBy('customers.name')
                ->orderByDesc('sales.sale_date'),
            'customer_desc' => $query->leftJoin('customers', 'sales.customer_id', '=', 'customers.id')
                ->select('sales.*')
                ->orderByDesc('customers.name')
                ->orderByDesc('sales.sale_date'),
            default => $query->orderByDesc('sale_date')->orderByDesc('id'),
        };
    }

    private function latestInvoiceIdForSale(int $saleId): ?int
    {
        return $this->saleInvoiceLookupQuery([$saleId])
            ->latest('id')
            ->value('id');
    }

    private function saleInvoice(Sale $sale): ?Invoice
    {
        return app(InvoiceLinkResolver::class)->saleInvoice(
            $sale,
            $this->orgId(),
            $this->hasInvoiceSaleColumn()
        );
    }

    private function saleInvoiceLookupQuery(array $saleIds)
    {
        return app(InvoiceLinkResolver::class)->saleInvoiceLookupQuery(
            $this->orgId(),
            $saleIds,
            $this->hasInvoiceSaleColumn()
        );
    }

    private function nextInvoiceNumber(): string
    {
        return 'INV-' . str_pad((Invoice::max('id') ?? 0) + 1, 6, '0', STR_PAD_LEFT);
    }

    private function normalizeStateName(?string $value): ?string
    {
        $normalized = strtolower(trim((string) $value));

        return $normalized !== '' ? $normalized : null;
    }

    private function calculateSaleCommercials(
        float $quantity,
        float $unitPrice,
        float $discountAmount,
        float $shippingCharges,
        float $taxPercentage,
        string $taxCalculationMode
    ): array {
        $quantity = max($quantity, 1);
        $unitPrice = max($unitPrice, 0);
        $discountAmount = max($discountAmount, 0);
        $shippingCharges = max($shippingCharges, 0);
        $taxPercentage = max($taxPercentage, 0);
        $taxCalculationMode = $taxCalculationMode === 'inclusive' ? 'inclusive' : 'exclusive';

        $subtotal = round($quantity * $unitPrice, 2);
        $taxableBase = max($subtotal - $discountAmount, 0);

        if ($taxCalculationMode === 'inclusive' && $taxPercentage > 0) {
            $taxableAmount = round($taxableBase / (1 + ($taxPercentage / 100)), 2);
            $totalTaxAmount = round($taxableBase - $taxableAmount, 2);
        } else {
            $taxableAmount = $taxableBase;
            $totalTaxAmount = round(($taxableAmount * $taxPercentage) / 100, 2);
        }

        $saleAmount = round($taxableBase + ($taxCalculationMode === 'exclusive' ? $totalTaxAmount : 0) + $shippingCharges, 2);

        return [
            'subtotal' => $subtotal,
            'discount_amount' => $discountAmount,
            'shipping_charges' => $shippingCharges,
            'taxable_amount' => $taxableAmount,
            'total_tax_amount' => $totalTaxAmount,
            'sale_amount' => $saleAmount,
        ];
    }

    private function createSaleInvoice(Sale $sale): Invoice
    {
        $sale->loadMissing(['customer', 'product', 'asset.warehouse', 'rental']);

        if ($existingInvoice = $this->saleInvoice($sale)) {
            $this->syncSaleInvoiceFromSale($sale, $existingInvoice);
            $this->syncExistingSaleInvoicePayment($sale, $existingInvoice);

            return $existingInvoice;
        }

        $organization = Organization::findOrFail($this->orgId());
        $taxType = $this->saleTaxType($sale, $organization);

        $commercials = $this->calculateSaleCommercials(
            (float) $sale->quantity,
            (float) ($sale->unit_price ?: 0),
            (float) ($sale->discount_amount ?: 0),
            (float) ($sale->shipping_charges ?: 0),
            (float) ($sale->tax_percentage ?: 0),
            (string) ($sale->tax_calculation_mode ?: 'exclusive')
        );

        return DB::transaction(function () use ($sale, $organization, $taxType, $commercials) {
            $invoice = app(InvoiceSyncService::class)->createSaleInvoiceFromPayload(
                $this->orgId(),
                $sale,
                $this->hasInvoiceSaleColumn(),
                $this->nextInvoiceNumber(),
                $this->saleInvoicePayload($sale, $organization, $taxType, $commercials),
                $this->saleInvoiceItemPayload($sale, $taxType, $commercials),
                $sale->payment_status === 'paid',
                auth()->id()
            );

            if ($sale->payment_status === 'paid') {
                app(PaymentSyncService::class)->recordPaidSaleInvoice(
                    $this->orgId(),
                    $sale,
                    $invoice,
                    (float) $commercials['sale_amount'],
                    $this->paymentsRentalIdIsNullable()
                );
                $invoice->refresh()->syncFinancialStatus();
            }

            return $invoice;
        });
    }

    private function saleTaxType(Sale $sale, Organization $organization): string
    {
        $customerState = $this->normalizeStateName($sale->customer?->state);
        $organizationState = $this->normalizeStateName($organization->state);

        return ($customerState && $organizationState && $customerState !== $organizationState)
            ? 'igst'
            : 'cgst_sgst';
    }

    private function saleInvoicePayload(Sale $sale, Organization $organization, string $taxType, array $commercials): array
    {
        return [
            'organization_id' => $this->orgId(),
            'invoice_date' => $sale->sale_date ?: now()->toDateString(),
            'due_date' => $sale->sale_date ?: now()->toDateString(),
            'customer_id' => $sale->customer_id,
            'bill_to_name' => $sale->customer?->name,
            'bill_to_phone' => $sale->customer?->phone,
            'bill_to_email' => $sale->customer?->email,
            'bill_to_address' => $sale->customer?->address,
            'bill_to_city' => $sale->customer?->city,
            'bill_to_state' => $sale->customer?->state,
            'bill_to_pincode' => $sale->customer?->pincode,
            'ship_to_name' => $sale->customer?->name,
            'ship_to_phone' => $sale->customer?->phone,
            'ship_to_address' => $sale->customer?->address,
            'ship_to_city' => $sale->customer?->city,
            'ship_to_state' => $sale->customer?->state,
            'ship_to_pincode' => $sale->customer?->pincode,
            'place_of_supply_state' => $sale->customer?->state,
            'tax_type' => $taxType,
            'tax_calculation_mode' => $sale->tax_calculation_mode ?: 'exclusive',
            'subtotal' => $commercials['subtotal'],
            'discount_amount' => $commercials['discount_amount'],
            'deposit_amount' => 0,
            'shipping_charges' => $commercials['shipping_charges'],
            'taxable_amount' => $commercials['taxable_amount'],
            'cgst_amount' => $taxType === 'cgst_sgst' ? round($commercials['total_tax_amount'] / 2, 2) : 0,
            'sgst_amount' => $taxType === 'cgst_sgst' ? round($commercials['total_tax_amount'] / 2, 2) : 0,
            'igst_amount' => $taxType === 'igst' ? $commercials['total_tax_amount'] : 0,
            'total_tax_amount' => $commercials['total_tax_amount'],
            'total_amount' => $commercials['sale_amount'],
            'notes' => 'Auto-generated for sale #' . $sale->id,
            'terms_conditions' => $organization->default_terms,
        ];
    }

    private function saleInvoiceItemPayload(Sale $sale, string $taxType, array $commercials): array
    {
        return [
            'product_id' => $sale->product_id,
            'source_type' => 'sale',
            'source_id' => $sale->id,
            'description' => $sale->product?->name ?? 'Sale product',
            'hsn_sac_code' => null,
            'quantity' => (float) $sale->quantity,
            'unit' => 'sale',
            'days' => null,
            'rate' => (float) ($sale->unit_price ?: 0),
            'discount_amount' => (float) ($sale->discount_amount ?: 0),
            'taxable_amount' => $commercials['taxable_amount'],
            'tax_percentage' => (float) ($sale->tax_percentage ?: 0),
            'tax_type' => $taxType,
            'cgst_rate' => $taxType === 'cgst_sgst' ? round(((float) ($sale->tax_percentage ?: 0)) / 2, 2) : 0,
            'sgst_rate' => $taxType === 'cgst_sgst' ? round(((float) ($sale->tax_percentage ?: 0)) / 2, 2) : 0,
            'igst_rate' => $taxType === 'igst' ? (float) ($sale->tax_percentage ?: 0) : 0,
            'cgst_amount' => $taxType === 'cgst_sgst' ? round($commercials['total_tax_amount'] / 2, 2) : 0,
            'sgst_amount' => $taxType === 'cgst_sgst' ? round($commercials['total_tax_amount'] / 2, 2) : 0,
            'igst_amount' => $taxType === 'igst' ? $commercials['total_tax_amount'] : 0,
            'line_total' => $commercials['sale_amount'] - (float) ($sale->shipping_charges ?: 0),
        ];
    }

    private function syncSaleInvoiceFromSale(Sale $sale, Invoice $invoice): void
    {
        $sale->loadMissing(['customer', 'product']);
        $organization = Organization::findOrFail($this->orgId());
        $taxType = $this->saleTaxType($sale, $organization);
        $commercials = $this->calculateSaleCommercials(
            (float) $sale->quantity,
            (float) ($sale->unit_price ?: 0),
            (float) ($sale->discount_amount ?: 0),
            (float) ($sale->shipping_charges ?: 0),
            (float) ($sale->tax_percentage ?: 0),
            (string) ($sale->tax_calculation_mode ?: 'exclusive')
        );

        app(InvoiceSyncService::class)->syncSaleInvoiceFromPayload(
            $invoice,
            $this->saleInvoicePayload($sale, $organization, $taxType, $commercials),
            $this->saleInvoiceItemPayload($sale, $taxType, $commercials),
            $sale->id
        );
    }

    private function recordPaidSaleInvoice(Sale $sale, Invoice $invoice, float $amount): void
    {
        app(PaymentSyncService::class)->recordPaidSaleInvoice(
            $this->orgId(),
            $sale,
            $invoice,
            $amount,
            $this->paymentsRentalIdIsNullable()
        );
    }

    private function autoPaidSalePaymentQuery(Sale $sale, Invoice $invoice)
    {
        return Payment::query()
            ->where('organization_id', $this->orgId())
            ->where('invoice_id', $invoice->id)
            ->where('notes', 'Auto-recorded from paid sale #' . $sale->id . '.');
    }

    private function syncExistingSaleInvoicePayment(Sale $sale, Invoice $invoice): void
    {
        app(PaymentSyncService::class)->syncExistingSaleInvoicePayment(
            $this->orgId(),
            $sale,
            $invoice,
            $this->paymentsRentalIdIsNullable()
        );
    }

    private function syncSalePaymentStatusFromInvoice(Sale $sale, Invoice $invoice): void
    {
        app(PaymentSyncService::class)->syncSalePaymentStatusFromInvoice($sale, $invoice);
    }

    private function validateQuickPayment(Request $request): array
    {
        return $request->validate([
            'payment_date' => 'required|date',
            'amount' => 'required|numeric|min:0.01',
            'payment_method' => 'nullable|string|max:255',
            'notes' => 'nullable|string',
        ]);
    }

    private function createInvoicePaymentForSale(Sale $sale, Invoice $invoice, array $validated): Payment
    {
        return app(PaymentSyncService::class)->createInvoicePayment(
            $this->orgId(),
            $invoice,
            $validated,
            $sale->rental_id ? (int) $sale->rental_id : null,
            $sale->rental_id || $this->paymentsRentalIdIsNullable(),
            'Payment amount cannot exceed the invoice balance due.',
            'Payment could not be recorded because the payments table still requires rental_id.'
        );
    }

    private function saleValidationRules(?Sale $sale = null): array
    {
        $saleId = $sale?->id;

        return [
            'customer_id' => [
                'required',
                Rule::exists('customers', 'id')->where(fn ($query) => $query->where('organization_id', $this->orgId())),
            ],
            'product_id' => [
                'required',
                Rule::exists('products', 'id')->where(fn ($query) => $query->where('organization_id', $this->orgId())),
            ],
            'asset_id' => [
                'nullable',
                Rule::exists('assets', 'id')->where(fn ($query) => $query->where('organization_id', $this->orgId())),
            ],
            'rental_id' => [
                'nullable',
                Rule::exists('rentals', 'id')->where(fn ($query) => $query->where('organization_id', $this->orgId())),
            ],
            'quantity' => 'required|integer|min:1',
            'unit_price' => 'required|numeric|min:0',
            'discount_amount' => 'nullable|numeric|min:0',
            'shipping_charges' => 'nullable|numeric|min:0',
            'tax_percentage' => 'nullable|numeric|min:0|max:100',
            'tax_calculation_mode' => 'required|in:exclusive,inclusive',
            'sale_date' => 'required|date',
            'sale_amount' => 'required|numeric|min:0',
            'payment_status' => 'required|in:pending,paid,partial,void',
            'notes' => 'nullable|string',
        ];
    }

    private function saleUsesAppliedStock(Sale $sale): bool
    {
        if ($this->hasStockAppliedColumn()) {
            return (bool) ($sale->stock_applied ?? false);
        }

        return ($sale->payment_status ?? 'pending') !== 'void';
    }

    private function resolveSaleInventory(Product $product, int $quantity, ?int $warehouseId = null, bool $restore = false): ?SaleInventory
    {
        $inventoryQuery = SaleInventory::query()
            ->where('organization_id', $this->orgId())
            ->where('product_id', $product->id);

        if ($warehouseId) {
            return (clone $inventoryQuery)
                ->where('warehouse_id', $warehouseId)
                ->lockForUpdate()
                ->first();
        }

        $inventories = (clone $inventoryQuery)
            ->orderBy('id')
            ->lockForUpdate()
            ->get();

        if ($inventories->isEmpty()) {
            return null;
        }

        if ($restore) {
            return $inventories->first();
        }

        return $inventories->first(fn ($inventory) => $inventory->availableToSell() >= $quantity);
    }

    private function updateSaleStockState(Sale $sale, bool $applied, ?int $warehouseId = null): void
    {
        $attributes = [];

        if ($this->hasWarehouseColumn()) {
            $attributes['warehouse_id'] = $warehouseId;
        }

        if ($this->hasStockAppliedColumn()) {
            $attributes['stock_applied'] = $applied;
        }

        if (!empty($attributes)) {
            $sale->forceFill($attributes)->saveQuietly();
        }
    }

    private function syncTrackedSaleSummary(Product $product): void
    {
        SaleInventory::syncFromSaleUnits($this->orgId(), $product->id);
        $product->refresh();
        $product->syncLegacyStockFields();
    }

    private function trackedSaleAllocationError(Product $product): ValidationException
    {
        return ValidationException::withMessages([
            'quantity' => ['Tracked sale product requires available sale asset units. Add stock or convert rental asset to sale stock first.'],
        ]);
    }

    private function trackedSaleAllocatedAssets(Sale $sale)
    {
        $sale->loadMissing('saleUnits');

        $assetIds = $sale->saleUnits
            ->pluck('id')
            ->map(fn ($assetId) => (int) $assetId)
            ->filter(fn ($assetId) => $assetId > 0)
            ->values()
            ->all();

        if (empty($assetIds) && $sale->asset_id) {
            $assetIds = [(int) $sale->asset_id];
        }

        if (empty($assetIds)) {
            return collect();
        }

        return Asset::query()
            ->where('organization_id', $this->orgId())
            ->whereIn('id', $assetIds)
            ->lockForUpdate()
            ->get()
            ->sortBy(fn ($asset) => $asset->serial_number ?: (string) $asset->id)
            ->values();
    }

    private function autoAllocateTrackedSaleAssets(Product $product, int $quantity, ?int $warehouseId = null, ?int $explicitAssetId = null)
    {
        if ($quantity <= 0) {
            return collect();
        }

        $baseQuery = Asset::query()
            ->where('organization_id', $this->orgId())
            ->where('product_id', $product->id)
            ->where('asset_stage', Asset::STAGE_NEW_STOCK);

        if ($explicitAssetId) {
            $asset = (clone $baseQuery)
                ->lockForUpdate()
                ->findOrFail($explicitAssetId);

            if ($asset->asset_status !== 'available_for_sale') {
                throw $this->trackedSaleAllocationError($product);
            }

            if ($quantity !== 1) {
                throw ValidationException::withMessages([
                    'quantity' => ['Quantity must be 1 when a serialized asset is selected for a tracked sale product.'],
                ]);
            }

            return collect([$asset]);
        }

        if ($warehouseId) {
            $assets = (clone $baseQuery)
                ->where('warehouse_id', $warehouseId)
                ->where('asset_status', 'available_for_sale')
                ->orderBy('serial_number')
                ->orderBy('id')
                ->lockForUpdate()
                ->limit($quantity)
                ->get();

            if ($assets->count() < $quantity) {
                throw $this->trackedSaleAllocationError($product);
            }

            return $assets->values();
        }

        $assets = (clone $baseQuery)
            ->where('asset_status', 'available_for_sale')
            ->orderByRaw('CASE WHEN warehouse_id IS NULL THEN 1 ELSE 0 END')
            ->orderBy('warehouse_id')
            ->orderBy('serial_number')
            ->orderBy('id')
            ->lockForUpdate()
            ->limit($quantity)
            ->get();

        if ($assets->count() < $quantity) {
            throw $this->trackedSaleAllocationError($product);
        }

        return $assets->values();
    }

    private function syncTrackedSaleUnitAssignments(Sale $sale, $assets): void
    {
        $syncPayload = $assets
            ->mapWithKeys(fn ($asset) => [
                (int) $asset->id => ['organization_id' => $this->orgId()],
            ])
            ->all();

        $sale->saleUnits()->sync($syncPayload);

        $resolvedAssetId = $assets->count() === 1 ? (int) $assets->first()->id : null;

        if ((int) ($sale->asset_id ?? 0) !== (int) ($resolvedAssetId ?? 0)) {
            $sale->forceFill([
                'asset_id' => $resolvedAssetId,
            ])->saveQuietly();
        }
    }

    private function adjustSaleStock(Sale $sale, bool $restore = false): void
    {
        $sale->loadMissing(['product', 'asset']);

        $product = Product::query()
            ->where('organization_id', $this->orgId())
            ->findOrFail($sale->product_id);

        $quantity = max((int) $sale->quantity, 1);
        $warehouseId = $this->hasWarehouseColumn() ? (int) ($sale->warehouse_id ?? 0) : 0;
        $asset = null;

        if ($product->tracksSaleStock()) {
            if ($restore) {
                $allocatedAssets = $this->trackedSaleAllocatedAssets($sale);

                foreach ($allocatedAssets as $allocatedAsset) {
                    if ($allocatedAsset->asset_stage !== Asset::STAGE_NEW_STOCK) {
                        continue;
                    }

                    $allocatedAsset->update(['asset_status' => 'available_for_sale']);
                }

                $this->syncTrackedSaleSummary($product);
                $this->updateSaleStockState(
                    $sale,
                    false,
                    $warehouseId ?: ($allocatedAssets->count() === 1 ? (int) ($allocatedAssets->first()->warehouse_id ?: 0) : null)
                );

                return;
            }

            $allocatedAssets = $this->autoAllocateTrackedSaleAssets(
                $product,
                $quantity,
                $warehouseId ?: null,
                $sale->asset_id ? (int) $sale->asset_id : null
            );

            foreach ($allocatedAssets as $allocatedAsset) {
                $allocatedAsset->update(['asset_status' => 'sold']);
            }

            $this->syncTrackedSaleUnitAssignments($sale, $allocatedAssets);
            $this->syncTrackedSaleSummary($product);

            $resolvedWarehouseId = null;

            if ($allocatedAssets->pluck('warehouse_id')->filter(fn ($warehouse) => filled($warehouse))->unique()->count() === 1) {
                $resolvedWarehouseId = (int) $allocatedAssets->pluck('warehouse_id')->first();
            } elseif ($warehouseId > 0) {
                $resolvedWarehouseId = $warehouseId;
            }

            $this->updateSaleStockState($sale, true, $resolvedWarehouseId);

            return;
        }

        if ($sale->asset_id) {
            $asset = Asset::query()
                ->where('organization_id', $this->orgId())
                ->lockForUpdate()
                ->findOrFail($sale->asset_id);

            if ((int) $asset->product_id !== (int) $product->id) {
                throw ValidationException::withMessages([
                    'asset_id' => 'Selected asset does not belong to the chosen product.',
                ]);
            }

            if ($asset->asset_stage !== Asset::STAGE_NEW_STOCK) {
                throw ValidationException::withMessages([
                    'asset_id' => 'Only new stock assets can be linked to a sale.',
                ]);
            }

            $warehouseId = (int) ($asset->warehouse_id ?: $warehouseId);

            if ($restore) {
                $asset->update(['asset_status' => 'available_for_sale']);
            } else {
                if ($asset->asset_status !== 'available_for_sale') {
                    throw ValidationException::withMessages([
                        'asset_id' => 'Selected asset is no longer available for sale.',
                    ]);
                }

                $asset->update(['asset_status' => 'sold']);
            }
        }

        $inventory = $this->resolveSaleInventory($product, $quantity, $warehouseId ?: null, $restore);

        if ($inventory) {
            if (!$restore && $inventory->availableToSell() < $quantity) {
                throw ValidationException::withMessages([
                    'quantity' => 'Sale quantity exceeds available stock for ' . $product->name . '.',
                ]);
            }

            if ($restore) {
                $inventory->increment('quantity_in_stock', $quantity);
            } else {
                $inventory->decrement('quantity_in_stock', $quantity);
            }

            $product->syncLegacyStockFields();
            $warehouseId = (int) $inventory->warehouse_id;
        } else {
            if ($restore) {
                $product->increment('available_quantity', $quantity);
            } else {
                if ((int) $product->available_quantity < $quantity) {
                    throw ValidationException::withMessages([
                        'quantity' => 'Sale quantity exceeds available stock for ' . $product->name . '.',
                    ]);
                }

                $product->decrement('available_quantity', $quantity);
            }
        }

        $this->updateSaleStockState($sale, !$restore, $warehouseId ?: null);
    }

    private function applySaleStock(Sale $sale): void
    {
        $this->adjustSaleStock($sale, false);
    }

    private function restoreSaleStock(Sale $sale): void
    {
        $this->adjustSaleStock($sale, true);
    }

    private function validateLinkedSaleReferences(Request $request, Product $product, Customer $customer, ?Sale $currentSale = null): void
    {
        if ($request->filled('asset_id')) {
            $asset = Asset::query()
                ->where('organization_id', $this->orgId())
                ->findOrFail($request->integer('asset_id'));

            if ((int) $asset->product_id !== (int) $product->id) {
                throw ValidationException::withMessages([
                    'asset_id' => 'Selected asset does not belong to the chosen product. Please choose an asset for ' . $product->name . '.',
                ]);
            }

            if ($asset->asset_stage !== Asset::STAGE_NEW_STOCK) {
                throw ValidationException::withMessages([
                    'asset_id' => 'Only new stock assets can be linked to a sale.',
                ]);
            }

            $isCurrentSaleAsset = $currentSale && (int) $currentSale->asset_id === (int) $asset->id;

            if ($asset->asset_status !== 'available_for_sale' && !$isCurrentSaleAsset) {
                throw ValidationException::withMessages([
                    'asset_id' => 'Selected asset is not available for sale.',
                ]);
            }

            if ((int) $request->integer('quantity') !== 1) {
                throw ValidationException::withMessages([
                    'quantity' => 'Quantity must be 1 when a serialized asset is linked.',
                ]);
            }
        }

        if ($request->filled('rental_id')) {
            $rental = Rental::query()
                ->where('organization_id', $this->orgId())
                ->findOrFail($request->integer('rental_id'));

            if ((int) $rental->customer_id !== (int) $customer->id) {
                throw ValidationException::withMessages([
                    'rental_id' => 'Linked rental must belong to the selected customer.',
                ]);
            }
        }
    }

    private function synchronizeLinkedRentalContext(Request $request): void
    {
        if (! $request->filled('rental_id')) {
            return;
        }

        $rental = Rental::query()
            ->where('organization_id', $this->orgId())
            ->find($request->integer('rental_id'));

        if (! $rental || ! $rental->customer_id) {
            return;
        }

        $request->merge([
            'customer_id' => $rental->customer_id,
        ]);
    }

    private function attachLinkedInvoiceIds($sales)
    {
        $saleIds = $sales->pluck('id')->filter()->map(fn ($id) => (int) $id)->values();

        if ($saleIds->isEmpty()) {
            return $sales;
        }

        $invoiceMap = Invoice::query()
            ->whereIn('id', (clone $this->saleInvoiceLookupQuery($saleIds->all()))->select('id'))
            ->with(['items' => function ($itemQuery) use ($saleIds) {
                $itemQuery
                    ->where('source_type', 'sale')
                    ->whereIn('source_id', $saleIds->all());
            }])
            ->orderByDesc('id')
            ->get()
            ->reduce(function ($carry, $invoice) {
                $directSaleId = $this->hasInvoiceSaleColumn()
                    ? (int) ($invoice->sale_id ?? 0)
                    : 0;

                if ($directSaleId > 0 && !isset($carry[$directSaleId])) {
                    $carry[$directSaleId] = (int) $invoice->id;
                }

                foreach ($invoice->items as $item) {
                    $saleId = (int) ($item->source_id ?? 0);

                    if ($saleId > 0 && !isset($carry[$saleId])) {
                        $carry[$saleId] = (int) $invoice->id;
                    }
                }

                return $carry;
            }, []);

        $sales->each(function ($sale) use ($invoiceMap) {
            $sale->setAttribute('linked_invoice_id', $invoiceMap[(int) $sale->id] ?? null);
        });

        return $sales;
    }

    private function salesReceivablesSnapshot($salesQuery): array
    {
        $salesCollection = (clone $salesQuery)->get(['id', 'sale_amount']);
        $saleIds = $salesCollection
            ->pluck('id')
            ->filter()
            ->map(fn ($id) => (int) $id)
            ->unique()
            ->values();

        if ($saleIds->isEmpty()) {
            return [
                'outstandingInvoiceCount' => 0,
                'outstandingInvoiceAmount' => 0.0,
                'unbilledSalesCount' => 0,
                'unbilledSalesAmount' => 0.0,
                'totalPendingSalesAmount' => 0.0,
            ];
        }

        $linkedInvoices = DB::table('invoice_items')
            ->join('invoices', 'invoices.id', '=', 'invoice_items.invoice_id')
            ->where('invoices.organization_id', $this->orgId())
            ->where('invoice_items.source_type', 'sale')
            ->whereIn('invoice_items.source_id', $saleIds->all())
            ->whereNotIn('invoices.payment_status', ['cancelled'])
            ->select([
                'invoice_items.source_id',
                'invoices.id as invoice_id',
                'invoices.payment_status',
                'invoices.balance_amount',
            ])
            ->get();

        if ($this->hasInvoiceSaleColumn()) {
            $linkedInvoices = $linkedInvoices
                ->concat(
                    Invoice::query()
                        ->where('organization_id', $this->orgId())
                        ->whereIn('sale_id', $saleIds->all())
                        ->whereNotIn('payment_status', ['cancelled'])
                        ->get([
                            'sale_id as source_id',
                            'id as invoice_id',
                            'payment_status',
                            'balance_amount',
                        ])
                )
                ->unique(fn ($invoice) => ((int) $invoice->invoice_id).':'.((int) $invoice->source_id));
        }

        $linkedSaleIds = $linkedInvoices
            ->pluck('source_id')
            ->map(fn ($id) => (int) $id)
            ->unique();

        $outstandingInvoices = $linkedInvoices
            ->filter(fn ($invoice) => in_array($invoice->payment_status, ['unpaid', 'partial', 'overdue'], true))
            ->unique('invoice_id');

        $outstandingInvoiceAmount = round((float) $outstandingInvoices->sum(fn ($invoice) => (float) ($invoice->balance_amount ?? 0)), 2);
        $unbilledSales = $salesCollection
            ->filter(fn (Sale $sale) => !$linkedSaleIds->contains((int) $sale->id));
        $unbilledSalesAmount = round((float) $unbilledSales->sum(fn (Sale $sale) => (float) ($sale->sale_amount ?? 0)), 2);

        return [
            'outstandingInvoiceCount' => (int) $outstandingInvoices->count(),
            'outstandingInvoiceAmount' => $outstandingInvoiceAmount,
            'unbilledSalesCount' => (int) $unbilledSales->count(),
            'unbilledSalesAmount' => $unbilledSalesAmount,
            'totalPendingSalesAmount' => round($outstandingInvoiceAmount + $unbilledSalesAmount, 2),
        ];
    }

    public function index(Request $request)
    {
        $this->authorize('viewAny', Sale::class);

        $search = trim((string) $request->get('search', ''));
        $customerId = $request->get('customer_id', '');
        $paymentStatus = (string) $request->get('payment_status', '');
        $fromDate = trim((string) $request->get('from_date', $request->get('date', '')));
        $toDate = trim((string) $request->get('to_date', $request->get('date', '')));
        $sortBy = (string) $request->get('sort_by', 'latest');

        $applyIndexFilters = function ($query) use ($customerId, $paymentStatus, $search, $fromDate, $toDate) {
            $query
                ->when($customerId !== '', fn ($innerQuery) => $innerQuery->where('customer_id', $customerId))
                ->when($paymentStatus !== '', fn ($innerQuery) => $innerQuery->where('payment_status', $paymentStatus))
                ->when($search !== '', function ($innerQuery) use ($search) {
                    $innerQuery->where(function ($nestedQuery) use ($search) {
                        $nestedQuery->whereHas('customer', function ($customerQuery) use ($search) {
                            $customerQuery->where('name', 'like', '%' . $search . '%')
                                ->orWhere('phone', 'like', '%' . $search . '%')
                                ->orWhere('email', 'like', '%' . $search . '%');

                            if (Customer::hasWhatsappNumberColumn()) {
                                $customerQuery->orWhere('whatsapp_number', 'like', '%' . $search . '%');
                            }
                        })->orWhereHas('product', function ($productQuery) use ($search) {
                            $productQuery->where('name', 'like', '%' . $search . '%');
                        })->orWhere('notes', 'like', '%' . $search . '%');
                    });
                });

            $this->applyDateRangeFilter($query, $fromDate, $toDate);

            return $query;
        };

        $salesQuery = $applyIndexFilters($this->baseSalesQuery(true));
        $summaryQuery = $applyIndexFilters($this->baseSalesQuery(false));

        $sales = $this->applySorting(clone $salesQuery, $sortBy)
            ->paginate(20)
            ->withQueryString();

        $this->attachLinkedInvoiceIds($sales->getCollection());

        $totalSales = (clone $summaryQuery)->count();
        $paidSales = (clone $summaryQuery)->where('payment_status', 'paid')->count();
        $pendingSales = (clone $summaryQuery)->whereIn('payment_status', ['pending', 'partial'])->count();
        $totalSalesAmount = (clone $summaryQuery)->sum('sale_amount');
        $totalTransportationAmount = (clone $summaryQuery)->sum('shipping_charges');
        $totalSaleValue = max((float) $totalSalesAmount - (float) $totalTransportationAmount, 0);
        $salesReceivables = $this->salesReceivablesSnapshot($summaryQuery);
        $outstandingInvoiceAmount = (float) ($salesReceivables['outstandingInvoiceAmount'] ?? 0);
        $outstandingInvoiceCount = (int) ($salesReceivables['outstandingInvoiceCount'] ?? 0);
        $unbilledSalesAmount = (float) ($salesReceivables['unbilledSalesAmount'] ?? 0);
        $unbilledSalesCount = (int) ($salesReceivables['unbilledSalesCount'] ?? 0);
        $totalPendingSalesAmount = (float) ($salesReceivables['totalPendingSalesAmount'] ?? 0);

        $customers = Customer::where('organization_id', $this->orgId())
            ->orderBy('name')
            ->get(['id', 'name']);

        return view('sales.index', compact(
            'sales',
            'customers',
            'search',
            'customerId',
            'paymentStatus',
            'fromDate',
            'toDate',
            'sortBy',
            'totalSales',
            'paidSales',
            'pendingSales',
            'totalSalesAmount',
            'totalTransportationAmount',
            'totalSaleValue',
            'outstandingInvoiceAmount',
            'outstandingInvoiceCount',
            'unbilledSalesAmount',
            'unbilledSalesCount',
            'totalPendingSalesAmount'
        ));
    }

    public function show(Sale $sale)
    {
        $sale = $this->scopedSale($sale);
        $this->authorize('view', $sale);
        $relations = ['customer', 'product', 'asset.warehouse', 'rental.customer', 'rental.product'];

        if ($this->hasDeliverySaleColumn()) {
            $relations[] = 'deliveryRecord.assignedStaff';
            $relations[] = 'deliveryRecord.assignedUser';
        }

        $sale->load($relations);
        $saleInvoice = $this->saleInvoice($sale);
        $saleInvoice?->load(['payments.customer', 'payments.rental.product']);
        $sale->setAttribute('linked_invoice_id', $saleInvoice?->id);
        $activityLogs = ActivityLogger::recentFor($sale);

        return view('sales.show', compact('sale', 'saleInvoice', 'activityLogs'));
    }

    public function create()
    {
        $this->authorize('create', Sale::class);

        $customers = Customer::where('organization_id', $this->orgId())->orderBy('name')->get();
        $products = Product::where('organization_id', $this->orgId())->orderBy('name')->get();
        $assets = Asset::query()
            ->with(['product', 'warehouse'])
            ->where('organization_id', $this->orgId())
            ->where('asset_stage', Asset::STAGE_NEW_STOCK)
            ->where('asset_status', 'available_for_sale')
            ->orderBy('serial_number')
            ->get();
        $rentals = Rental::query()
            ->with(['customer', 'product'])
            ->where('organization_id', $this->orgId())
            ->latest('id')
            ->get();

        return view('sales.create', compact('customers', 'products', 'assets', 'rentals'));
    }

    public function store(Request $request)
    {
        $this->authorize('create', Sale::class);

        $this->synchronizeLinkedRentalContext($request);
        $request->validate($this->saleValidationRules());

        $customer = Customer::where('organization_id', $this->orgId())->findOrFail($request->customer_id);
        $product = Product::where('organization_id', $this->orgId())->findOrFail($request->product_id);
        $this->validateLinkedSaleReferences($request, $product, $customer);
        $commercials = $this->calculateSaleCommercials(
            (float) $request->quantity,
            (float) $request->unit_price,
            (float) ($request->discount_amount ?? 0),
            (float) ($request->shipping_charges ?? 0),
            (float) ($request->tax_percentage ?? 0),
            (string) ($request->tax_calculation_mode ?? 'exclusive')
        );

        $salePayload = [
            'customer_id' => $customer->id,
            'product_id' => $product->id,
            'asset_id' => $request->filled('asset_id') ? $request->integer('asset_id') : null,
            'rental_id' => $request->filled('rental_id') ? $request->integer('rental_id') : null,
            'quantity' => $request->quantity,
            'unit_price' => $request->unit_price,
            'discount_amount' => $request->discount_amount ?? 0,
            'shipping_charges' => $request->shipping_charges ?? 0,
            'tax_percentage' => $request->tax_percentage ?? 0,
            'tax_calculation_mode' => $request->tax_calculation_mode ?? 'exclusive',
            'sale_date' => $request->sale_date,
            'sale_amount' => $commercials['sale_amount'],
            'payment_status' => $request->payment_status,
            'notes' => $request->notes,
            'organization_id' => $this->orgId(),
        ];

        if ($this->hasCreatedByColumn()) {
            $salePayload['created_by'] = auth()->id();
        }

        if ($this->hasCreatedByUserColumn()) {
            $salePayload['created_by_user_id'] = auth()->id();
        }

        [$sale, $invoice] = DB::transaction(function () use ($salePayload) {
            $sale = Sale::create($salePayload);
            $this->applySaleStock($sale);
            $invoice = $this->createSaleInvoice($sale);

            return [$sale, $invoice];
        });

        ActivityLogger::log('sale.created', $sale, [
            'invoice_id' => $invoice->id,
            'invoice_number' => $invoice->invoice_number,
            'sale_amount' => $sale->sale_amount,
            'payment_status' => $sale->payment_status,
            'tax_calculation_mode' => $sale->tax_calculation_mode ?? null,
        ], 'Sale created and invoice generated.');

        return redirect()
            ->route('sales.index')
            ->with('success', 'Sale created successfully. Invoice ' . $invoice->invoice_number . ' was created automatically.');
    }

    public function importSaleFromPayload(array $attributes): array
    {
        $customer = Customer::where('organization_id', $this->orgId())->findOrFail((int) $attributes['customer_id']);
        $product = Product::where('organization_id', $this->orgId())->findOrFail((int) $attributes['product_id']);
        $match = $this->describeImportedSaleMatch(
            $this->importMatchSignatureService()->sale(
                $attributes,
                $customer->id,
                $product->id,
                max((int) ($attributes['quantity'] ?? 0), 1),
                $this->hasWarehouseColumn() && !empty($attributes['warehouse_id'])
                    ? (int) $attributes['warehouse_id']
                    : null
            )
        );

        if (($match['action'] ?? null) === 'review') {
            throw ValidationException::withMessages([
                'import' => [$match['message'] ?? 'This sales import row requires manual review.'],
            ]);
        }

        $commercials = $this->calculateSaleCommercials(
            (float) $attributes['quantity'],
            (float) $attributes['unit_price'],
            (float) ($attributes['discount_amount'] ?? 0),
            (float) ($attributes['shipping_charges'] ?? 0),
            (float) ($attributes['tax_percentage'] ?? 0),
            (string) ($attributes['tax_calculation_mode'] ?? 'exclusive')
        );

        $salePayload = [
            'customer_id' => $customer->id,
            'product_id' => $product->id,
            'asset_id' => $attributes['asset_id'] ?? null,
            'rental_id' => $attributes['rental_id'] ?? null,
            'quantity' => $attributes['quantity'],
            'unit_price' => $attributes['unit_price'],
            'discount_amount' => $attributes['discount_amount'] ?? 0,
            'shipping_charges' => $attributes['shipping_charges'] ?? 0,
            'tax_percentage' => $attributes['tax_percentage'] ?? 0,
            'tax_calculation_mode' => $attributes['tax_calculation_mode'] ?? 'exclusive',
            'sale_date' => $attributes['sale_date'],
            'sale_amount' => $commercials['sale_amount'],
            'payment_status' => in_array(($attributes['payment_status'] ?? 'pending'), ['paid', 'partial'], true)
                ? 'pending'
                : ($attributes['payment_status'] ?? 'pending'),
            'notes' => $attributes['notes'] ?? null,
            'organization_id' => $this->orgId(),
        ];

        if ($this->hasWarehouseColumn() && !empty($attributes['warehouse_id'])) {
            $salePayload['warehouse_id'] = (int) $attributes['warehouse_id'];
        }

        if ($this->hasCreatedByColumn()) {
            $salePayload['created_by'] = auth()->id();
        }

        if ($this->hasCreatedByUserColumn()) {
            $salePayload['created_by_user_id'] = auth()->id();
        }

        if ($existingSale = ($match['sale'] ?? null)) {
            [$sale, $invoice, $delivery] = $this->updateImportedSaleFromPayload($existingSale, $salePayload, $attributes);
            $action = 'updated';
        } else {
            [$sale, $invoice, $delivery] = $this->createImportedSaleFromPayload($salePayload, $attributes);
            $action = 'created';
        }

        try {
            ActivityLogger::log('sale.imported', $sale, [
                'invoice_id' => $invoice?->id,
                'invoice_number' => $invoice?->invoice_number,
                'delivery_id' => $delivery?->id,
                'sale_amount' => $sale->sale_amount,
                'payment_status' => $sale->payment_status,
                'import_action' => $action,
            ], 'Sale imported via sales import preview.');
        } catch (\Throwable) {
            // Keep import success independent from optional activity logging.
        }

        return [
            'sale' => $sale,
            'invoice' => $invoice,
            'delivery' => $delivery,
            'action' => $action,
        ];
    }

    public function describeImportedSaleMatch(array $attributes): array
    {
        $customerId = (int) ($attributes['customer_id'] ?? 0);
        $productId = (int) ($attributes['product_id'] ?? 0);
        $quantity = max((int) ($attributes['quantity'] ?? 0), 1);
        $saleDate = $attributes['sale_date'] ?? null;
        $warehouseId = !empty($attributes['warehouse_id']) ? (int) $attributes['warehouse_id'] : null;

        if ($customerId <= 0 || $productId <= 0 || blank($saleDate)) {
            return ['action' => 'create', 'sale' => null, 'message' => null];
        }

        $candidates = Sale::query()
            ->where('organization_id', $this->orgId())
            ->where('customer_id', $customerId)
            ->where('product_id', $productId)
            ->whereDate('sale_date', $saleDate)
            ->where('quantity', $quantity)
            ->when($this->hasWarehouseColumn() && $warehouseId, fn ($query) => $query->where('warehouse_id', $warehouseId))
            ->with(['invoice.payments'])
            ->get();

        if ($candidates->isEmpty()) {
            return ['action' => 'create', 'sale' => null, 'message' => null];
        }

        if ($candidates->count() > 1) {
            return [
                'action' => 'review',
                'sale' => null,
                'message' => 'Multiple sales match this import row. Add a unique external reference or review manually.',
            ];
        }

        $sale = $candidates->first();
        $invoice = $sale?->invoice ?? $this->saleInvoice($sale);
        $paymentReview = $invoice ? $this->importedSalePaymentReviewMessage($sale, $invoice, $attributes) : null;

        if ($paymentReview) {
            return [
                'action' => 'review',
                'sale' => $sale,
                'message' => $paymentReview,
            ];
        }

        return ['action' => 'update', 'sale' => $sale, 'message' => null];
    }

    private function createImportedSaleFromPayload(array $salePayload, array $attributes): array
    {
        return $this->saleImportExecutor()->createImportedSale($salePayload, $attributes, [
            'organization_id' => $this->orgId(),
            'has_delivery_sale_column' => $this->hasDeliverySaleColumn(),
            'has_delivery_assignment_type_column' => Schema::hasColumn('deliveries', 'assignment_type'),
            'apply_sale_stock' => fn (Sale $sale) => $this->applySaleStock($sale),
            'create_sale_invoice' => fn (Sale $sale) => $this->createSaleInvoice($sale),
            'import_field_was_provided' => fn (array $row, string $field) => $this->importFieldWasProvided($row, $field),
            'managed_imported_payment_query' => fn (Invoice $invoice, int $saleId) => $this->managedImportedSalePaymentQuery($invoice, $saleId),
            'imported_payment_note' => fn (int $saleId) => $this->importedSalePaymentNote($saleId),
            'create_invoice_payment' => fn (Sale $sale, Invoice $invoice, array $payload) => $this->createInvoicePaymentForSale($sale, $invoice, $payload),
            'sync_sale_payment_status_from_invoice' => fn (Sale $sale, Invoice $invoice) => $this->syncSalePaymentStatusFromInvoice($sale, $invoice),
            'has_warehouse_column' => $this->hasWarehouseColumn(),
            'sale_invoice' => fn (Sale $sale) => $this->saleInvoice($sale),
            'sync_sale_invoice_from_sale' => fn (Sale $sale, Invoice $invoice) => $this->syncSaleInvoiceFromSale($sale, $invoice),
        ]);
    }

    private function updateImportedSaleFromPayload(Sale $sale, array $salePayload, array $attributes): array
    {
        return $this->saleImportExecutor()->updateImportedSale($sale, $salePayload, $attributes, [
            'organization_id' => $this->orgId(),
            'has_delivery_sale_column' => $this->hasDeliverySaleColumn(),
            'has_delivery_assignment_type_column' => Schema::hasColumn('deliveries', 'assignment_type'),
            'import_field_was_provided' => fn (array $row, string $field) => $this->importFieldWasProvided($row, $field),
            'managed_imported_payment_query' => fn (Invoice $invoice, int $saleId) => $this->managedImportedSalePaymentQuery($invoice, $saleId),
            'imported_payment_note' => fn (int $saleId) => $this->importedSalePaymentNote($saleId),
            'create_invoice_payment' => fn (Sale $saleRecord, Invoice $invoice, array $payload) => $this->createInvoicePaymentForSale($saleRecord, $invoice, $payload),
            'sync_sale_payment_status_from_invoice' => fn (Sale $saleRecord, Invoice $invoice) => $this->syncSalePaymentStatusFromInvoice($saleRecord, $invoice),
            'has_warehouse_column' => $this->hasWarehouseColumn(),
            'sale_invoice' => fn (Sale $saleRecord) => $this->saleInvoice($saleRecord),
            'create_sale_invoice' => fn (Sale $saleRecord) => $this->createSaleInvoice($saleRecord),
            'sync_sale_invoice_from_sale' => fn (Sale $saleRecord, Invoice $invoice) => $this->syncSaleInvoiceFromSale($saleRecord, $invoice),
        ]);
    }

    private function shouldCreateImportedSaleInvoice(array $attributes): bool
    {
        return $this->saleImportExecutor()->shouldCreateImportedSaleInvoice($attributes);
    }

    private function applyImportedSalePaymentState(Sale $sale, Invoice $invoice, array $attributes): void
    {
        $this->saleImportExecutor()->applyImportedSalePaymentState($sale, $invoice, $attributes, [
            'import_field_was_provided' => fn (array $row, string $field) => $this->importFieldWasProvided($row, $field),
            'managed_imported_payment_query' => fn (Invoice $linkedInvoice, int $saleId) => $this->managedImportedSalePaymentQuery($linkedInvoice, $saleId),
            'imported_payment_note' => fn (int $saleId) => $this->importedSalePaymentNote($saleId),
            'create_invoice_payment' => fn (Sale $saleRecord, Invoice $linkedInvoice, array $payload) => $this->createInvoicePaymentForSale($saleRecord, $linkedInvoice, $payload),
            'sync_sale_payment_status_from_invoice' => fn (Sale $saleRecord, Invoice $linkedInvoice) => $this->syncSalePaymentStatusFromInvoice($saleRecord, $linkedInvoice),
        ]);
    }

    private function applyImportedSaleDeliveryState(Sale $sale, array $attributes, bool $isUpdate = false): ?Delivery
    {
        return $this->saleImportExecutor()->applyImportedSaleDeliveryState(
            $sale,
            $attributes,
            $isUpdate,
            $this->orgId(),
            $this->hasDeliverySaleColumn(),
            Schema::hasColumn('deliveries', 'assignment_type')
        );
    }

    private function managedImportedSalePaymentQuery(Invoice $invoice, int $saleId)
    {
        return Payment::query()
            ->where('organization_id', $this->orgId())
            ->where('invoice_id', $invoice->id)
            ->where('notes', $this->importedSalePaymentNote($saleId));
    }

    private function importedSalePaymentNote(int $saleId): string
    {
        return 'Imported payment sync for sale #'.$saleId.'.';
    }

    private function importedSalePaymentReviewMessage(Sale $sale, Invoice $invoice, array $attributes): ?string
    {
        $statusProvided = $this->importFieldWasProvided($attributes, 'payment_status');
        $paidAmountProvided = $this->importFieldWasProvided($attributes, 'paid_amount');

        if (!$statusProvided && !$paidAmountProvided) {
            return null;
        }

        $paymentStatus = strtolower(trim((string) ($attributes['payment_status'] ?? 'pending')));
        $requestedPaidAmount = match ($paymentStatus) {
            'paid' => round((float) ($attributes['sale_amount'] ?? $sale->sale_amount), 2),
            'partial' => round((float) ($attributes['paid_amount'] ?? 0), 2),
            default => 0.0,
        };

        $managedPayment = $this->managedImportedSalePaymentQuery($invoice, $sale->id)->first();
        $historicalPaymentsTotal = (float) $invoice->payments()
            ->when($managedPayment, fn ($query) => $query->whereKeyNot($managedPayment->id))
            ->sum('amount');

        if ($requestedPaidAmount + 0.01 < $historicalPaymentsTotal) {
            return 'Existing recorded payments exceed the imported payment state for this sale. Review this row manually.';
        }

        return null;
    }

    private function importFieldWasProvided(array $attributes, string $field): bool
    {
        return (bool) ($attributes[$field.'_provided'] ?? false);
    }

    public function edit(Sale $sale)
    {
        $sale = $this->scopedSale($sale);
        $this->authorize('update', $sale);

        if ($this->isAutoGeneratedRentalSale($sale)) {
            return $this->managedRentalSaleRedirect($sale);
        }

        $customers = Customer::where('organization_id', $this->orgId())->orderBy('name')->get();
        $products = Product::where('organization_id', $this->orgId())->orderBy('name')->get();
        $assets = Asset::query()
            ->with(['product', 'warehouse'])
            ->where('organization_id', $this->orgId())
            ->where('asset_stage', Asset::STAGE_NEW_STOCK)
            ->where(function ($query) use ($sale) {
                $query->where('asset_status', 'available_for_sale');

                if ($sale->asset_id) {
                    $query->orWhere('id', $sale->asset_id);
                }
            })
            ->orderBy('serial_number')
            ->get();
        $rentals = Rental::query()
            ->with(['customer', 'product'])
            ->where('organization_id', $this->orgId())
            ->latest('id')
            ->get();

        return view('sales.edit', compact('sale', 'customers', 'products', 'assets', 'rentals'));
    }

    public function update(Request $request, Sale $sale)
    {
        $sale = $this->scopedSale($sale);
        $this->authorize('update', $sale);

        if ($this->isAutoGeneratedRentalSale($sale)) {
            return $this->managedRentalSaleRedirect($sale);
        }

        $this->synchronizeLinkedRentalContext($request);
        $request->validate($this->saleValidationRules($sale));

        $customer = Customer::where('organization_id', $this->orgId())->findOrFail($request->customer_id);
        $product = Product::where('organization_id', $this->orgId())->findOrFail($request->product_id);
        $this->validateLinkedSaleReferences($request, $product, $customer, $sale);
        $commercials = $this->calculateSaleCommercials(
            (float) $request->quantity,
            (float) $request->unit_price,
            (float) ($request->discount_amount ?? 0),
            (float) ($request->shipping_charges ?? 0),
            (float) ($request->tax_percentage ?? 0),
            (string) ($request->tax_calculation_mode ?? 'exclusive')
        );

        $linkedInvoice = $this->saleInvoice($sale->loadMissing(['customer', 'product']));
        if ($linkedInvoice) {
            app(AmountReductionGuardService::class)->assertTotalNotBelowReceivedPayments(
                $linkedInvoice,
                (float) ($commercials['sale_amount'] ?? 0),
                'This sale update'
            );
        }

        DB::transaction(function () use ($sale, $customer, $product, $request, $commercials) {
            $originalSale = Sale::query()
                ->with(['product', 'asset'])
                ->where('organization_id', $this->orgId())
                ->findOrFail($sale->id);

            if ($this->saleUsesAppliedStock($originalSale)) {
                $this->restoreSaleStock($originalSale);
            }

            $sale->update([
                'customer_id' => $customer->id,
                'product_id' => $product->id,
                'asset_id' => $request->filled('asset_id') ? $request->integer('asset_id') : null,
                'rental_id' => $request->filled('rental_id') ? $request->integer('rental_id') : null,
                'quantity' => $request->quantity,
                'unit_price' => $request->unit_price,
                'discount_amount' => $request->discount_amount ?? 0,
                'shipping_charges' => $request->shipping_charges ?? 0,
                'tax_percentage' => $request->tax_percentage ?? 0,
                'tax_calculation_mode' => $request->tax_calculation_mode ?? 'exclusive',
                'sale_date' => $request->sale_date,
                'sale_amount' => $commercials['sale_amount'],
                'payment_status' => $request->payment_status,
                'notes' => $request->notes,
            ]);

            if ($sale->payment_status !== 'void') {
                $this->applySaleStock($sale->fresh(['product', 'asset']));
            } elseif ($this->hasStockAppliedColumn()) {
                $sale->forceFill(['stock_applied' => false])->saveQuietly();
            }

            if ($invoice = $this->saleInvoice($sale->refresh())) {
                $this->syncSaleInvoiceFromSale($sale, $invoice);
                $this->syncExistingSaleInvoicePayment($sale, $invoice);
            }
        });

        ActivityLogger::log('sale.updated', $sale->refresh(), [
            'sale_amount' => $sale->sale_amount,
            'payment_status' => $sale->payment_status,
            'tax_calculation_mode' => $sale->tax_calculation_mode ?? null,
        ], 'Sale updated.');

        return redirect()->route('sales.index')->with('success', 'Sale updated successfully.');
    }

    public function generateInvoice(Sale $sale)
    {
        $sale = $this->scopedSale($sale);

        $invoice = $this->createSaleInvoice($sale);

        ActivityLogger::log('sale.invoice.generated', $invoice, [
            'sale_id' => $sale->id,
            'invoice_number' => $invoice->invoice_number,
            'total_amount' => $invoice->total_amount,
            'payment_status' => $invoice->payment_status,
        ], 'Sale invoice generated.');

        return redirect()->route('invoices.show', $invoice)->with('success', 'Sale invoice is ready.');
    }

    public function markPaid(Sale $sale)
    {
        $sale = $this->scopedSale($sale);
        $invoice = $this->createSaleInvoice($sale);
        $invoice->syncFinancialStatus();

        if ((float) $invoice->balance_amount <= 0) {
            $this->syncSalePaymentStatusFromInvoice($sale, $invoice);

            return redirect()->route('sales.show', $sale)->with('success', 'Sale invoice is already settled.');
        }

        DB::transaction(function () use ($sale, $invoice) {
            $payment = $this->createInvoicePaymentForSale($sale, $invoice, [
                'payment_date' => now()->toDateString(),
                'amount' => (float) $invoice->balance_amount,
                'payment_method' => 'other',
                'notes' => 'Auto-recorded from Mark Paid action.',
            ]);

            $this->syncSalePaymentStatusFromInvoice($sale->refresh(), $invoice->refresh());

            ActivityLogger::log('sale.marked_paid', $sale, [
                'invoice_id' => $invoice->id,
                'payment_id' => $payment->id,
                'payment_amount' => $payment->amount,
            ], 'Sale marked as paid from the sale page.');
        });

        return redirect()->route('sales.show', $sale)->with('success', 'Sale marked as paid.');
    }

    public function recordPayment(Request $request, Sale $sale)
    {
        $sale = $this->scopedSale($sale);
        $validated = $this->validateQuickPayment($request);
        $invoice = $this->createSaleInvoice($sale);

        DB::transaction(function () use ($sale, $invoice, $validated) {
            $payment = $this->createInvoicePaymentForSale($sale, $invoice, $validated);
            $this->syncSalePaymentStatusFromInvoice($sale->refresh(), $invoice->refresh());

            ActivityLogger::log('sale.partial_payment_recorded', $sale, [
                'invoice_id' => $invoice->id,
                'payment_id' => $payment->id,
                'payment_amount' => $payment->amount,
                'payment_method' => $payment->payment_method,
            ], 'Sale payment recorded from the sale page.');
        });

        return redirect()->route('sales.show', $sale)->with('success', 'Sale payment recorded successfully.');
    }

    public function destroy(Sale $sale)
    {
        $sale = $this->scopedSale($sale);
        $this->authorize('delete', $sale);

        if ($this->isAutoGeneratedRentalSale($sale)) {
            return $this->managedRentalSaleRedirect($sale);
        }

        DB::transaction(function () use ($sale) {
            $sale->loadMissing(['product', 'asset']);

            if ($this->saleUsesAppliedStock($sale)) {
                $this->restoreSaleStock($sale);
            }

            $sale->delete();
        });

        return redirect()->route('sales.index')->with('success', 'Sale deleted successfully.');
    }

    public function voidSale(Sale $sale)
    {
        $sale = $this->scopedSale($sale);

        if ($this->isAutoGeneratedRentalSale($sale)) {
            return $this->managedRentalSaleRedirect($sale);
        }

        if ($sale->payment_status === 'void') {
            return redirect()->route('sales.show', $sale)->with('error', 'This sale is already voided.');
        }

        DB::transaction(function () use ($sale) {
            if ($this->saleUsesAppliedStock($sale->loadMissing(['product', 'asset']))) {
                $this->restoreSaleStock($sale);
            }

            $invoice = $this->saleInvoice($sale);

            if ($invoice) {
                $this->autoPaidSalePaymentQuery($sale, $invoice)->delete();
                $invoice->forceFill([
                    'status' => 'cancelled',
                    'payment_status' => 'cancelled',
                    'paid_amount' => (float) $invoice->payments()->sum('amount'),
                    'balance_amount' => 0,
                ])->save();
            }

            $sale->update([
                'payment_status' => 'void',
                'notes' => trim(($sale->notes ? $sale->notes . ' | ' : '') . 'Sale voided.'),
            ]);

            if ($this->hasStockAppliedColumn()) {
                $sale->forceFill(['stock_applied' => false])->saveQuietly();
            }
        });

        ActivityLogger::log('sale.voided', $sale->refresh(), [
            'payment_status' => $sale->payment_status,
        ], 'Sale voided.');

        return redirect()->route('sales.show', $sale)->with('success', 'Sale voided successfully.');
    }
}
