@extends('layouts.app')

@section('content')
@php
    $currentUser = auth()->user();
    $canUpdateSales = $currentUser?->canAccessModule('sales', 'update') ?? false;
    $canDeleteSales = $currentUser?->canAccessModule('sales', 'delete') ?? false;
    $canDeletePayments = $currentUser?->canAccessModule('payments', 'delete') ?? false;
    $canCreatePayments = $currentUser?->canAccessModule('payments', 'create') ?? false;
    $canCreateDeliveries = $currentUser?->canAccessModule('deliveries', 'create') ?? false;
    $canUpdateDeliveries = $currentUser?->canAccessModule('deliveries', 'update') ?? false;
    $hasSaleDeliverySupport = \Illuminate\Support\Facades\Schema::hasColumn('deliveries', 'sale_id');
    $canViewFinance = $currentUser?->canViewFinance() ?? false;
    $isAutoGeneratedRentalSale = (bool) ($sale->auto_generated_from_rental ?? false);
    $currency = fn ($value) => "\u{20B9}" . number_format((float) $value, 2);
    $saleInvoiceId = $sale->linked_invoice_id ?? null;
    $saleInvoiceStatus = $saleInvoice?->payment_status ?? null;
    $saleInvoiceDue = (float) ($saleInvoice->balance_amount ?? 0);
    $saleItems = $sale->displaySaleItems();
    $saleItemsCount = $saleItems->count();
    $saleItemsQuantity = (int) $saleItems->sum(fn ($item) => (int) ($item->quantity ?? 0));
    $statusTone = match ($sale->payment_status) {
        'paid' => 'background:#dcfce7;color:#166534;',
        'partial' => 'background:#fef3c7;color:#b45309;',
        default => 'background:#fee2e2;color:#b91c1c;',
    };
    $deliveryStatusLabel = fn (?string $status) => match ($status) {
        'pending', 'assigned' => 'Delivery Assigned',
        'in_progress' => 'Delivery In Progress',
        'completed' => 'Delivery Completed',
        default => $status ? ucfirst(str_replace('_', ' ', $status)) . ' Delivery' : 'Delivery Not Assigned',
    };
    $assignedPersonLabel = fn ($record) => $record?->assignedStaff?->name
        ?? $record?->assignedUser?->name
        ?? $record?->third_party_name
        ?? 'Not assigned';
    $reminderContactName = $sale->reminderContactName();
    $reminderContactPhone = $sale->reminderContactPhone();
    $deliveryContactName = $sale->deliveryContactName();
    $deliveryContactPhone = $sale->deliveryContactPhone();
    $deliveryContactAddress = $sale->deliveryContactAddress();
    $deliveryContactMapUrl = $sale->deliveryContactMapUrl();
    $saleReminderCallHref = $reminderContactPhone ? 'tel:' . preg_replace('/\D+/', '', $reminderContactPhone) : null;
    $saleWhatsappHref = $saleInvoice?->bill_to_phone || $sale->customer?->phone
        ? \App\Support\WhatsAppHelper::chatUrl(
            \App\Support\WhatsAppHelper::normalizeNumber($saleInvoice?->bill_to_phone ?: $sale->customer?->phone),
            $saleInvoice ? \App\Support\WhatsAppHelper::invoiceMessage($saleInvoice) : \App\Support\WhatsAppHelper::saleFollowUp($sale)
        )
        : null;
    $saleFollowUpContextJson = json_encode([
        'customer_id' => $sale->customer_id,
        'business_partner_id' => $sale->business_partner_id,
        'partner_client_id' => $sale->partner_client_id,
        'sale_id' => $sale->id,
        'invoice_id' => $saleInvoiceId,
        'delivery_id' => $sale->deliveryRecord?->id,
        'reference' => 'Sale #' . $sale->id,
        'reminder_contact' => collect([$reminderContactName, $reminderContactPhone])->filter()->implode(' | '),
        'service_contact' => collect([$deliveryContactName, $deliveryContactPhone])->filter()->implode(' | '),
        'service_address' => $deliveryContactAddress,
    ]);
    $saleQuickActions = collect();
    $saleMoreActions = collect();
    $saleInfoItems = collect();

    if ($saleReminderCallHref) {
        $saleQuickActions->push([
            'type' => 'link',
            'label' => 'Call',
            'href' => $saleReminderCallHref,
        ]);
    }

    if ($saleWhatsappHref) {
        $saleQuickActions->push([
            'type' => 'link',
            'label' => 'WhatsApp',
            'href' => $saleWhatsappHref,
            'target' => '_blank',
            'rel' => 'noopener',
            'accent' => true,
        ]);
    }

    if ($saleInvoiceId) {
        $saleQuickActions->push([
            'type' => 'link',
            'label' => 'Invoice',
            'href' => route('invoices.show', $saleInvoiceId),
        ]);
    } elseif ($canUpdateSales) {
        $saleQuickActions->push([
            'type' => 'form',
            'label' => 'Invoice',
            'action' => route('sales.invoice', $sale),
            'method' => 'POST',
        ]);
    }

    if ($canCreatePayments && !in_array($saleInvoiceStatus, ['paid', 'cancelled'], true)) {
        $saleQuickActions->push([
            'type' => 'link',
            'label' => 'Payment',
            'href' => '#sale-billing-actions',
        ]);
    }

    if (!$isAutoGeneratedRentalSale && $hasSaleDeliverySupport) {
        if ($sale->relationLoaded('deliveryRecord') && $sale->deliveryRecord) {
            $saleQuickActions->push([
                'type' => 'link',
                'label' => 'Delivery',
                'href' => route('deliveries.show', $sale->deliveryRecord),
            ]);
        } elseif ($canCreateDeliveries) {
            $saleQuickActions->push([
                'type' => 'link',
                'label' => 'Delivery',
                'href' => route('deliveries.create', ['sale_id' => $sale->id, 'type' => 'delivery']),
            ]);
        }
    }

    $saleQuickActions->push([
        'type' => 'link',
        'label' => 'Timeline',
        'href' => '#sale-activity-timeline',
    ]);

    $saleMoreActions->push([
        'type' => 'link',
        'label' => 'Add Note',
        'href' => '#sale-activity-timeline',
    ]);
    $saleMoreActions->push([
        'type' => 'button',
        'label' => 'Add Follow-up',
        'attributes' => [
            'data-open-follow-up-modal' => true,
            'data-follow-up-context' => $saleFollowUpContextJson,
            'data-follow-up-type' => \App\Models\FollowUp::TYPE_PAYMENT,
            'data-follow-up-priority' => \App\Models\FollowUp::PRIORITY_MEDIUM,
        ],
    ]);

    if (!$isAutoGeneratedRentalSale && $canCreateDeliveries && $hasSaleDeliverySupport) {
        if ($sale->relationLoaded('deliveryRecord') && $sale->deliveryRecord) {
            $saleMoreActions->push([
                'type' => 'link',
                'label' => 'Assign Delivery',
                'href' => route('deliveries.edit', $sale->deliveryRecord),
            ]);
        } else {
            $saleMoreActions->push([
                'type' => 'link',
                'label' => 'Assign Delivery',
                'href' => route('deliveries.create', ['sale_id' => $sale->id, 'type' => 'delivery']),
            ]);
        }
    }

    if ($sale->customer_id) {
        $saleMoreActions->push([
            'type' => 'link',
            'label' => 'View Customer',
            'href' => route('customers.show', $sale->customer_id),
        ]);
    }

    if ($sale->business_partner_id) {
        $saleMoreActions->push([
            'type' => 'link',
            'label' => 'View Business Partner',
            'href' => route('business-partners.show', $sale->business_partner_id),
        ]);
        $saleMoreActions->push([
            'type' => 'link',
            'label' => 'View Actual Client',
            'href' => route('business-partners.show', $sale->business_partner_id) . '#actual-clients',
        ]);
    }

    if ($deliveryContactMapUrl) {
        $saleMoreActions->push([
            'type' => 'link',
            'label' => 'Open Map',
            'href' => $deliveryContactMapUrl,
            'target' => '_blank',
            'rel' => 'noopener',
        ]);
    }

    $saleInfoItems->push([
        'label' => 'Reminder / Payment',
        'value' => collect([$reminderContactName, $reminderContactPhone])->filter()->implode(' | '),
    ]);
    $saleInfoItems->push([
        'label' => 'Delivery / Service',
        'value' => collect([$deliveryContactName, $deliveryContactPhone])->filter()->implode(' | '),
    ]);
    if ($deliveryContactAddress) {
        $saleInfoItems->push([
            'label' => 'Service Location',
            'value' => $deliveryContactAddress,
            'href' => $deliveryContactMapUrl,
            'target' => '_blank',
            'rel' => 'noopener',
            'linkLabel' => 'Open Map',
        ]);
    }

    $mobilePrimaryActions = collect();
    $mobileMoreActions = collect();

    if ($saleInvoiceId) {
        $mobilePrimaryActions->push([
            'type' => 'link',
            'label' => 'Invoice',
            'href' => route('invoices.show', $saleInvoiceId),
        ]);
    } elseif ($canUpdateSales) {
        $mobilePrimaryActions->push([
            'type' => 'form',
            'label' => 'Invoice',
            'action' => route('sales.invoice', $sale),
            'method' => 'POST',
        ]);
    }

    if ($canCreatePayments && !in_array($saleInvoiceStatus, ['paid', 'cancelled'], true)) {
        $mobilePrimaryActions->push([
            'type' => 'form',
            'label' => 'Paid',
            'action' => route('sales.markPaid', $sale),
            'method' => 'POST',
        ]);
    } elseif (!$isAutoGeneratedRentalSale && $hasSaleDeliverySupport) {
        if ($sale->relationLoaded('deliveryRecord') && $sale->deliveryRecord) {
            $mobilePrimaryActions->push([
                'type' => 'link',
                'label' => 'Delivery',
                'href' => route('deliveries.show', $sale->deliveryRecord),
            ]);
        } elseif ($canCreateDeliveries) {
            $mobilePrimaryActions->push([
                'type' => 'link',
                'label' => 'Delivery',
                'href' => route('deliveries.create', ['sale_id' => $sale->id, 'type' => 'delivery']),
            ]);
        }
    } elseif (!$isAutoGeneratedRentalSale && $canUpdateSales) {
        $mobilePrimaryActions->push([
            'type' => 'link',
            'label' => 'Edit',
            'href' => route('sales.edit', $sale),
        ]);
    } elseif ($isAutoGeneratedRentalSale && $sale->rental) {
        $mobilePrimaryActions->push([
            'type' => 'link',
            'label' => 'Edit Rental',
            'href' => route('rentals.edit', $sale->rental),
        ]);
    }

    $mobilePrimaryActions = $mobilePrimaryActions->take(2)->values();
    $usedMobileLabels = $mobilePrimaryActions->pluck('label')->all();
    $pushMoreAction = function (array $action) use (&$mobileMoreActions, $usedMobileLabels): void {
        if (in_array($action['label'], $usedMobileLabels, true)) {
            return;
        }

        $mobileMoreActions->push($action);
    };

    $pushMoreAction([
        'type' => 'link',
        'label' => 'Back to Sales',
        'href' => route('sales.index'),
    ]);

    if ($canCreatePayments && !in_array($saleInvoiceStatus, ['paid', 'cancelled'], true)) {
        $pushMoreAction([
            'type' => 'link',
            'label' => 'Partial Payment',
            'href' => '#sale-billing-actions',
        ]);
    }

    if ($sale->reminderContactPhone()) {
        $pushMoreAction([
            'type' => 'link',
            'label' => 'Call Customer',
            'href' => 'tel:' . preg_replace('/\D+/', '', $sale->reminderContactPhone()),
        ]);
    }

    if (!$isAutoGeneratedRentalSale && $canUpdateSales) {
        $pushMoreAction([
            'type' => 'link',
            'label' => 'Edit Sale',
            'href' => route('sales.edit', $sale),
        ]);
    } elseif ($isAutoGeneratedRentalSale && $sale->rental) {
        $pushMoreAction([
            'type' => 'link',
            'label' => 'Edit Rental',
            'href' => route('rentals.edit', $sale->rental),
        ]);
    }

    if ($canUpdateDeliveries && $sale->relationLoaded('deliveryRecord') && $sale->deliveryRecord) {
        $pushMoreAction([
            'type' => 'link',
            'label' => 'View Delivery',
            'href' => route('deliveries.show', $sale->deliveryRecord),
        ]);

        if ($sale->deliveryRecord->status === 'pending') {
            $pushMoreAction([
                'type' => 'form',
                'label' => 'Start Delivery',
                'action' => route('deliveries.in_progress', $sale->deliveryRecord),
                'method' => 'PUT',
            ]);
        }

        if ($sale->deliveryRecord->status === 'in_progress') {
            $pushMoreAction([
                'type' => 'form',
                'label' => 'Complete Delivery',
                'action' => route('deliveries.complete', $sale->deliveryRecord),
                'method' => 'PUT',
            ]);
        }
    } elseif (!$isAutoGeneratedRentalSale && $canCreateDeliveries && $hasSaleDeliverySupport) {
        $pushMoreAction([
            'type' => 'link',
            'label' => 'Assign Delivery',
            'href' => route('deliveries.create', ['sale_id' => $sale->id, 'type' => 'delivery']),
        ]);
    }

    if (!$isAutoGeneratedRentalSale && $canUpdateSales && $sale->payment_status !== 'void') {
        $pushMoreAction([
            'type' => 'form',
            'label' => 'Void Sale',
            'action' => route('sales.void', $sale),
            'method' => 'PUT',
            'confirm' => 'Void this sale? This keeps the record for audit history.',
            'danger' => true,
        ]);
    }

    if (!$isAutoGeneratedRentalSale && $canDeleteSales) {
        $pushMoreAction([
            'type' => 'form',
            'label' => 'Delete Sale',
            'action' => route('sales.destroy', $sale),
            'method' => 'DELETE',
            'confirm' => 'Delete this sale record?',
            'danger' => true,
        ]);
    }
@endphp

<style>
    .sale-show-page { display:grid; gap:14px; width:100%; max-width:1080px; margin:0 auto; padding:10px 0 20px; }
    .sale-show-header { display:flex; justify-content:space-between; align-items:flex-start; gap:12px; flex-wrap:wrap; }
    .sale-show-header h1 { margin:0; font-size:28px; color:#0f172a; }
    .sale-show-header p { margin:5px 0 0; color:#64748b; font-size:13px; max-width:760px; }
    .sale-show-actions { display:flex; gap:8px; flex-wrap:wrap; }
    .mobile-inline-actions,
    .mobile-actions-menu { display:none; }
    .sale-mobile-actions {
        display:grid;
        grid-template-columns:repeat(2, minmax(0, 1fr));
        gap:8px;
        align-items:stretch;
        grid-auto-rows:minmax(44px, auto);
    }
    .sale-mobile-actions > *,
    .sale-mobile-actions form,
    .sale-mobile-actions button,
    .sale-mobile-actions a {
        min-width:0;
    }
    .sale-mobile-actions .mobile-actions-menu {
        width:100%;
    }
    .sale-mobile-actions > a,
    .sale-mobile-actions > form > button,
    .sale-mobile-actions .mobile-actions-menu summary {
        width:100%;
        min-height:44px;
        justify-content:center;
        font-size:12px;
        font-weight:800;
    }
    .ops-btn, .ops-btn-light, .ops-btn-success {
        display:inline-flex; align-items:center; justify-content:center; gap:6px;
        min-height:34px; padding:7px 12px; border-radius:10px; border:1px solid transparent;
        text-decoration:none; font-size:12px; font-weight:700; cursor:pointer; white-space:nowrap;
        line-height:1.2; font-family:inherit;
    }
    .ops-btn { background:#0f172a; color:#fff; }
    .ops-btn-light { background:#fff; color:#334155; border-color:#cbd5e1; }
    .ops-btn-success { background:#16a34a; color:#fff; border-color:#16a34a; }
    .ops-card {
        background:#fff; border:1px solid #dbe3ef; border-radius:14px;
        box-shadow:0 8px 24px rgba(15, 23, 42, 0.04);
    }
    .ops-card-head {
        display:flex; justify-content:space-between; align-items:center; gap:10px;
        padding:12px 14px; border-bottom:1px solid #e2e8f0;
    }
    .ops-card-head h2 { margin:0; font-size:15px; color:#0f172a; }
    .ops-card-body { padding:14px; }
    .summary-grid { display:grid; grid-template-columns:repeat(auto-fit, minmax(180px, 1fr)); gap:10px; }
    .summary-tile {
        padding:12px 14px; border:1px solid #dbe3ef; border-radius:12px;
        background:linear-gradient(180deg, #ffffff 0%, #f8fbff 100%);
        display:grid; gap:6px;
    }
    .summary-tile span { color:#64748b; font-size:11px; font-weight:700; text-transform:uppercase; letter-spacing:.05em; }
    .summary-tile strong { color:#0f172a; font-size:22px; line-height:1.2; min-width:0; overflow-wrap:anywhere; }
    .detail-grid { display:grid; grid-template-columns:repeat(auto-fit, minmax(220px, 1fr)); gap:12px; }
    .detail-item { display:grid; gap:5px; }
    .detail-item span { color:#64748b; font-size:11px; font-weight:700; text-transform:uppercase; letter-spacing:.05em; }
    .detail-item strong, .detail-item div { color:#0f172a; font-size:14px; line-height:1.5; }
    .badge {
        display:inline-flex; align-items:center; padding:5px 9px; border-radius:999px;
        font-size:10px; font-weight:800; text-transform:uppercase; letter-spacing:.04em;
    }
    .sale-billing-grid {
        display:grid;
        grid-template-columns:repeat(4,minmax(0,1fr));
        gap:10px;
        margin-top:14px;
    }
    .mobile-inline-actions {
        gap:8px;
        width:100%;
        grid-template-columns:repeat(2, minmax(0, 1fr));
    }
    .mobile-inline-actions a,
    .mobile-inline-actions button,
    .mobile-inline-actions form { min-width:0; }
    .mobile-inline-actions .ops-btn,
    .mobile-inline-actions .ops-btn-light,
    .mobile-inline-actions .ops-btn-success {
        width:100%;
        min-height:40px;
        padding:9px 10px;
        justify-content:center;
    }
    .mobile-actions-menu {
        position:relative;
        width:100%;
    }
    .mobile-actions-menu summary {
        list-style:none;
        display:inline-flex;
        align-items:center;
        justify-content:center;
        width:100%;
        min-height:40px;
        padding:0 12px;
        border-radius:12px;
        border:1px solid #cbd5e1;
        background:#fff;
        color:#334155;
        font-size:12px;
        font-weight:800;
        cursor:pointer;
    }
    .mobile-actions-menu summary::-webkit-details-marker { display:none; }
    .mobile-actions-menu[open] summary {
        background:#eff6ff;
        border-color:#bfdbfe;
        color:#1d4ed8;
    }
    .mobile-actions-panel {
        display:grid;
        gap:6px;
        padding:8px;
        margin-top:8px;
        border:1px solid #dbe3ef;
        border-radius:12px;
        background:#fff;
        box-shadow:0 16px 34px rgba(15,23,42,.12);
    }
    .mobile-actions-panel a,
    .mobile-actions-panel button {
        display:flex;
        align-items:center;
        justify-content:center;
        min-height:38px;
        padding:0 10px;
        border-radius:10px;
        border:1px solid #e2e8f0;
        background:#fff;
        color:#334155;
        text-decoration:none;
        font-size:12px;
        font-weight:700;
    }
    .mobile-actions-panel form { margin:0; }
    .mobile-actions-panel .danger {
        color:#b91c1c;
        border-color:#fecaca;
        background:#fff1f2;
    }
    .sale-payment-history-list {
        display:grid;
        gap:8px;
    }
    .sale-payment-history-item {
        display:grid;
        grid-template-columns:130px minmax(0, 1fr) 130px auto;
        gap:10px;
        align-items:center;
        border:1px solid #e2e8f0;
        border-radius:12px;
        padding:10px 12px;
        background:#fcfdff;
    }

    @media (max-width: 720px) {
        .sale-show-page { padding:8px 0 16px; }
        .summary-grid, .detail-grid { grid-template-columns:repeat(2, minmax(0, 1fr)); }
        .sale-show-actions { display:none; }
        .mobile-inline-actions { display:none; }
        .mobile-sticky-actions .mobile-actions-menu { display:block; }
        .sale-billing-grid { grid-template-columns:1fr; }
        .mobile-sticky-actions .mobile-actions-menu {
            flex:1 0 auto;
            width:auto;
            min-width:0;
        }
        .mobile-sticky-actions .mobile-actions-menu summary {
            min-height:44px;
            width:100%;
        }
        .mobile-sticky-actions .mobile-actions-panel {
            position:absolute;
            right:0;
            bottom:calc(100% + 8px);
            width:min(220px, calc(100vw - 44px));
            margin-top:0;
        }
        .summary-tile { min-width:0; }
        .summary-tile strong { font-size:18px; }
        .sale-payment-history-item {
            grid-template-columns:1fr;
            gap:8px;
            align-items:flex-start;
        }
        .sale-payment-history-item form {
            width:100%;
        }
        .sale-payment-history-item .ops-btn-light {
            width:100%;
            min-height:40px;
        }
    }
    @media (max-width: 420px) {
        .detail-grid { grid-template-columns:repeat(2, minmax(0, 1fr)); }
    }
</style>

<div class="container sale-show-page">
    <div class="sale-show-header">
        <div>
            <h1>Sale #{{ $sale->id }}</h1>
            <p>Quick sales view for customer, item, payment status, and related invoice access.</p>
        </div>

        <div class="sale-show-actions">
            <a href="{{ route('sales.index') }}" class="ops-btn-light">Back to Sales</a>
            @if($saleInvoiceId)
                <a href="{{ route('invoices.show', $saleInvoiceId) }}" class="ops-btn-light">View Invoice</a>
            @elseif($canUpdateSales)
                <form action="{{ route('sales.invoice', $sale) }}" method="POST" style="margin:0;">
                    @csrf
                    <button type="submit" class="ops-btn-light">Create Invoice</button>
                </form>
            @endif
            @if($canCreatePayments && !in_array($saleInvoiceStatus, ['paid', 'cancelled'], true))
                <form action="{{ route('sales.markPaid', $sale) }}" method="POST" style="margin:0;">
                    @csrf
                    <button type="submit" class="ops-btn-light">Mark as Paid</button>
                </form>
                <a href="#sale-billing-actions" class="ops-btn">Mark Partial Payment</a>
            @endif
            @if(!$isAutoGeneratedRentalSale && $canCreateDeliveries && $hasSaleDeliverySupport)
                @if($sale->relationLoaded('deliveryRecord') && $sale->deliveryRecord)
                    <a href="{{ route('deliveries.show', $sale->deliveryRecord) }}" class="ops-btn-light">
                        {{ $deliveryStatusLabel($sale->deliveryRecord->status) }}
                    </a>
                    @if($canUpdateDeliveries)
                        <a href="{{ route('deliveries.edit', $sale->deliveryRecord) }}" class="ops-btn-light">Edit Assignment</a>
                    @endif
                    @if($canUpdateDeliveries && $sale->deliveryRecord->status === 'pending')
                        <form action="{{ route('deliveries.in_progress', $sale->deliveryRecord) }}" method="POST" style="margin:0;">
                            @csrf
                            @method('PUT')
                            <button type="submit" class="ops-btn-light">Start Delivery</button>
                        </form>
                    @endif
                    @if($canUpdateDeliveries && $sale->deliveryRecord->status === 'in_progress')
                        <form action="{{ route('deliveries.complete', $sale->deliveryRecord) }}" method="POST" style="margin:0;">
                            @csrf
                            @method('PUT')
                            <button type="submit" class="ops-btn-success">Complete Delivery</button>
                        </form>
                    @endif
                @else
                    <a href="{{ route('deliveries.create', ['sale_id' => $sale->id, 'type' => 'delivery']) }}" class="ops-btn-light">Assign Delivery</a>
                @endif
            @endif
            @if(!$isAutoGeneratedRentalSale && $canUpdateSales)
                <a href="{{ route('sales.edit', $sale) }}" class="ops-btn">Edit Sale</a>
            @elseif($isAutoGeneratedRentalSale && $sale->rental)
                <a href="{{ route('rentals.edit', $sale->rental) }}" class="ops-btn">Edit Rental</a>
            @endif
            @if(!$isAutoGeneratedRentalSale && $canUpdateSales && $sale->payment_status !== 'void')
                <form action="{{ route('sales.void', $sale) }}" method="POST" style="margin:0;">
                    @csrf
                    @method('PUT')
                    <button type="submit" class="ops-btn-light" onclick="return confirm('Void this sale? This keeps the record for audit history.');">Void Sale</button>
                </form>
            @endif
        </div>

    </div>

    @include('partials.quick-action-toolbar', [
        'label' => 'Sale Quick Actions',
        'actions' => $saleQuickActions,
        'moreActions' => $saleMoreActions,
        'infoItems' => $saleInfoItems,
    ])

    <x-section-nav
        label="Sale page sections"
        :items="[
            ['id' => 'sale-overview-section', 'label' => 'Overview'],
            ['id' => 'sale-billing-actions', 'label' => 'Invoice'],
            ['id' => 'sale-payments-section', 'label' => 'Payments'],
            ['id' => 'sale-details-section', 'label' => 'Details'],
            ['id' => 'sale-products-section', 'label' => 'Products'],
            ['id' => 'sale-activity-timeline', 'label' => 'Timeline'],
        ]"
    />

    <div class="section-nav-target" id="sale-overview-section"></div>

    @if($isAutoGeneratedRentalSale && $sale->rental)
        <div style="background:#fff7ed;color:#9a3412;border:1px solid #fed7aa;padding:12px 14px;border-radius:12px;">
            This sale was created from <a href="{{ route('rentals.show', $sale->rental) }}" class="ops-btn-light" style="margin-left:8px;">Rental #{{ $sale->rental->id }}</a>.
            Billing actions can be handled here, and line edits still live in the rental's New Products section.
        </div>
    @endif

    <div class="ops-card section-nav-target" id="sale-billing-actions">
        <div class="ops-card-head">
            <div>
                <h2>Billing Actions</h2>
                <div style="color:#64748b; font-size:12px; margin-top:4px;">
                    {{ $saleInvoiceId ? 'Use these actions directly from the sale page.' : 'Generate the invoice here, then record full or partial payment without leaving the sale.' }}
                </div>
            </div>
            @if($saleInvoiceId)
                <span class="badge" style="{{ $statusTone }}">
                    {{ ucfirst($saleInvoiceStatus ?: 'unpaid') }}
                    @if($saleInvoiceDue > 0)
                        · Due {{ $currency($saleInvoiceDue) }}
                    @endif
                </span>
            @endif
        </div>
        <div class="ops-card-body">
            <div style="display:flex; gap:8px; flex-wrap:wrap;">
                @if($isAutoGeneratedRentalSale && $sale->rental)
                    <a href="{{ route('rentals.edit', $sale->rental) }}" class="ops-btn-light">Edit Rental</a>
                @elseif($canUpdateSales)
                    <a href="{{ route('sales.edit', $sale) }}" class="ops-btn-light">Edit Sale</a>
                @endif
                @if($saleInvoiceId)
                    <a href="{{ route('invoices.show', $saleInvoiceId) }}" class="ops-btn-light">Open Invoice</a>
                @elseif($canUpdateSales)
                    <form action="{{ route('sales.invoice', $sale) }}" method="POST" style="margin:0;">
                        @csrf
                        <button type="submit" class="ops-btn-light">Generate Invoice</button>
                    </form>
                @endif
                @if($canCreatePayments && !in_array($saleInvoiceStatus, ['paid', 'cancelled'], true))
                    <form action="{{ route('sales.markPaid', $sale) }}" method="POST" style="margin:0;">
                        @csrf
                        <button type="submit" class="ops-btn">Mark as Paid</button>
                    </form>
                @endif
            </div>
            @if($canCreatePayments && !in_array($saleInvoiceStatus, ['paid', 'cancelled'], true))
                <form action="{{ route('sales.recordPayment', $sale) }}" method="POST" class="sale-billing-grid">
                    @csrf
                    <div>
                        <span style="display:block; color:#64748b; font-size:11px; font-weight:700; text-transform:uppercase; letter-spacing:.05em;">Payment Date</span>
                        <input type="date" name="payment_date" value="{{ old('payment_date', now()->toDateString()) }}" style="width:100%; min-height:38px; border:1px solid #cbd5e1; border-radius:10px; padding:8px 10px; font-size:13px;">
                    </div>
                    <div>
                        <span style="display:block; color:#64748b; font-size:11px; font-weight:700; text-transform:uppercase; letter-spacing:.05em;">Amount</span>
                        <input type="number" step="0.01" min="0.01" name="amount" value="{{ old('amount', $saleInvoiceDue > 0 ? number_format($saleInvoiceDue, 2, '.', '') : '') }}" style="width:100%; min-height:38px; border:1px solid #cbd5e1; border-radius:10px; padding:8px 10px; font-size:13px;">
                    </div>
                    <div>
                        <span style="display:block; color:#64748b; font-size:11px; font-weight:700; text-transform:uppercase; letter-spacing:.05em;">Payment Method</span>
                        <input type="text" name="payment_method" value="{{ old('payment_method', 'other') }}" placeholder="cash / upi / bank" style="width:100%; min-height:38px; border:1px solid #cbd5e1; border-radius:10px; padding:8px 10px; font-size:13px;">
                    </div>
                    <div>
                        <span style="display:block; color:#64748b; font-size:11px; font-weight:700; text-transform:uppercase; letter-spacing:.05em;">Notes</span>
                        <input type="text" name="notes" value="{{ old('notes') }}" placeholder="Partial payment note" style="width:100%; min-height:38px; border:1px solid #cbd5e1; border-radius:10px; padding:8px 10px; font-size:13px;">
                    </div>
                    <div style="grid-column:1 / -1; display:flex; justify-content:flex-end;">
                        <button type="submit" class="ops-btn-light">Record Partial Payment</button>
                    </div>
                </form>
            @endif
        </div>
    </div>

    <div class="summary-grid">
        <div class="summary-tile">
            <span>Sale Date</span>
            <strong>{{ $sale->sale_date ? \Carbon\Carbon::parse($sale->sale_date)->format('d M Y') : '-' }}</strong>
        </div>
        <div class="summary-tile">
            <span>Reminder / Billing Contact</span>
            <strong>{{ $sale->billingContactName() ?: 'N/A' }}</strong>
        </div>
        <div class="summary-tile">
            <span>Delivery Contact</span>
            <strong>{{ $sale->deliveryContactName() ?: 'N/A' }}</strong>
        </div>
        <div class="summary-tile">
            <span>Items / Qty</span>
            <strong>{{ $saleItemsCount }} line(s) · {{ $saleItemsQuantity }}</strong>
        </div>
        <div class="summary-tile">
            <span>Status</span>
            <strong>
                <span class="badge" style="{{ $statusTone }}">
                    {{ ucfirst($sale->payment_status ?: 'pending') }}
                </span>
            </strong>
        </div>
        <div class="summary-tile">
            <span>GST Mode</span>
            <strong>{{ $sale->gstLabel() }}</strong>
        </div>
    </div>

    <div class="ops-card section-nav-target" id="sale-payments-section">
        <div class="ops-card-head">
            <div>
                <h2>Payment History</h2>
                <div style="color:#64748b; font-size:12px; margin-top:4px;">Delete incorrect sale invoice payments here before deleting the sale record.</div>
            </div>
            @if($saleInvoiceId)
                <a href="{{ route('invoices.show', $saleInvoiceId) }}" class="ops-btn-light">Open Invoice</a>
            @endif
        </div>
        <div class="ops-card-body">
            @if(!empty($saleInvoice) && $saleInvoice->payments->isNotEmpty())
                <div class="sale-payment-history-list">
                    @foreach($saleInvoice->payments as $payment)
                        <div class="sale-payment-history-item">
                            <div>
                                <span style="display:block; color:#64748b; font-size:11px; font-weight:700; text-transform:uppercase; letter-spacing:.05em;">Date</span>
                                <strong>{{ optional($payment->payment_date)->format('d M Y') ?: '-' }}</strong>
                            </div>
                            <div>
                                <strong>{{ $payment->paymentMethodLabel() }}</strong>
                                <div style="color:#64748b; font-size:12px;">{{ $payment->notes ?: 'Sale invoice payment' }}</div>
                            </div>
                            <div>
                                <span style="display:block; color:#64748b; font-size:11px; font-weight:700; text-transform:uppercase; letter-spacing:.05em;">Amount</span>
                                <strong>{{ $currency($payment->amount) }}</strong>
                            </div>
                            @if($canDeletePayments)
                                <form action="{{ route('payments.destroy', $payment) }}" method="POST" style="margin:0;">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="ops-btn-light" style="border-color:#fecaca;color:#b91c1c;" onclick="return confirm('Delete this payment? Sale invoice balance and sale payment status will be recalculated.');">Delete</button>
                                </form>
                            @endif
                        </div>
                    @endforeach
                </div>
            @else
                <div style="color:#64748b;">No payments recorded for this sale invoice.</div>
            @endif
        </div>
    </div>

    <div class="ops-card section-nav-target" id="sale-details-section">
        <div class="ops-card-head">
            <h2>Sale Details</h2>
        </div>
        <div class="ops-card-body">
            <div class="detail-grid">
                <div class="detail-item">
                    <span>Primary Product</span>
                    <strong>{{ $sale->product->name ?? 'N/A' }}</strong>
                </div>
                <div class="detail-item">
                    <span>Delivery Phone</span>
                    <div>{{ $sale->deliveryContactPhone() ?? 'N/A' }}</div>
                </div>
                <div class="detail-item">
                    <span>Billing Phone</span>
                    <div>{{ $sale->billingContactPhone() ?? 'N/A' }}</div>
                </div>
                @if($canViewFinance)
                    <div class="detail-item">
                        <span>Sale Amount</span>
                        <strong>{{ $currency($sale->sale_amount) }}</strong>
                    </div>
                    <div class="detail-item">
                        <span>Unit Price</span>
                        <div>{{ $currency($sale->unit_price ?? 0) }}</div>
                    </div>
                    <div class="detail-item">
                        <span>Discount</span>
                        <div>{{ $currency($sale->discount_amount ?? 0) }}</div>
                    </div>
                    <div class="detail-item">
                        <span>Shipping Cost</span>
                        <div>{{ $currency($sale->resolvedShippingCharges()) }}</div>
                    </div>
                    <div class="detail-item">
                        <span>GST %</span>
                        <div>{{ number_format((float) ($sale->tax_percentage ?? 0), 2) }}%</div>
                    </div>
                @endif
                <div class="detail-item">
                    <span>Invoice Link</span>
                    <div>
                        @if($saleInvoiceId)
                            <a href="{{ route('invoices.show', $saleInvoiceId) }}" class="ops-btn-light">Open Invoice #{{ $saleInvoiceId }}</a>
                        @else
                            @if($canUpdateSales)
                                <form action="{{ route('sales.invoice', $sale) }}" method="POST" style="margin:0;">
                                    @csrf
                                    <button type="submit" class="ops-btn-light">Create Invoice</button>
                                </form>
                            @else
                                No invoice linked yet
                            @endif
                        @endif
                    </div>
                </div>
                <div class="detail-item">
                    <span>Delivery Assignment</span>
                    <div>
                        @if(!$isAutoGeneratedRentalSale && $hasSaleDeliverySupport && $sale->relationLoaded('deliveryRecord') && $sale->deliveryRecord)
                            <div style="display:flex; gap:8px; flex-wrap:wrap;">
                                <a href="{{ route('deliveries.show', $sale->deliveryRecord) }}" class="ops-btn-light">
                                    {{ $deliveryStatusLabel($sale->deliveryRecord->status) }}
                                </a>
                                @if($canUpdateDeliveries)
                                    <a href="{{ route('deliveries.edit', $sale->deliveryRecord) }}" class="ops-btn-light">Edit Assignment</a>
                                @endif
                                @if($canUpdateDeliveries && $sale->deliveryRecord->status === 'pending')
                                    <form action="{{ route('deliveries.in_progress', $sale->deliveryRecord) }}" method="POST" style="margin:0;">
                                        @csrf
                                        @method('PUT')
                                        <button type="submit" class="ops-btn-light">Start Delivery</button>
                                    </form>
                                @endif
                                @if($canUpdateDeliveries && $sale->deliveryRecord->status === 'in_progress')
                                    <form action="{{ route('deliveries.complete', $sale->deliveryRecord) }}" method="POST" style="margin:0;">
                                        @csrf
                                        @method('PUT')
                                        <button type="submit" class="ops-btn-success">Complete Delivery</button>
                                    </form>
                                @endif
                                <span class="ops-muted" style="align-self:center;">Assigned to: {{ $assignedPersonLabel($sale->deliveryRecord) }}</span>
                            </div>
                        @elseif(!$isAutoGeneratedRentalSale && $canCreateDeliveries && $hasSaleDeliverySupport)
                            <a href="{{ route('deliveries.create', ['sale_id' => $sale->id, 'type' => 'delivery']) }}" class="ops-btn-light">Assign Delivery</a>
                        @else
                            Not assigned
                        @endif
                    </div>
                </div>
                <div class="detail-item">
                    <span>Linked Asset</span>
                    <div>
                        @if($sale->asset)
                            {{ $sale->asset->serial_number ?: $sale->asset->asset_name ?: ('Asset #' . $sale->asset->id) }}
                        @else
                            Not linked
                        @endif
                    </div>
                </div>
                <div class="detail-item">
                    <span>Linked Rental</span>
                    <div>
                        @if($sale->rental)
                            Rental #{{ $sale->rental->id }}
                        @else
                            Not linked
                        @endif
                    </div>
                </div>
                <div class="detail-item" style="grid-column:1 / -1;">
                    <span>Notes</span>
                    <div>{{ $sale->notes ?: 'No notes added for this sale.' }}</div>
                </div>
            </div>
        </div>
    </div>

    <div class="ops-card section-nav-target" id="sale-products-section">
        <div class="ops-card-head">
            <h2>Product Items</h2>
        </div>
        <div class="ops-card-body">
            <div style="display:grid; gap:10px;">
                @foreach($saleItems as $saleItem)
                    <div style="border:1px solid #e2e8f0; border-radius:12px; padding:12px 14px; background:#fcfdff;">
                        <div style="display:flex; justify-content:space-between; gap:12px; flex-wrap:wrap;">
                            <div>
                                <strong>{{ $saleItem->product?->name ?? 'Sale product' }}</strong>
                                <div style="color:#64748b; font-size:12px; margin-top:4px;">
                                    Qty {{ (int) ($saleItem->quantity ?? 0) }} · Unit {{ $currency($saleItem->unit_price ?? 0) }}
                                    @if($saleItem->asset)
                                        · Asset {{ $saleItem->asset->serial_number ?: $saleItem->asset->asset_name ?: ('#' . $saleItem->asset->id) }}
                                    @endif
                                </div>
                            </div>
                            <div style="text-align:right;">
                                <div style="color:#64748b; font-size:11px; font-weight:700; text-transform:uppercase; letter-spacing:.05em;">Line Total</div>
                                <strong>{{ $currency($saleItem->line_total ?? 0) }}</strong>
                            </div>
                        </div>
                        <div style="display:flex; gap:14px; flex-wrap:wrap; color:#475569; font-size:12px; margin-top:8px;">
                            <span>Discount {{ $currency($saleItem->discount_amount ?? 0) }}</span>
                            <span>GST {{ number_format((float) ($saleItem->tax_percentage ?? 0), 2) }}% {{ ucfirst($saleItem->tax_calculation_mode ?? 'exclusive') }}</span>
                        </div>
                        @if($saleItem->notes)
                            <div style="color:#64748b; font-size:12px; margin-top:8px;">{{ $saleItem->notes }}</div>
                        @endif
                    </div>
                @endforeach
            </div>
        </div>
    </div>

    @if(!$isAutoGeneratedRentalSale && $canDeleteSales)
        <div class="sale-show-actions hide-on-mobile">
            <form action="{{ route('sales.destroy', $sale) }}" method="POST" style="margin:0;">
                @csrf
                @method('DELETE')
                <button type="submit" class="ops-btn-light" onclick="return confirm('Delete this sale record?')">Delete Sale</button>
            </form>
        </div>
    @endif
</div>

<div class="section-nav-target" id="sale-activity-timeline">
    @include('partials.activity-timeline', [
        'timeline' => $activityLogs ?? collect(),
        'title' => 'Operations History',
        'subtitle' => 'Invoice, payment status, delivery, and order updates linked to this sale.',
        'timelineFilter' => $timelineFilter ?? 'all',
        'timelineRoute' => 'sales.show',
        'noteAction' => route('sales.notes.store', $sale),
        'noteLabel' => 'Add Note',
        'anchorId' => 'sale-activity-timeline',
    ])
</div>

@include('partials.mobile-action-bar', [
    'label' => 'Sale mobile actions',
    'moreLabel' => 'Sale secondary actions',
    'actions' => $mobilePrimaryActions->all(),
    'moreActions' => $mobileMoreActions->all(),
])
@include('partials.follow-up-modal')
@endsection
