@extends('layouts.app')

@section('content')
@include('invoices._form', [
    'pageTitle' => 'Create Invoice',
    'pageSubtitle' => 'Create a GST-ready invoice for rental, sale, or mixed items.',
    'formAction' => route('invoices.store'),
    'formMethod' => 'POST',
    'submitLabel' => 'Save Invoice',
    'invoice' => null,
    'invoiceNumberValue' => old('invoice_number', $invoiceNumber),
    'invoiceDateValue' => old('invoice_date', date('Y-m-d')),
    'dueDateValue' => old('due_date'),
    'purchaseOrderNumberValue' => old('purchase_order_number'),
    'purchaseOrderDateValue' => old('purchase_order_date'),
    'referenceNumberValue' => old('reference_number'),
    'selectedCustomerId' => old('customer_id'),
    'placeOfSupplyStateValue' => old('place_of_supply_state', $organization->state),
    'billToNameValue' => old('bill_to_name'),
    'billToPhoneValue' => old('bill_to_phone'),
    'billToEmailValue' => old('bill_to_email'),
    'billToAddressValue' => old('bill_to_address'),
    'billToCityValue' => old('bill_to_city'),
    'billToStateValue' => old('bill_to_state'),
    'billToStateCodeValue' => old('bill_to_state_code'),
    'billToPincodeValue' => old('bill_to_pincode'),
    'billToGstinValue' => old('bill_to_gstin'),
    'shipToNameValue' => old('ship_to_name'),
    'shipToPhoneValue' => old('ship_to_phone'),
    'shipToAddressValue' => old('ship_to_address'),
    'shipToCityValue' => old('ship_to_city'),
    'shipToStateValue' => old('ship_to_state'),
    'shipToStateCodeValue' => old('ship_to_state_code'),
    'shipToPincodeValue' => old('ship_to_pincode'),
    'notesValue' => old('notes'),
    'termsValue' => old('terms_conditions', $organization->default_terms),
    'depositAmountValue' => old('deposit_amount', 0),
    'shippingChargesValue' => old('shipping_charges', 0),
    'paidAmountValue' => old('paid_amount', 0),
])
@endsection
