@extends('layouts.app')

@section('content')
@include('invoices._form', [
    'pageTitle' => 'Edit Invoice',
    'pageSubtitle' => 'Update invoice details, line items, and settlement amounts.',
    'formAction' => route('invoices.update', $invoice->id),
    'formMethod' => 'PUT',
    'submitLabel' => 'Update Invoice',
    'invoice' => $invoice,
    'invoiceNumberValue' => old('invoice_number', $invoice->invoice_number),
    'invoiceDateValue' => old('invoice_date', optional($invoice->invoice_date)->format('Y-m-d')),
    'dueDateValue' => old('due_date', optional($invoice->due_date)->format('Y-m-d')),
    'purchaseOrderNumberValue' => old('purchase_order_number', $invoice->purchase_order_number),
    'purchaseOrderDateValue' => old('purchase_order_date', optional($invoice->purchase_order_date)->format('Y-m-d')),
    'referenceNumberValue' => old('reference_number', $invoice->reference_number),
    'selectedCustomerId' => old('customer_id', $invoice->customer_id),
    'placeOfSupplyStateValue' => old('place_of_supply_state', $invoice->place_of_supply_state),
    'billToNameValue' => old('bill_to_name', $invoice->bill_to_name),
    'billToPhoneValue' => old('bill_to_phone', $invoice->bill_to_phone),
    'billToEmailValue' => old('bill_to_email', $invoice->bill_to_email),
    'billToAddressValue' => old('bill_to_address', $invoice->bill_to_address),
    'billToCityValue' => old('bill_to_city', $invoice->bill_to_city),
    'billToStateValue' => old('bill_to_state', $invoice->bill_to_state),
    'billToStateCodeValue' => old('bill_to_state_code', $invoice->bill_to_state_code),
    'billToPincodeValue' => old('bill_to_pincode', $invoice->bill_to_pincode),
    'billToGstinValue' => old('bill_to_gstin', $invoice->bill_to_gstin),
    'shipToNameValue' => old('ship_to_name', $invoice->ship_to_name),
    'shipToPhoneValue' => old('ship_to_phone', $invoice->ship_to_phone),
    'shipToAddressValue' => old('ship_to_address', $invoice->ship_to_address),
    'shipToCityValue' => old('ship_to_city', $invoice->ship_to_city),
    'shipToStateValue' => old('ship_to_state', $invoice->ship_to_state),
    'shipToStateCodeValue' => old('ship_to_state_code', $invoice->ship_to_state_code),
    'shipToPincodeValue' => old('ship_to_pincode', $invoice->ship_to_pincode),
    'notesValue' => old('notes', $invoice->notes),
    'termsValue' => old('terms_conditions', $invoice->terms_conditions),
    'depositAmountValue' => old('deposit_amount', $invoice->deposit_amount),
    'shippingChargesValue' => old('shipping_charges', $invoice->shipping_charges),
    'paidAmountValue' => old('paid_amount', $invoice->paid_amount),
])
@endsection
